### ISSUE TITLE
Escape when autocomplete visible moves focus in PhpStorm

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1399] opened 2022-05-02 01:23 UTC
> If I hit Esc key then for some reason the focus/cursor jumps to the editor tab and out of the terminal

**Comment by chrisnoden** [comment] 2022-05-03 12:15
This was particularly obvious with https://github.com/withfig/autocomplete/pull/1199

I was originally experiencing this trying to get the `yarn upgrade` command to run when drop down was appearing. Because this is now resolved I suspect this is a "feature" of PhpStorm and not Fig, but I've put steps to reproduce plus a video below.

NB: My Fig appears to have updated to include the above merged fix, so I have to hit space after `yarn upgrade` to get the Fig drop down. Then I hit `Esc` twice and you'll see the active cursor returns to the editor

https://user-images.githubusercontent.com/2600554/166450343-2b7f6ac5-b06f-4417-97b0-5b011e4e60b5.mov

**Comment by mschrage** [comment] 2022-05-06 17:26
I am not able to reproduce this. It seems like you might have a keybinding in PhpStorm that is causing this.

Will close this issue for now.

**Closed by mschrage** 2022-05-06 17:26 UTC
Labels: type:bug, codebase:autocomplete-app
