### ISSUE TITLE
Fig settings file is corrupted

### ISSUE THREAD

**Issue by ptg251294** [withfig/fig#2001] opened 2022-11-06 19:26 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

The expectation was to open fig settings but was displayed an error instead.

### Actual behaviour

Getting error:
Error: Failed setting using_cognito: EOF while parsing a value at line 1 column 0

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/pulkitkewlani
  - exe-path: /Users/pulkitkewlani/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: d517a2f3-826b-4775-902c-8c2228f7a1ac
    - FIG_HOSTNAME: Pulkit-Kewlani
    - FIG_TERM: 2.7.5
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/pulkitkewlani/.fig/bin:/Users/pulkitkewlani/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 35506
    - FIG_PARENT: d517a2f3-826b-4775-902c-8c2228f7a1ac
    - FIG_SET_PARENT: d517a2f3-826b-4775-902c-8c2228f7a1ac
```

**Comment by SeparateRecords** [comment] 2022-11-07 02:43
Hey @ptg251294! This is unrelated to settings, it's a weird auth bug. Going to close this now as duplicate of #1997

**Closed by SeparateRecords** 2022-11-07 02:43 UTC
Labels: type:bug, NEED_TO_LABEL
