### ISSUE TITLE
No autocomplete over SSH connnection

### ISSUE THREAD

**Issue by e36Alex** [withfig/fig#561] opened 2021-11-01 20:12 UTC
Hello,

fig runs fine at local terminal in iTerm2, but when I login into a ssh-session autocomplete doesn't work any more.
So I ran _fig tools doctor_ with the following error as result:

`alexander@MacBook-Pro ~ % fig tools doctor

Let's make sure Fig is running...

Fig bin exists: pass
Fig in path: pass
Fig running: pass
macOS version: pass

Let's see what fig diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: pass
CLI installed: pass
CLI tool path: pass
Accessibility enabled: pass
Autocomplete specs installed: fail

I can fix this!

> /Users/Alexander/.fig/bin/fig update

Pulling most up-to-date completion specs...
Run fig docs to learn how to contribute your own!

tar: specs: Not found in archive
tar: Error exit delayed from previous errors.

Fix applied!

Let's restart our checks to see if the problem is resolved...

Let's make sure Fig is running...

Fig bin exists: pass
Fig in path: pass
Fig running: pass
macOS version: pass

Let's see what fig diagnostic tells us...

Compatible shell: pass
Bundle path: pass
Autocomplete enabled: pass
CLI installed: pass
CLI tool path: pass
Accessibility enabled: pass
Autocomplete specs installed: fail

Looks like we've already tried this fix before and it's not working.

Run fig issue to let us know!`

**Comment by mschrage** [comment] 2021-11-02 01:22
Hey @e36Alex! Currently autocomplete over SSH is not supported, but we are actively working on this and it should be included in the next week or so!

**Comment by e36Alex** [comment] 2021-12-30 21:53
Any news on this? Really looking forward for this feature!

**Comment by mschrage** [comment] 2021-12-30 22:14
@e36Alex since we launched publicly in mid-November, stability issues took precedence over new features.

We've done a big rewrite of our shell integrations which should make it possible to add support, but don't have a concrete date just yet!

**Comment by mschrage** [comment] 2022-03-11 20:51
We have made a bunch of progress on SSH. If you are in our Discord community, ping in the #user-help channel and I will help you get setup.

Closing as a duplicate of #709 (our main tracking issue for this)

**Closed by mschrage** 2022-03-11 20:51 UTC
Labels: feature_request, integration:ssh
