### ISSUE TITLE
[aws] Loadspec doesn't show autocomplete results when nested by 2 levels

### ISSUE THREAD

**Issue by abhishekkh** [withfig/fig#848] opened 2022-01-29 03:39 UTC
I have a master CLI which wraps around all the CLIs like terraform, kubectl and aws using loadspec. I have had no issues with tf and k8s, but for aws since we have another level of nesting with loadspecs I am not seeing any autocomplete options. 

`mycli -- terraform plan` works 
`mycli -- aws s3` does not

Had a quick chat with @mschrage and he was able to reproduce it. Here is my spec for reference

```
const completionSpec: Fig.Spec = {
  name: "my",
  description: "My CLI",
  subcommands: [
    {
      name: "kube",
      description: "Wrapper for kubectl CLI",
      subcommands: [
        {
          name: "--",
          description: "Kubectl command",
          loadSpec: "kubectl",
        },
      ],
    },
    {
      name: "aws",
      description: "Wrapper for aws CLI",
      subcommands: [
        {
          name: "--",
          description: "Aws command",
          loadSpec: "aws",
        },
      ],
    },
    {
      name: "terraform",
      description: "Wrapper for terraform CLI",
      subcommands: [
        {
          name: "--",
          description: "Terraform command",
          loadSpec: "terraform",
        },
      ],
    },
  ],
};

export default completionSpec;
```

**Comment by mschrage** [comment] 2022-01-29 04:04
Thanks for reporting this @abhishekkh!

@fedeci can you look into what's going on here? My initial thought was that it had something to do with the "--" naming. However, I tried renaming the subcommand and could still reproduce.

<img width="724" alt="Screen Shot 2022-01-28 at 8 03 23 PM" src="https://user-images.githubusercontent.com/3155109/151646609-58c6d0a5-8a82-47db-8ecf-d4ee22c9d6d8.png">

The spec was successfully loaded. The error seems to be "Cannot consume subcommand arg."

**Comment by fedeci** [comment] 2022-02-23 19:05
This will be fixed with the next AE version!

**Closed by fedeci** 2022-02-23 19:05 UTC
Labels: bug, codebase:autocomplete_app

**Comment by abhishekkh** [comment] 2022-03-17 17:41
> This will be fixed with the next AE version!

Is this out yet? @fedeci  Thanks for fixing it
