### ISSUE TITLE
Misconfigured `PATH` is calling different `fig` binary

### ISSUE THREAD

**Issue by murilo** [withfig/fig#1176] opened 2022-03-24 19:42 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Last login: Thu Mar 24 16:40:03 on ttys000
Traceback (most recent call last):
  File "/Users/mh/.pyenv/versions/3.8.8/bin/fig", line 33, in <module>
    sys.exit(load_entry_point('fig==1.0.1', 'console_scripts', 'fig')())
  File "/Users/mh/.pyenv/versions/3.8.8/bin/fig", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/site-packages/fig/__init__.py", line 2, in <module>
    from .service import Service  # noqa:flake8
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/site-packages/fig/service.py", line 398
    except StreamOutputError, e:
                            ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/mh/.pyenv/versions/3.8.8/bin/fig", line 33, in <module>
    sys.exit(load_entry_point('fig==1.0.1', 'console_scripts', 'fig')())
  File "/Users/mh/.pyenv/versions/3.8.8/bin/fig", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/site-packages/fig/__init__.py", line 2, in <module>
    from .service import Service  # noqa:flake8
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/site-packages/fig/service.py", line 398
    except StreamOutputError, e:
                            ^
SyntaxError: invalid syntax

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [Brazilian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/mh/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment] 2022-03-24 19:53
Hey @murilo! It seems like a different `fig` binary is in your PATH and is getting invoked instead of ours, which is located in `~/.local/bin/fig`

Can you share your zshrc/zprofile?

**Comment by murilo** [comment] 2022-03-24 20:34
# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
eval "$(fig init zsh pre)"

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:$HOME/flutter/bin:/Applications/Julia-1.6.app/Contents/Resources/julia/bin/:/usr/local/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/icu4c/sbin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/mh/.oh-my-zsh"
ZSH_THEME="agnoster"
COMPLETION_WAITING_DOTS="true"

plugins=(
	git
	docker
	macos
	emoji
	emoji-clock
	)

source $ZSH/oh-my-zsh.sh

export PATH="/Users/mh/.pyenv/versions/3.8.8/bin:$PATH"
eval "$(pyenv init -)"
export WORKON_HOME=~/.virtualenvs
mkdir -p $WORKON_HOME

export PATH="/usr/local/opt/tcl-tk/bin:$PATH"

# Fig post block. Keep at the bottom of this file.
eval "$(fig init zsh post)"

**Comment by mschrage** [comment] 2022-03-24 20:54
It seems like the line:
```
export PATH="/Users/mh/.pyenv/versions/3.8.8/bin:$PATH"`
```
is responsible for this. 

Based on the pyenv installation guide, you might be able to remove the offending line and replace it with the following:
```
eval "$(pyenv init --path)"
```

If this, doesn't resolve the issue, you can follow the instructions in this issue #1167

**Comment by murilo** [comment] 2022-03-24 21:57
not worked... maybe my python version? example:

echo $HOME
/Users/mh
Traceback (most recent call last):
  File "/Users/mh/.pyenv/versions/3.8.8/bin/fig", line 33, in <module>
    sys.exit(load_entry_point('fig==1.0.1', 'console_scripts', 'fig')())
  File "/Users/mh/.pyenv/versions/3.8.8/bin/fig", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/site-packages/fig/__init__.py", line 2, in <module>
    from .service import Service  # noqa:flake8
  File "/Users/mh/.pyenv/versions/3.8.8/lib/python3.8/site-packages/fig/service.py", line 398
    except StreamOutputError, e:
                            ^
SyntaxError: invalid syntax

**Comment by mschrage** [comment] 2022-03-24 22:58
Fig doesn't use python. To be clear, the issue is that a _different_ binary also named `fig` is in your PATH. That executable is being called rather than the Fig CLI.

Try removing this line entirely:
```
export PATH="/Users/mh/.pyenv/versions/3.8.8/bin:$PATH"
```

**Comment by SeparateRecords** [comment] 2022-04-20 06:07
Are we able to close this? Seems like this isn't something we can fix. @murilo is it working for you now after trying Matt's suggestion?

**Closed** 2022-04-20 06:38 UTC
Labels: awaiting user reply
