### ISSUE TITLE
Support autocomplete for the Android Studio terminal

### ISSUE THREAD

**Issue by jonas-zebari** [withfig/fig#402] opened 2021-08-28 19:18 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
Ideally the support for the Android Studio terminal would function pretty much the exact same way as support for  VS Code and other terminals. The AS terminal can be moved around/windowed/etc. in the same ways as the VS Code terminal inside the main window.

**Comment by mschrage** [comment] 2022-03-09 22:30
This is a soft duplicate of #49. I'll leave open for now.

**Comment by mjwaghmare** [comment] 2022-03-24 08:36
Is Android Studio Support done? Its not working like VSCODE

**Closed** 2022-08-31 18:21 UTC
Labels: type:integration-request
