### ISSUE TITLE
Android Studio autocomplete in terminal not working as default terminal 😢 

### ISSUE THREAD

**Issue by mjwaghmare** [withfig/fig#1171] opened 2022-03-24 08:52 UTC
### Description:
> Not showing the autocomplete dialog

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [ABC - India] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/user/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/user/.local/bin:/Users/user/.fig/bin:/Users/user/.local/bin:/Users/user/Documents/src/flutter/bin:/Users/user/.local/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment] 2022-03-24 20:47
Hey @mjwaghmare! Can you provide any more information about what isn't working?

I am not sure what the issue is based on the details you've included.  What do you mean by "android autocomplete" - is this in reference to a specific CLI tool?

**Comment by mjwaghmare** [comment] 2022-03-26 05:43
When I use fig in VS Code in terminal its opens up a dialog of auto complete, but same thing not comes up in the Android studio terminal

**Comment by mschrage** [comment] 2022-03-26 05:44
Ah I see. Thanks for clarifying @mjwaghmare.

This is actually a duplicate of #49 - we should have support coming soon!

**Closed by mschrage** 2022-03-26 05:44 UTC
Labels: awaiting user reply

**Comment by mjwaghmare** [comment] 2022-03-26 05:46
Great so there will be an update for Android studio right?

**Comment by mschrage** [comment] 2022-03-26 05:50
It is on the roadmap!

**Comment by mjwaghmare** [comment] 2022-03-26 05:56
> 

🥳🤩

**Comment by mschrage** [comment] 2022-03-26 06:52
No time like the present to turn the roadmap into reality. Thanks for reminding me to do this :)

<img width="521" alt="Screen Shot 2022-03-25 at 11 49 38 PM" src="https://user-images.githubusercontent.com/3155109/160228457-42fab959-a49a-4f64-867a-2873f8d75309.png">

Support for Android Studio will be available as an experimental integration in the next release!

**Comment by mjwaghmare** [comment] 2022-03-27 16:57
Awesome Please ASAP
