### ISSUE TITLE
New iTerm sessions crash with `A session ended very soon after starting. Check that the command in profile "Default" is correct`

### ISSUE THREAD

**Issue by ubolonton** [withfig/fig#88] opened 2021-05-26 03:25 UTC
**Summary:**
Fig crashes new iTerm sessions.

**Steps to Reproduce:**

1. Install Fig without giving work email to finish. Accessibility was configured.
1. Restart iTerm.

**Expected Results:**
iTerm continues to work.

**Actual Results:**
New iTerm sessions crash with `A session ended very soon after starting. Check that the command in profile "Default" is correct`.
Changing the command does not help.

**System information:**
OS: MacOS Catalina 10.15.7
Terminal: iTerm2
Version of Fig: Latest, as of now. There is nowhere to get that information.

**Additional Notes:**

* iTerm worked normally right before installing Fig.
* Removing added code in `.zshrc`, `.profile`, `.bashrc` does not help.
* `Terminal` does not crash.
* After a restart, new iTerm sessions just crash without any error message.
* The overall experience is terrible:
  * Adding additional code into .profile and .zshrc without letting user know.
  * User can't finish installation without giving work email.
  * The installation popup cannot be hidden.

**Comment by lou-lan** [comment] 2021-05-26 03:47
```
fig_precmd_hook: command not found: fig
$ ~ fig_hide:1: command not found: fig
reboot
fig_precmd_hook: command not found: fig
$ ~
fig_precmd_hook: command not found: fig
$ ~
fig_precmd_hook: command not found: fig

```
I have the same problem

**Comment by ubolonton** [comment] 2021-05-26 03:49
Temporary workaround (with MacPorts installed):
List installed iTerm version:
```
port installed iTerm2
```
Activate another iTerm version:
```
sudo port activate iTerm2@<another-version>
```

**Comment by mschrage** [comment] 2021-08-04 21:39
This should be fixed as of v1.0.47.

**Closed by mschrage** 2021-08-04 21:39 UTC
Labels: bug, terminal:iTerm

**Comment by Nutlope** [comment] 2021-08-11 02:48
@mschrage I'm seeing this error when I install Fig then update to the beta.

**Comment by mschrage** [comment] 2021-08-11 16:20
There are two different issues here I believe. One caused by the version of iTerm being too low or beta/nightly.

**Comment by rovente** [comment] 2022-03-26 07:04
Exactly same here, in march 2022.
I've tried several time, since a year ago, hoping that this bug will be fixed, but I'm exactly in the same situation.
Even the mac terminal is crashing, the only solution is uninstall fig at the moment.

System information:
OS: MacOS Mojave 10.14.4
Terminal: iTerm2
Version of Fig: Latest, as of now, just reinstalled.

**Comment by mschrage** [comment] 2022-03-26 07:13
Can you run `fig doctor` @rovente?

I think the issue may be that you are on Mojave.

**Comment by rovente** [comment] 2022-03-26 07:25
How can I run `fig doctor` ? @mschrage 
All my terminal crashes

**Comment by rovente** [comment] 2022-03-26 07:33
@mschrage  the debugger menu, after opening a terminal window, display:
"not linked to terminal session." 
"window 2218/%"
"run 'fig doctor' for more details"

the big mess is that also after uninstall fig, all my terminals doesn't work anymore.
I try to restart my mac.

**Comment by rovente** [comment] 2022-03-26 07:42
In my case I was able to restart terminals after activate/deactivate the "Toggle debug logging" in iTerm2.
For some reasons now my terminals work again, also the native mac terminal.
Maybe this operation have reset some files settings, don't know.
Fig is a great idea, had use it in the early times, but after some upgrades last year is become unusable for me.
Hope that this issues will be fixed, thanks

**Comment by rajat-mehraa** [comment] 2024-10-11 10:16
For me, reinstalling iterm latest version worked.
