### ISSUE TITLE
Support Warp

### ISSUE THREAD

**Issue by sietzekeuning** [withfig/fig#1275] opened 2022-04-07 08:27 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Feature Details

Will Warp also be supported in the future? https://www.warp.dev/ looks like a promising new terminal app.

**Comment by mschrage** [comment] 2022-04-07 10:37
Closing as a duplicate of #785

**Closed by mschrage** 2022-04-07 10:37 UTC
Labels: NEED_TO_LABEL
