### ISSUE TITLE
Sometimes fig inserts a suggestions after I type it

### ISSUE THREAD

**Issue by EthanOrlander** [withfig/fig#358] opened 2021-08-15 19:35 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:
Say I type "git commit -A". Sometimes fig will insert it's own "A", so that it reads "git commit -AA", and I need to go back and delete it. I'm not sure what conditions this occurs under or why exactly it's happening. I'll see if I can notice any patterns in the coming days.

Anyone else running into this?

### Environment

```bash
Version 1.0.47 (B257) [Beta] [Dev] [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ethanorlander/.fig/bin/fig
Accessibility: true
Number of specs: 163
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/ethanorlander/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/ethanorlander/Library/Android/sdk/tools:/Users/ethanorlander/Library/Android/sdk/platform-tools:/Users/ethanorlander/.opam/default/bin:/bin:/Users/ethanorlander/.deno/bin:/Users/ethanorlander/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (80328) - ttys027
Current working directory: /Users/ethanorlander/Documents/Personal/ionic-cli-fig
Current window identifier: 89658/code:80317% (com.microsoft.VSCode)
PATH: /Users/ethanorlander/.opam/default/bin:/Users/ethanorlander/Library/Android/sdk/tools:/Users/ethanorlander/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home/bin:/Users/ethanorlander/.deno/bin:/Users/ethanorlander/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/ethanorlander/Library/Android/sdk/tools:/Users/ethanorlander/Library/Android/sdk/platform-tools:/Users/ethanorlander/.opam/default/bin:/Users/ethanorlander/.deno/bin:/Users/ethanorlander/opt/anaconda3/bin:/Users/ethanorlander/.fig/bin:/Users/ethanorlander/.yarn/bin:/Users/ethanorlander/.yarn/bin:/Users/ethanorlander/Library/Android/sdk/tools:/Users/ethanorlander/Library/Android/sdk/platform-tools
FIG_INTEGRATION_VERSION: 4
```

**Comment by fwesss** [comment] 2021-08-17 16:16
We use to see an issue similar to this but it hasn't popped up since we changed the way we read the edit buffer.

Does this sound like what you're experiencing?

> You are typing so quickly Fig can't process your keystrokes in time
> 
> Sometimes when you hit tab or enter to insert a suggestion, Fig thinks what you currently have typed in your terminal is different to what's actually there. 
> 
> e.g. you type `cd desk` then hit enter but Fig only thinks you typed `cd des
> `. 
> The final output will look like `cd deskktop` instead of `cd desktop`

**Comment by EthanOrlander** [comment] 2021-08-17 16:35
@fwesss Yes, that sounds like the same issue I am experiencing. It doesn't happen too often, but enough that it's worth mentioning. I think it might only be happening when I'm doing a lot of things and my computer's struggling to keep up.

**Comment by mschrage** [comment] 2022-03-09 22:19
Closing as a duplicate of #173

**Closed by mschrage** 2022-03-09 22:19 UTC
Labels: bug, codebase:macOS
