### ISSUE TITLE
Always prompted to update to a new version, even when running latest version

### ISSUE THREAD

**Issue by BestWaveRock** [withfig/fig#813] opened 2022-01-24 03:34 UTC
### Description:
> When I am the latest version of fig, after opening the terminal, it still prompts me that there is a new version to update!

look this

<img width="372" alt="截屏2022-01-24 AM11 29 04" src="https://user-images.githubusercontent.com/36351805/150717860-be52b969-22c2-4a56-b490-319f9ca55715.png">
<img width="882" alt="截屏2022-01-24 AM11 29 17" src="https://user-images.githubusercontent.com/36351805/150717869-9c159ad1-b112-42ff-b21c-4b9695c49b43.png">
<img width="1145" alt="截屏2022-01-24 AM11 29 30" src="https://user-images.githubusercontent.com/36351805/150717871-e83c4ac6-9fe2-45f6-a1de-17b35a8c7473.png">

**I need help, the problem needs to be dealt with!**

### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.0|Version 1.0.54 (B359)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.54 (B359) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: false
Settings.json: true
CLI installed: true
CLI tool path: /Users/liangjiaxin/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: true
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /usr/local/opt/openssl@1.1/bin:/usr/local/opt/openjdk@11/bin:/usr/local/opt/php@7.4/sbin:/usr/local/opt/php@7.4/bin:/usr/local/opt/node@14/bin:/usr/local/opt/node@14/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/liangjiaxin/.fig/bin:/Users/liangjiaxin/platform-tools/:/Users/liangjiaxin/platform-tools/
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by BestWaveRock** [comment] 2022-01-24 03:37
When I turn off the AutoUpdate switch, the update message indicates that the problem still exists!
<img width="882" alt="截屏2022-01-24 AM11 36 31" src="https://user-images.githubusercontent.com/36351805/150718073-192b4091-99ab-4721-9849-3c897a61da6b.png">
<img width="992" alt="截屏2022-01-24 AM11 36 43" src="https://user-images.githubusercontent.com/36351805/150718079-129e29bb-e5b2-4b79-9b20-d5dc54482c26.png">

**Comment by BestWaveRock** [comment] 2022-01-24 03:41
Just have a switch in the setting that can turn off the prompt :)

**Comment by mschrage** [comment] 2022-01-24 20:32
Hey @BestWaveRock! Thanks for reporting this. I think the issue is that the shell is not aware that the update has been applied. 

We update `~/.fig/user/config` when an update is available and it seems like we don't reset this in certain (unknown) cases. I'm investigating today.

**Comment by BestWaveRock** [comment] 2022-01-26 07:19
`cat .fig/user/config`

APP_TERMINATED_BY_USER=1DOWNLOAD_TIME=1632382789
LAST_UPDATE=1642994149
FIG_ONBOARDING=1
DONT_SHOW_DRIP=0
DRIP_ONE=0
DRIP_TWO=0
DRIP_THREE=0
DRIP_FOUR=0
DRIP_FIVE=0
DRIP_SIX=0
DRIP_SEVEN=0
DISPLAYED_AUTOUPDATE_SETTINGS_HINT=1
FIG_LOGGED_IN=1
NEW_VERSION_AVAILABLE=1.0.52%

@mschrage 
1.0.52% :)

**Comment by mschrage** [comment] 2022-01-26 07:40
This should be fixed if you update to the latest version (v1.0.55). Run `fig update` in your terminal :)

**Closed by mschrage** 2022-01-26 07:40 UTC
Labels: bug, codebase:macOS, codebase:shell_integrations

**Comment by BestWaveRock** [comment] 2022-01-26 07:52
binggo, tks!
