### ISSUE TITLE
Not Suggest Anything

### ISSUE THREAD

**Issue by ami-pbj** [withfig/fig#2353] opened 2023-02-18 05:37 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.0 (22D49)

### Expected behaviour

Fig always give me suggestions for git and some commands. But today it's not suggesting anything.

### Actual behaviour

Fig is not running after run "fig doctor". Not Suggest anything.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 13.2.0 (22D49)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/purnendubikashjana
  - exe-path: /Users/purnendubikashjana/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 421bd90a-8c0d-4593-bc31-a518202b8b54
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /opt/homebrew/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/purnendubikashjana/.fig/bin:/Users/purnendubikashjana/.local/bin:/usr/local/mysql-8.0.28-macos11-arm64/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 1727
    - FIG_SET_PARENT: 421bd90a-8c0d-4593-bc31-a518202b8b54
```

**Comment by mschrage** [comment] 2023-05-02 17:44
Closing since I cannot reproduce with the information given. Please share a screen recording if you can demonstrate how to trigger this issue.

**Closed by mschrage** 2023-05-02 17:44 UTC
Labels: type:bug, NEED_TO_LABEL
