### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by IVoyt** [withfig/fig#2745] opened 2023-09-25 10:42 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.2 (22G91)

### Expected behaviour

succesfull login and ability to use the software
fig cli available in the system

### Actual behaviour

1. Permanent message
```
Something went wrong :(
Signups are currently disabled
```
<img width="1033" alt="image" src="https://github.com/withfig/fig/assets/10925772/db3df86b-4007-4dfa-b041-60bf857f2fac">

2. Fig cli not found in the system
```
% fig
zsh: command not found: fig
```

### Steps to reproduce

1. Download Fig from official website
2. Move Fig.app from downloaded .dmg to /Applications
3. Select Login with email
4. Input code sent to email

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  - cores: 4
  - mem: 32.00 GB
os-info:
  - macOS 13.5.2 (22G91)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - __CFBundleIdentifier: com.mschrage.fig
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by mschrage** [comment] 2023-09-26 23:37
Duplicate of #2699

**Closed by mschrage** 2023-09-26 23:37 UTC
Labels: NEED_TO_LABEL

**Comment by IVoyt** [comment] 2023-09-27 10:16
> Duplicate of #2699

not a duplicate since fig cli not available in this case
