### ISSUE TITLE
Choose file input web laggy

### ISSUE THREAD

**Issue by necmicolak** [withfig/fig#726] opened 2021-12-17 19:21 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Choose file on web (type=file) if fig running file selection opening laggy.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1.21C52|1.0.53|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.53 (B339) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/necmicolak/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/necmicolak/.fig/bin:/Users/necmicolak/.composer/vendor/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (45336) - /dev/ttys002
Current working directory: /Users/necmicolak
Current window identifier: 4329/% (com.googlecode.iterm2)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/necmicolak/.fig/bin:/Users/necmicolak/.composer/vendor/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:DF8ECF4B-D5F0-409F-B57D-6FBCD6F36E81
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
</pre>
</p>
</details>

**Comment by mschrage** [comment] 2021-12-17 20:13
Hey @necmicolak, this is so strange but very reproducible. I think it has to do with an interaction between Fig's use of the Accessibility API and how Chrome opens popup windows, but not exactly what the root cause is.

I've found a fix that I'll put into the next build.

**Comment by necmicolak** [comment] 2021-12-18 16:02
> 

Safari, Chrome and Opera happening this problem but in firefox no problem.

**Comment by SeparateRecords** [comment] 2022-03-07 22:08
@mschrage was this fixed in 1.0.54? Still happening for me on the latest build

**Comment by mschrage** [comment] 2022-03-08 00:11
No I don't think a fix went out for this.

**Closed** 2022-08-31 18:35 UTC
Labels: type:bug, codebase:macos
