### ISSUE TITLE
`fish` editbuffer is not determined correctly 

### ISSUE THREAD

**Issue by nivintw** [withfig/fig#1828] opened 2022-09-25 21:47 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

There are a few things going on here, and seemingly all related.
BLUF: shell suggestions / autocomplete are not working as expected.

Starting state:
1. Fig is not running
2. iterm2 (terminal of interest) is not running.

Steps to reproduce on my machine:
1. launch fig
2. launch iterm2
3. type `git ` 
4. no completions show; similar to other commands, not just git.

Steps to identify the problem / try fixing it:
1. fig doctor (see below)
2. click on fig icon in menu bar
  2a. after running `fig doctor`:
  2b. "Inserting text into the terminal will fail"
  2c. "figterm socket does not exist for session <session_id>"
3. restart iterm2
4. fig icon -> debugger -> "not linked to terminal session"
5. `fig doctor`
6. get "✔ Everything looks good!" despite autocomplete still not working

results of initial `fig doctor` run:

 fig doctor                                                                                                    

✘ Daemon: Daemon settings watcher error
  No such file or directory (os error 2)
Attempting to fix automatically...
Re-running check...

✔ Daemon

✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B528) [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,2
  - chip-id: Apple M1 Max
  - cores: 10 (8 performance and 2 efficiency)
  - mem: 32 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.5.1/bin/fish
  - terminal: iterm
  - cwd: /Users/tylernivin
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /opt/homebrew/bin/fish
    - TERM_SESSION_ID: w0t0p0:DA015FFC-D956-4D5C-A66F-4C98EABF49E8
    - TERM: xterm-256color
    - FIG_TERM: 1
    - FIG_INTEGRATION_VERSION: 8
    - PATH: /Users/tylernivin/.rd/bin:/Users/tylernivin/.pyenv/shims:/Users/tylernivin/miniconda3/bin:/Users/tylernivin/miniconda3/condabin:/Users/tylernivin/.pyenv/bin:/opt/homebrew/bin:/Users/tylernivin/.fig/bin:/Users/tylernivin/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/tylernivin/.local/bin
    - FIG_TERM_VERSION: 5.2.0
    - FIG_PID: 5778
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by nivintw** [comment] 2022-09-25 21:50
meant to include:
Sometimes after typing out a command (with no completions) the completions will show up while I am back-spacing.
E.g.:
1. `git clone ` -> no completions
2. `git cl` -> (while backspacing) -> completions show up

**Comment by nivintw** [comment] 2022-09-25 21:50
also adding context that same situation with `terminal` application

**Comment by nivintw** [comment] 2022-09-25 21:53
also: running `fig restart` does not resolve the issue; returns to state of "inserting text into the terminal will fail" / "figterm socket does not exist for session"

**Comment by DJTB** [comment] 2022-09-28 14:55
I have the same issue, where completions only show up while backspacing.
Has been happening for about a week, after a restart which Fig crashed on login, and had to go through setup wizard again.

```
fig-details:
  - desktop-version: Version 1.0.61 (B528) [Australian]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro16,1
  - chip-id:
  - cores: 8
  - mem: 32 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /usr/local/Cellar/fish/3.5.1/bin/fish
  - terminal: iterm
  - cwd: /Users/djtb/Projects/
  - exe-path: /Users/djtb/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - SHELL: /usr/local/bin/fish
    - TERM_SESSION_ID: w0t2p0:82491113-0FC9-41D9-AA7D-1411C305D014
    - FIG_PID: 14558
    - FIG_INTEGRATION_VERSION: 8
    - PATH: /Users/djtb/.gem/ruby/2.7.6/bin:/Users/djtb/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/bin:/Users/djtb/.rubies/ruby-2.7.6/bin:/usr/local/sbin:/Users/djtb/.yarn/bin:/Users/djtb/.fig/bin:/Users/djtb/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/djtb/.npm-packages/bin:/Users/djtb/.local/bin:/Users/djtb/fvm/default/bin:/Users/djtb/n/bin
    - FIG_TERM_VERSION: 5.2.0
    - FIG_TERM: 1
    - TERM: xterm-256color
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
  ```

**Comment by mschrage** [comment] 2022-09-28 17:44
It looks like both of you are `fish` users. We push a regression in the last production build that prevented use from accurately determining the color used by fish autosuggestions. This should be fixed on our beta channel and will be live in production soon.

If you want to try the beta, run `fig settings app.beta true`.

**Comment by DJTB** [comment] 2022-09-29 08:07
Switched to beta, restarted iterm2, and suggestions appear to be working fine 👍 

Oddly enough I'm seeing this for `fig doctor` though
```
✘ Daemon diagnostics: Daemon socket does not exist
Attempting to fix automatically...
Re-running check...

✘ Daemon diagnostics: Daemon socket does not exist


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
``` 

Not running into any issues using fig with the beta channel yet 🤷

**Comment by yahu1031** [comment] 2022-09-30 01:54
Similar logs as mentioned above.

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B535) [Beta] [Dev] [ABC – India]
hardware-info:
  - model: MacBook Air
  - model-id: MacBookAir10,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 8 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/mr.minnu
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/mr.minnu/.fig/bin:/Users/mr.minnu/.local/bin:/Users/mr.minnu/Development/flutter/bin:/Users/mr.minnu/Development/atsign/:/Users/mr.minnu/Development/atsign-helper/:/Users/mr.minnu/Development/android-sdk/cmdline-tools:/Users/mr.minnu/Development/android-sdk/platform-tools:/Users/mr.minnu/Development/android-sdk/tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: fbdd9058-f9ab-480e-8ef7-f0eb40458dd0
    - FIG_PID: 1536
    - FIG_PARENT: fbdd9058-f9ab-480e-8ef7-f0eb40458dd0
    - FIG_SET_PARENT: fbdd9058-f9ab-480e-8ef7-f0eb40458dd0
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by nivintw** [comment] 2022-09-30 07:10
as an update: opting in to beta and restarting everything a few times and running fig doctor eventually got it all working nicely.

My issue is resolved with the beta but since @yahu1031 isn't using fish I wasn't sure if I should close this one just yet. Will leave for maintainers to decide

**Comment by nivintw** [comment] 2022-09-30 07:13
hmmm... one other thing to not is that running fig doctor does fails sometimes even after updating...

```
fig doctor

✘ Daemon diagnostics: Daemon websocket error
  Failed to connect to websocket
Attempting to fix automatically...
Re-running check...

✘ Daemon diagnostics: Daemon websocket error
  Failed to connect to websocket


✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

I ran it again (because why not I guess?) and that time it did report that it was able to fix itself, but not confident that it stays fixed. E.g. opening a new terminal window and running fig doctor will report failure again

**Comment by vzoha** [comment] 2022-10-03 07:47
Hello, I have same problem on Ubuntu with fish. I have tried to enable beta and restart everything, but it does not help.

```yaml
fig-details:
  - cli-version: 1.5.0
  - desktop-version: 2.5.1
  - figterm-version: 5.2.0
hardware-info:
  - chip-id: Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
  - cores: 4
  - mem: 15923.004 GB
os-info:
  - kernel: 5.15.0-48-generic
  - distro: "Ubuntu 20.04.5 LTS"
  - distro-version: "20.04.5 LTS (Focal Fossa)"
environment:
  - shell: /usr/bin/fish
  - terminal: <unknown>
  - cwd: /home/vojta
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - GLFW_IM_MODULE: ibus
    - DISPLAY: :0
    - XDG_SESSION_TYPE: x11
    - XMODIFIERS: @im=ibus
    - TERM: xterm-256color
    - FIG_INTEGRATION_VERSION: 8
    - PATH: /home/vojta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vojta/.local/bin:/home/vojta/.fig/bin
    - SHELL: /usr/bin/fish
    - QT_IM_MODULE: ibus
    - FIG_PID: 4104
    - XDG_SESSION_DESKTOP: budgie-desktop
    - XDG_CURRENT_DESKTOP: Budgie:GNOME
    - TERM_SESSION_ID: db5968c5-0d81-4fc4-aece-3506e18eb52c
    - FIG_TERM_VERSION: 5.2.0
    - GTK_IM_MODULE: ibus
    - FIG_TERM: 1
```

**Closed** 2023-05-05 17:21 UTC
Labels: shell:fish, codebase:figterm
