### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by KevDCS** [withfig/fig#2040] opened 2022-11-13 14:52 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 10.15.7 (19H2026)

### Expected behaviour

Autocomplete in command line and being able to see the Fig dashboard

### Actual behaviour

I've restarted Fig and is still not syncing with the terminal, and the dashboard is just a white screen.
I already have the latest update, but is not working properly.

### Environment

```yaml
fig-details:
  - 2.7.8
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  - cores: 4
  - mem: 8.00 GB
os-info:
  - macOS 10.15.7 (19H2026)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/bash
```

**Comment by grant0417** [comment] 2022-11-13 22:26
Hey @KevDCS if you are available here is a link to schedule a debugging call: https://calendly.com/grant-fig/debugging

**Comment by grant0417** [comment] 2022-11-14 21:34
Going to close this as duplicate of #2028

The current version broke support for macOS versions below 11.3, a new version 2.7.9 will be out soon to fix this!

**Closed by grant0417** 2022-11-14 21:34 UTC
Labels: type:bug, NEED_TO_LABEL
