### ISSUE TITLE
WarpTerminal is not supported

### ISSUE THREAD

**Issue by adamlaz** [withfig/fig#1305] opened 2022-04-12 12:30 UTC
### Description:
> [WarpTerminal](https://www.warp.dev/) is currently not supported by fig. It'd be great if fig worked, since I'm missing it's functionality as I'm trying to make the switch from iTerm -> Warp. Warp is currently in early beta and Mac only. 

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.0 (20G165)|1.0.56|-zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: true
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/adam/dev/google-cloud-sdk/bin:/usr/local/opt/ruby/bin:/Users/adam/.nvm/versions/node/v14.19.0/bin:/Users/adam/.gem/ruby/2.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/adam/.local/bin:/Users/adam/.fig/bin:/Users/adam/.local/bin:/Users/adam/flutter/bin:/Users/adam/flutter/bin:/Users/adam/cook-cli
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB
## OS Info:
  - macOS 11.6.0 (20G165)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/adam/dev
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: ???
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - PATH=/Users/adam/dev/google-cloud-sdk/bin:/usr/local/opt/ruby/bin:/Users/adam/.nvm/versions/node/v14.19.0/bin:/Users/adam/.gem/ruby/2.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/adam/.local/bin:/Users/adam/.fig/bin:/Users/adam/.local/bin:/Users/adam/flutter/bin:/Users/adam/flutter/bin:/Users/adam/cook-cli
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by adamlaz** [comment] 2022-04-12 12:34
...I'm pretty sure it was actually working the other day, but as of right now, Fig does not seem to be supported in Warp.

![Screenshot on 2022-04-12 at 08 33 51 of  in Warp](https://user-images.githubusercontent.com/2012381/162963290-1fb2a3b0-81ae-4520-9eb2-2322f3588f75.png)

```
fig doctor

✘ Fig Integration: WarpTerminal is not supported

✘ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!
```

**Comment by mschrage** [comment] 2022-04-12 17:12
Hey @adamlaz! Warp is closed-source and not backwards compatible with the existing shell ecosystem. Building out a custom integration is not a priority for us right now, however we plan to expose an API so any terminal can add support for Fig. :)

I'm going to close this as a duplicate of #785

**Closed by mschrage** 2022-04-12 17:12 UTC
