### ISSUE TITLE
unable to see commands

### ISSUE THREAD

**Issue by imhamad** [withfig/fig#2415] opened 2023-03-21 14:24 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

 Unable to see list of commands

### Actual behaviour

Working perfectly, just spotted this issue

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/hamad/WebServer/indivior
  - exe-path: /opt/homebrew/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 222c5a12-efed-42c3-a9a5-c2da22465f57
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /Users/hamad/.cvm/cache/2.5.0:/opt/homebrew/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/Users/hamad/.nvm/versions/node/v17.4.0/bin:/opt/homebrew/bin:/Users/hamad/.platformsh/bin:/usr/local/opt/openldap/sbin:/usr/local/opt/openldap/bin:/usr/local/opt/libiconv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hamad/.fig/bin:/Users/hamad/.local/bin:/usr/local/bin

    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 29768
    - FIG_SET_PARENT: 222c5a12-efed-42c3-a9a5-c2da22465f57
```

**Comment by mschrage** [comment] 2023-05-01 22:52
Unclear what the issue is. Closing this for now.

**Closed by mschrage** 2023-05-01 22:52 UTC
Labels: type:bug, NEED_TO_LABEL
