### ISSUE TITLE
bug: The pop up window does not open

### ISSUE THREAD

**Issue by RomanPurishy** [withfig/fig#2889] opened 2024-01-26 06:01 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Sonoma 14.1

### Expected behaviour

When I type the command "cd" I want to see pop up suggestions.

### Actual behaviour

The pop up window does not open, but I see a flashing cursor beneath the typing

### Steps to reproduce

try to type cd

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.1.0 (23B74)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/roman.purishy
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 8b292f5f-8290-449d-8c98-49f3fcdccefb
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/roman.purishy/Library/pnpm:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/roman.purishy/.fig/bin:/Users/roman.purishy/.local/bin:/Users/roman.purishy/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 2396
    - FIG_SET_PARENT: 8b292f5f-8290-449d-8c98-49f3fcdccefb
```

**Comment by RomanPurishy** [comment] 2024-01-26 06:06
https://www.loom.com/share/82b1f7f53f28495993a22c5ec950af88?sid=964132f2-9cae-4c66-a6bc-e1466efefb97

**Comment by lucabattistini** [comment] 2024-01-26 15:18
same behaviour here

`fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/lbattistini/Projects
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: e564125f-559c-4d0b-b7dc-dc7016e8e19b
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/lbattistini/.nvm/versions/node/v18.17.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/lbattistini/development/flutter/bin:/Users/lbattistini/.fig/bin:/Users/lbattistini/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 14522
    - FIG_SET_PARENT: e564125f-559c-4d0b-b7dc-dc7016e8e19b`

**Comment by danielweck** [comment] 2024-01-27 14:37
Duplicate of https://github.com/withfig/fig/issues/2885

**Closed** 2024-01-29 18:40 UTC
Labels: NEED_TO_LABEL
