### ISSUE TITLE
Fig showing loading indicator instead of suggestions

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#870] opened 2022-02-01 02:23 UTC
This issue is very similar to this: https://github.com/withfig/fig/issues/779 however the cause is different so we have created a new issue!

https://user-images.githubusercontent.com/8764375/149586610-32dd56b6-5346-4230-9ac1-572a93b17abd.mov

**Comment by brendanfalk** [comment] 2022-02-04 18:47
If you are facing this issue, please comment a video with the output of the following:

1. Open two terminals side by side
2. In the left terminal, run `fig debug logs unix pty c_pty`
3. In the right terminal, type some example commands: e.g. `cd[space]`, `git push[space]`, `ls[space]`

**Comment by grant0417** [comment] 2022-03-11 19:04
Duplicate of #920

**Closed by grant0417** 2022-03-11 19:04 UTC
Labels: bug, codebase:_UNSURE_
