### ISSUE TITLE
Support for Zellij multiplexer

### ISSUE THREAD

**Issue by Integralist** [withfig/fig#1662] opened 2022-08-03 09:01 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

I'm using https://zellij.dev (a multiplexer, like tmux) with the Alacritty terminal, and I've found that fig autocomplete just doesn't work from within zellij. 

If I type `fig<space>` in Alacritty, then I'll see the autocomplete menu appear. If I execute the `zellij` command to drop inside the zellij multiplexer and I type `fig<space>` (or any other command I'd expect fig to work with) it does nothing.

But if I execute `fig doctor` from within the zellij multiplexer instance, it will tell me everything is good.

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.59 (B487) [Beta] [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /Users/integralist/.yarn/bin:/Users/integralist/.config/yarn/global/node_modules/.bin:/Users/integralist/Library/Caches/fnm_multishells/70374_1659516715551/bin:/Users/integralist/bin:/Users/integralist/.cargo/bin:/Users/integralist/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/integralist/.yarn/bin:/Users/integralist/.config/yarn/global/node_modules/.bin:/Users/integralist/Library/Caches/fnm_multishells/69886_1659516702081/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/integralist/.fig/bin:/Users/integralist/.local/bin:/opt/homebrew/opt/fzf/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /opt/homebrew/bin/bash
  - Current Directory: /Users/integralist/Code/shell/dotfiles
  - CLI Installed: true
  - Executable Location: /Users/integralist/.fig/bin/fig
  - Current Window ID: 8254/% (io.alacritty)
  - Active Process: zsh (69814) - /dev/ttys025
  - Terminal: <unknown>
  - Environment Variables:
    - PATH=/Users/integralist/.yarn/bin:/Users/integralist/.config/yarn/global/node_modules/.bin:/Users/integralist/Library/Caches/fnm_multishells/72673_1659517193597/bin:/Users/integralist/bin:/Users/integralist/.cargo/bin:/Users/integralist/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/integralist/.yarn/bin:/Users/integralist/.config/yarn/global/node_modules/.bin:/Users/integralist/Library/Caches/fnm_multishells/69886_1659516702081/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/integralist/.fig/bin:/Users/integralist/.local/bin:/opt/homebrew/opt/fzf/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=DEDEB765-3B99-4524-B16A-072949A54663
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.2
    - FIG_PID=72575
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: true
```
```

**Comment by Integralist** [comment] 2022-08-03 09:03
FYI your diagnostic output suggests my shell is Bash when it's Zsh.

```
$ echo $SHELL
/opt/homebrew/bin/zsh
```

**Comment by SeparateRecords** [comment] 2022-08-03 09:39
Definitely agree! Early support for zellij would be great 🙂

---

As an aside...

The "User Shell" line is from the directory service, specifically `dscl . -read /Users/$(id -un) UserShell`, which returns the current login-shell. Changing that requires editing `/etc/shells` and running `chsh -s $(which zsh)`.

AFAIK the $SHELL variable is actually set by the terminal on launch, which is why it reports zsh. Can set the terminal to launch any program and it'll happily oblige:
<img width="248" alt="Screen Shot 2022-08-03 at 7 36 37 pm" src="https://user-images.githubusercontent.com/52195359/182576539-0ec84028-c369-496f-83a1-af269f5c5ec9.png">


The most reliable way to get the _actual_ running shell instance is a hidden command in Fig! `fig _ get-shell` always returns the real path of the current shell.

**Comment by SeparateRecords** [comment] 2022-08-03 10:59
Was just putting this into our weekly support meeting notes and saw that (surprisingly) there's already an issue for zellij! Will close in favor of that just to keep the number down 😄

(still getting mentioned in the meeting of course!)

Duplicate of #1004

**Closed by SeparateRecords** 2022-08-03 10:59 UTC
Labels: type:integration-request

**Comment by Integralist** [comment] 2022-08-03 14:33
Ah I see that was opened in a different repo, that's why I didn't find it in these issues. Thanks for the update 👍
