### ISSUE TITLE
No Fig in embedded terminal of IntelliJ

### ISSUE THREAD

**Issue by abseralvo** [withfig/fig#986] opened 2022-02-23 09:45 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B383) [ABC] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/abs/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/abs/dev/ir/ir-q-messaging
Current window identifier: ???
Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/abs/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=0c2bfa27-06be-4e3a-bee8-5f5dc48a6a69
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM_VERSION=4.0.10
  - FIG_TERM=1
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 8
  - Memory: 64 GB</pre>
</p>
</details>

**Comment by fedeci** [comment] 2022-02-23 14:24
Duduplicate of #49

**Closed** 2022-02-23 14:24 UTC
