### ISSUE TITLE
Fig window theme to inherit from terminal colorscheme

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#379] opened 2021-08-20 05:41 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
My preferred theme isn't supported by Fig and I already have it as my colorscheme in the terminal. Fig should generate it's theme from my terminal color scheme.

**Comment by mschrage** [comment] 2021-09-01 05:06
Duplicate of #412

**Comment by brendanfalk** [comment] 2022-02-18 18:36
This is likely going to be be quite hard unfortunately :/

**Comment by mschrage** [comment] 2022-09-14 18:18
Closing as out of scope.

**Closed by mschrage** 2022-09-14 18:18 UTC
Labels: type:feature-request, codebase:themes
