### ISSUE TITLE
Fig eats "cmd + i"

### ISSUE THREAD

**Issue by fwesss** [withfig/fig#447] opened 2021-09-09 19:59 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue

### Description:

I use `cmd`+`i` to rename terminal windows in iTerm. With Fig running, `cmd`+`i` does not work. Fig uses this keybinding to popout the description but it should not eat this keybinding when the window is inactive.

### Environment

```bash
N/A
```

**Comment by mschrage** [comment] 2021-09-09 22:02
I think this is the intended behavior (cc: @brendanfalk) but totally see how it could be annoying.

We definitely should have an option to only intercept cmd+i when the Fig window is active. And maybe, we should reconsider the default?

**Comment by fwesss** [comment] 2021-09-10 16:04
This also interferes with `cmd`+`shift`+`i` which is used to send input to all panes in iTerm.

**Comment by mschrage** [comment] 2021-09-10 23:12
The `cmd+shift+i` intercept is fixed with the next version (v1.0.49)

I've also added a setting to the next buil allowing you to turn off `cmd+i` interception when the Fig window is not visible. 

Run this command to `autocomplete.alwaysInterceptCommandI false` cc @tiyberious-sailthru

**Closed** 2021-09-10 23:12 UTC
Labels: bug, repo:macOS
