### ISSUE TITLE
Unable to get diagnostics

### ISSUE THREAD

**Issue by btmurrell** [withfig/fig#830] opened 2022-01-27 01:17 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I ran `fig doctor` and it said "Unable to get diagnostics", so I ran `fig restart` and ran `fig doctor` again, and got the same error.  I just installed fig, and kicking the tires.  I am using Hyper v3.1.5.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7 19H1419|1.0.55|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>
It looks like Fig is not running.
Try running: fig restart

</pre>
</p>
</details>

```
fig diagnostic
Fig Version: Version 1.0.55 (B365) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/brianmurrell/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: hyper.js must include `fig-hyper-integration` in localPlugins.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/Cellar/python/2.7.8_2/bin:/usr/local/opt/openssl/bin:/Users/brianmurrell/bin:/bin:/Users/brianmurrell/.local/bin::/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/GE/bin:/Users/brianmurrell/.fig/bin:/usr/local/go/bin:/Users/brianmurrell/go/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Python/2.7/site-packages:/Users/brianmurrell/n/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (48490) - /dev/ttys027
Current working directory: /Users/brianmurrell
Current window identifier: 111299/% (co.zeit.hyper)
Path: /usr/local/Cellar/python/2.7.8_2/bin:/usr/local/opt/openssl/bin:/Users/brianmurrell/bin:/bin:/Users/brianmurrell/.local/bin::/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/GE/bin:/Users/brianmurrell/.fig/bin:/usr/local/go/bin:/Users/brianmurrell/go/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Python/2.7/site-packages:/Users/brianmurrell/n/bin
Fig environment variables:
  - TERM_SESSION_ID=D8FEDDF1-47DD-498F-B3AC-F4EDE9DFF2EE
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 10.15.7 19H1419
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 8
  - Memory: 32 GB
```

**Comment by mschrage** [comment] 2022-01-27 01:23
@btmurrell is autocomplete working besides these `fig doctor` errors?

**Comment by btmurrell** [comment] 2022-01-27 18:44
yes, afaik, everything is working fine (but i'm a noob)... y'all make it so easy to log an issue (👏 ), i just wanted to let you know. 😉  you can handle this one any way you see fit.

**Comment by mschrage** [comment] 2022-01-28 00:06
>  y'all make it so easy to log an issue (👏 ), i just wanted to let you know.

This is exactly what we want :)

The problem is we just pushed a few changes to `fig doctor` so it actually may be less reliable the the app itself haha

**Comment by grant0417** [comment] 2022-08-31 18:48
This seems like it should be fixed!

**Closed by grant0417** 2022-08-31 18:48 UTC
Labels: type:bug, codebase:cli
