### ISSUE TITLE
style: contrast issue on fig.io website

### ISSUE THREAD

**Issue by kr-anurag** [withfig/fig#842] opened 2022-01-28 05:45 UTC
### Discussed in https://github.com/withfig/fig/discussions/838

<div type='discussions-op-text'>

<sup>Originally posted by **kr-anurag** January 27, 2022</sup>
so I noticed that the input field for email at fig.io's landing page has a contrast issue.

![image](https://user-images.githubusercontent.com/77309809/151413551-0e76d53e-3017-4957-9e60-1cb42eb49bd9.png)

⬆️ as you can see, the colors don't match well</div>

**Comment by mschrage** [comment] 2022-01-28 20:20
Closing as duplicate of #841.

**Closed by mschrage** 2022-01-28 20:20 UTC
