### ISSUE TITLE
bug: dashboard blank, fig autocomplete not working

### ISSUE THREAD

**Issue by adamgreenhall** [withfig/fig#2042] opened 2022-11-13 19:16 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
  - similar to https://github.com/withfig/fig/issues/1982, but sounds like the problem there was supposed to be fixed in newer versions
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 10.15.7 (19H1824)

### Expected behaviour

* fig autocomplete works
* fig dashboard is not blank

### Actual behaviour

dashboard:
![Screen Shot 2022-11-13 at 11 12 12 AM](https://user-images.githubusercontent.com/704919/201539796-ff49509f-f858-47c8-acaf-7edd5e90216c.png)

dashboard devtools:
![Screen Shot 2022-11-13 at 11 12 30 AM](https://user-images.githubusercontent.com/704919/201539795-e6824018-eb8c-422b-89af-18da027d6ea4.png)

### Steps to reproduce

* Fig has been working for me for several months - this is new - not sure what changed
* open dashboard
* confirmed I'm connected to the internet (pretty normal setup, no strange VPN issues)
* I also tried re-installing fig, via homebrew and download. No luck.

### Environment

```yaml
fig-details:
  - 2.7.8
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 10.15.7 (19H1824)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.VK9UTVtU2N/org.macosforge.xquartz:0
    - FIGTERM_SESSION_ID: 52e64cee-ca3d-4bdf-86e0-b14cdffed5f6
    - FIG_HOSTNAME: adam.local
    - FIG_TERM: 2.7.8
    - PATH: /Users/adam/.rbenv/shims:/Users/adam/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/adam/.fig/bin:/Users/adam/.local/bin:/Users/adam/go/bin:/Users/adam/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 68992
    - FIG_PARENT: 52e64cee-ca3d-4bdf-86e0-b14cdffed5f6
    - FIG_SET_PARENT: 52e64cee-ca3d-4bdf-86e0-b14cdffed5f6
```

**Comment by grant0417** [comment] 2022-11-13 22:25
Hey @adamgreenhall, if you have time here is a link to schedule a debugging call: https://calendly.com/grant-fig/debugging

**Comment by zjfresh** [comment] 2022-11-14 02:35
Also dashboard blank and no fig's tip dialog, but has autocomplete.

MacOS 10.15.7, Intel Core i7. 

When i start up my mac, finding no fig's tip dialog, and then I run fig. It start with auto update.

After update, the dashboard is blank, and still no tip dialog

**Comment by grant0417** [comment] 2022-11-14 21:34
Going to close this as duplicate of #2028

The current version broke support for macOS versions below 11.3, a new version 2.7.9 will be out soon to fix this!

**Closed by grant0417** 2022-11-14 21:34 UTC
Labels: type:bug, NEED_TO_LABEL

**Comment by adamgreenhall** [comment] 2022-11-30 21:52
@grant0417 did this bug get reintroduced in `v2.8.0`? Seeing the same problem today (it had been working since the update to `v2.7.9`)
