### ISSUE TITLE
fig not linked to the terminal session

### ISSUE THREAD

**Issue by Ozandkr** [withfig/fig#1358] opened 2022-04-23 01:58 UTC
### Description:

hello ! i'm here to get help, because my fig autocomplete would not work. when i try to find out what's going on with the fig doctor, it just says to me that there is no issue with the terminal...

<img width="544" alt="Capture d’écran 2022-04-23 à 03 49 56" src="https://user-images.githubusercontent.com/74986465/164861955-c9dd4752-8da0-47d5-acd3-b93541da6e54.png">

<img width="409" alt="Capture d’écran 2022-04-23 à 03 52 45" src="https://user-images.githubusercontent.com/74986465/164862040-56038d84-8847-4998-bdc4-a9ab83f50d79.png">

so i dont know how to deal with this problematic issue, i tried to restart it multiple times but it does not work.

<img width="830" alt="Capture d’écran 2022-04-23 à 03 55 39" src="https://user-images.githubusercontent.com/74986465/164862535-9b3b8b81-61bb-454e-9525-9aebc84a2d26.png">

mind if i ask for help ? it would be very kind of you !
### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.57|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [French – Numerical]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ozanvarol/.fig/bin:/Users/ozanvarol/.local/bin:/usr/local/mysql/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir8,2
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/ozanvarol
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 22506/% (com.apple.Terminal)
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=A7CC6B40-AC96-4C0E-A854-94EE08CF9AE3
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ozanvarol/.fig/bin:/Users/ozanvarol/.local/bin:/usr/local/mysql/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by thmuch** [comment] 2022-04-23 10:09
Same here. Fig just stopped working this morning in macOS 12.3.1 Terminal. Same fig version as @Ozandkr, and "fig doctor" does not report a problem either.

What I did notice:
- brew upgraded my node to 18.0.0 this morning. Reverted to node 16 and node 12, fig is still not linked to the Terminal session.
- I think I saw a "auto-update fig" message in my bash(figterm) this morning, so maybe this is caused by a new fig version?

**Comment by thmuch** [comment] 2022-04-23 15:03
Used the workaround mentioned in #1333, now my bash/Terminal is linked again and fig is working again: In my `.bash_*profile*`, I changed the pre and post scripts to `bash*rc*.(pre|post).bash`

**Comment by mschrage** [comment] 2022-04-23 17:49
Hmm not sure what’s happened here. cc @grant0417 

A better fix is to revert your manual changes, run `touch ~/.bashrc` and then run `fig doctor`.

This should resolve the issue, but we’ll investigate the regression for users without a bashrc.

**Comment by thmuch** [comment] 2022-04-24 08:47
`.bashrc` had been created by fig before (with only the calls to  the bashrc pre/post scripts in it).

Reverting my changes, `touch`ing .bashrc and running `fig doctor` did unfortunately not resolve the issue.

For the time being, I'll have to keep the calls to the bashrc pre/post scripts in my `.bash_profile`.

Maybe `.bashrc` was created by 1.0.57? At least the timestamp (before `touch`ing it) showed yesterday, the probable time when my fig installation was updated.

**Comment by mschrage** [comment] 2022-04-24 15:32
cc @grant0417

**Comment by grant0417** [comment] 2022-04-26 03:45
Hey @thmuch and @Ozandkr, this should be fixed on stable, run `fig update` to get the latest version.

**Closed by grant0417** 2022-04-26 03:45 UTC

**Comment by thmuch** [comment] 2022-04-26 06:30
In the settings I had to opt-out of "Beta", otherwise `fig update` would not find a new version. But now the update is installed (fig 1.3.1, 1.0.57, B440) and everything's working smoothly – even with my manual changes reverted.

Bug resolved. Thank you!
