### ISSUE TITLE
If I paste anything long, it gets truncated to 1015 characters.

### ISSUE THREAD

**Issue by peter-mxtoolbox** [withfig/fig#1720] opened 2022-08-24 13:48 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

 I uninstalled fig and the behavior went back to normal. After I re-installed fig, same bug appears where the pasted information is truncated down to 1015 characters. 

This is super annoying because I very routinely paste 1024 characters from AWS SSO to configure my credentials and I have to paste somewhere else and then copy the last 9 characters multiple times per day ;)

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.60 (B507) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/peterleblond/.fig/bin:/Users/peterleblond/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.5.1 (21G83)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/peterleblond
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 338/% (com.googlecode.iterm2)
  - Active Process: zsh (7519) - /dev/ttys004
  - Terminal: iterm
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=5.1.0
    - PATH=/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/peterleblond/.fig/bin:/Users/peterleblond/.local/bin
    - TERM=xterm-256color
    - TERM_SESSION_ID=w0t0p0:7A7224BD-50DF-4EFD-8C91-186E743DE652
    - FIG_PID=7519
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment] 2022-08-25 00:09
Hey @peter-mxtoolbox! Thanks for reporting this. We can reproduce and are working on a fix.

**Comment by SeparateRecords** [comment] 2022-08-25 00:17
Just want to add a workaround here too! You can use the `pbpaste` command to paste your clipboard:
```console
$ echo "Hello!" | pbcopy

$ pbpaste         # writes data to stdout by default
Hello!

$ pbpaste | cat   # pipe, for tools that want input via stdin
Hello!

$ echo $(pbpaste) # command subsitution, for a string argument
Hello!

$ cat <(pbpaste)  # process substitution, for tools that want to read a file
Hello!
```

**Comment by mschrage** [comment] 2022-08-30 02:56
This should be fixed on beta in the next hour. Just run `fig setting app.beta true` to update.

**Comment by grant0417** [comment] 2022-08-31 04:20
Closing as duplicate of #1673

**Closed by grant0417** 2022-08-31 04:20 UTC
Labels: type:bug, codebase:figterm
