### ISSUE TITLE
Git branch auto completion gets confused when several terminals are open

### ISSUE THREAD

**Issue by MichaelPereira** [withfig/fig#241] opened 2021-07-05 21:28 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Hi,

I found the following bug when working on different git repos in different iterm2 tabs at the same time. It looks like the git auto-completion gets confused and displays the active branch from the other repo. Any git commands (even creating and checking out branches) doesn't change the autocompleted default branch result.

https://user-images.githubusercontent.com/431374/124518553-4f54c100-ddac-11eb-9f47-602d213f9eeb.mov

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|10.15.7|Version 1.0.45 (B218)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.45 (B218) [U.S. International - PC]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/per5573/.fig/bin/fig
Accessibility: true
Number of specs: 131
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/per5573/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Users/per5573/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 443/A58BE900-1EC4-40C0-B20F-EE80E13F130C% (com.googlecode.iterm2)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Users/per5573/.fig/bin
FIG_INTEGRATION_VERSION: 3</pre>
</p>
</details>

**Comment by mattschrage** [comment] 2021-07-08 03:43
It looks like Fig has gotten confused and accidentally linked multiple terminal sessions. You can fix this by running `fig source`.

**Comment by mschrage** [comment] 2021-07-21 00:15
Just to follow up here @MichaelPereira! There was actually a regression in build v1.0.45 that created some issues when determining which terminal session was active.

Should be fixed as of v1.0.46 (the current version)!

**Closed by mschrage** 2021-07-21 00:15 UTC
Labels: bug
