### ISSUE TITLE
Warp terminal not supported

### ISSUE THREAD

**Issue by francbartoli** [withfig/fig#1996] opened 2022-11-05 14:16 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.1 (21G217)

### Expected behaviour

Fig supported in Warp

### Actual behaviour

fig doctor

✘ Fig Integration: WarpTerminal is not supported

### Environment

```yaml
fig-details:
  - 2.7.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  - cores: 6
  - mem: 32.00 GB
os-info:
  - macOS 12.6.1 (21G217)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/geobart/Downloads/caricamento_nic/AreeVerdi[9]
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /usr/local/anaconda3/bin:/usr/local/anaconda3/condabin:/usr/local/prince12/bin:/Users/geobart/.gem/ruby/2.7.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/openssl@1.1/bin:/Users/geobart/.cargo/bin:/usr/local/opt/sqlite/bin:/Applications/Development/editor/Visual Studio Code.app/Contents/Resources/app/bin:/Users/geobart/.krew/bin:/Users/geobart/.pyenv/shims:/Users/geobart/.pyenv/bin:/Users/geobart/.poetry/bin:/Users/geobart/.poetry/bin:/Users/geobart/.jenv/shims:/Users/geobart/.jenv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/geobart/.poetry/bin:/Users/geobart/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/geobart/.fig/bin:/Users/geobart/.local/bin:/Users/geobart/.go/bin:/usr/local/opt/go/libexec/bin
    - DISPLAY: /private/tmp/com.apple.launchd.mfSoQ4gXQo/org.macosforge.xquartz:0
    - FIG_PID: 1647
    - FIG_SET_PARENT:
```

**Comment by mschrage** [comment] 2022-11-05 17:22
Duplicate of #785

**Closed by mschrage** 2022-11-05 17:22 UTC
Labels: type:bug, NEED_TO_LABEL
