### ISSUE TITLE
Hyper Terminal

### ISSUE THREAD

**Issue by wiktormalyska** [withfig/fig#2225] opened 2023-01-16 07:57 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)
Add compatibility with Hyper terminal

**Comment by mschrage** [comment] 2023-05-02 19:29
Duplicate of #27

**Closed by mschrage** 2023-05-02 19:29 UTC
Labels: NEED_TO_LABEL
