### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by OkungbowaGodspower** [withfig/fig#2524] opened 2023-05-11 15:37 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 10.15.7 (19H2026)

### Expected behaviour

To autocomplete the texts or command

### Actual behaviour

It's not working 

### Steps to reproduce

yes

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 10.15.7 (19H2026)
environment:
  - shell: /bin/zsh
  - terminal: hyper
  - cwd: /Users/okungbowagodspower/Documents/alx-system_engineering-devops/0x01-shell_permissions
  - exe-path: /Users/okungbowagodspower/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: e0d0fa2f-40da-4059-95c5-4eb6e9b1ebb8
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/okungbowagodspower/.fig/bin:/Users/okungbowagodspower/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 775
    - FIG_SET_PARENT: e0d0fa2f-40da-4059-95c5-4eb6e9b1ebb8
```

**Comment by mschrage** [comment] 2023-05-11 17:36
Closing as duplicate of #2522

**Closed by mschrage** 2023-05-11 17:36 UTC
Labels: NEED_TO_LABEL
