### ISSUE TITLE
A < symbol is accidentally generated in the jetbrains ides

### ISSUE THREAD

**Issue by StringKe** [withfig/fig#2507] opened 2023-05-03 14:16 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.1 (22E261)

### Expected behaviour

No extra < symbols

### Actual behaviour

[Preview Video](https://share.cleanshot.com/fmT8lq3X)

An additional < symbol will appear in all jetbrains ide

### Steps to reproduce

.zshrc

```shell
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# 自动进入命令工具
eval "$(zoxide init zsh)"

export PATH="/Users/chen/Runtime:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

alias ls="ls --color"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# pnpm
export PNPM_HOME="/Users/chen/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

plugins

![CleanShot 2023-05-03 at 22 14 43@2x](https://user-images.githubusercontent.com/31089228/235942365-5c47d361-5875-416e-8f1b-e920dc424ca2.png)

All plugins do not set anything extra.

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: intellij-webstorm
  - cwd: /Users/chen/Project/Bussiness/avarile/next-scaling
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: ed7d6c7e-1666-48da-a602-f3367c42e1fd
    - FIG_JETBRAINS_SHELL_INTEGRATION: 1
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /Users/chen/.local/share/fig/plugins/git-open:/Users/chen/Library/pnpm:/Users/chen/.sdkman/candidates/maven/current/bin:/Users/chen/.sdkman/candidates/java/current/bin:/Users/chen/.sdkman/candidates/gradle/current/bin:/Users/chen/.nvm/versions/node/v18.16.0/bin:/Users/chen/Runtime:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/chen/.cargo/bin:/Users/chen/Project/Bussiness/avarile/next-scaling/node_modules/.bin:/Users/chen/.fig/bin:/Users/chen/.local/bin:/opt/homebrew/opt/fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.WebStorm
    - FIG_PID: 40245
    - FIG_SET_PARENT: ed7d6c7e-1666-48da-a602-f3367c42e1fd
```

**Comment by mschrage** [comment] 2023-05-03 19:29
Very strange. I'd recommend removing all of the community plugins and seeing if this resolves the issue.

**Comment by mschrage** [comment] 2023-05-04 23:04
I'm not sure what is going on here. I cannot reproduce locally. Can you see if this behavior is reproducible in a different terminal or shell?

**Comment by mochaslave** [comment] 2023-05-17 15:59
I have a similar issue. It will auto append weird char in my iTerm. After comparing settings with the default value I find out the root cause.

Resolved by set `"figterm.csi-u.enabled": false,` in `~/.fig/settings.json` file.

**Closed** 2023-05-18 23:08 UTC
Labels: awaiting user reply, terminal:Jetbrains
