### ISSUE TITLE
Support for WrapTerminal

### ISSUE THREAD

**Issue by Elter71** [withfig/fig#2508] opened 2023-05-04 06:07 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
https://www.warp.dev

**Comment by mschrage** [comment] 2023-05-04 22:34
Duplicate of #785

**Closed by mschrage** 2023-05-04 22:34 UTC
Labels: NEED_TO_LABEL
