### ISSUE TITLE
Can't past the command or text that has more than 1018 character

### ISSUE THREAD

**Issue by goldengrisha** [withfig/fig#1739] opened 2022-08-30 12:49 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

When I pass some random text or command into the terminal, Fig truncates it.

### Environment

```yaml
Mac OS
```

**Comment by grant0417** [comment] 2022-08-30 18:24
Hey @goldengrisha, this is a known bug on the stable version of Fig that is fixed on the beta and should be released to stable soon.

**Comment by goldengrisha** [comment] 2022-08-30 18:47
Hey, @grant0417 thank you for updating.

**Comment by mschrage** [comment] 2022-08-31 02:34
Hey @goldengrisha you can update to the beta now. Just run `fig settings app.beta true`!

**Comment by mschrage** [comment] 2022-08-31 02:34
Closing as duplicate of #1673

**Closed by mschrage** 2022-08-31 02:34 UTC
Labels: type:bug, codebase:figterm
