### ISSUE TITLE
Restart from Fig App menu only succeeds in restarting Fig if it started recently <60s ago.

### ISSUE THREAD

**Issue by bryanparadis** [withfig/fig#936] opened 2022-02-11 23:58 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [ ] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
If I restart Fig from the system tray menu it closes Fig but fails to start it again if it had been opened for more than a minute. 

vs

If I restart Fig from the system tray menu it closes Fig and starts Fig again if it had been opened for less than a minute.

Nothing in `fig debug logs` between the two times to point to anything happening.

### Environment

```bash
bparadis on Bryans-MacBook-Pro at /opt/dev/bin/.fig [master] > fig diagnostic
Fig Version: Version 1.0.55 (B365) [Canadian English]
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/bparadis/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path:
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: application is not present.
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installed via Brew: true
Installation Script: true
PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/bparadis/.nix-profile/bin:/opt/dev/bin/user:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bparadis/.fig/bin:/usr/local/sbin:/opt/homebrew/opt/fzf/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (13597) - /dev/ttys005
Current working directory: /opt/dev/bin/.fig
Current window identifier: 153/% (com.googlecode.iterm2)
Path: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/bparadis/.nix-profile/bin:/opt/dev/bin/user:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bparadis/.fig/bin:/usr/local/sbin:/opt/homebrew/opt/fzf/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t2p0:CDD60A32-CB44-4321-A048-82F7B143237C
  - FIG_INTEGRATION_VERSION=5
  - FIG_TERM=1
  - FIG_TERM_VERSION=3
  - FIG_ENV_VAR=1
  - FIG_CHECKED_PROMPTS=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,3
  - Chip: Apple M1 Pro
  - Cores: 8 (6 performance and 2 efficiency)
  - Memory: 16 GB
```

**Comment by SeparateRecords** [comment] 2022-02-14 01:19
Super weird, I can't reproduce this. Fig restarts perfectly for me. @grant0417 is this a known problem?

**Comment by mschrage** [comment] 2022-02-14 20:56
Restarting Fig can sometimes be a little flakey. I'll investigate to see if I can reproduce this behavior @bryanparadis.

**Comment by bryanparadis** [comment] 2022-03-23 21:46
I can't get it to reproduce right now either. It was very persistent before. Possibly has been patched out?

**Comment by mschrage** [comment] 2022-03-23 22:30
I will close this issue for the time being but please ping me if you start to experience this again.

**Closed by mschrage** 2022-03-23 22:30 UTC
Labels: bug, codebase:macOS
