### ISSUE TITLE
Configuration and Plugin changes in UI don't seem to take affect, nor get saved after closing UI.

### ISSUE THREAD

**Issue by cgraving** [withfig/fig#1489] opened 2022-05-25 12:53 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Open UI
go to Oh My Zsh
Change theme to "amuse"
Switch to other parts of UI and back to Oh My Zsh, shows amuse.
Close UI and Open, no longer shows amuse, back to default
fig source shows no change.

Tried this with other plugins as well and no configurations get saved.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [U.S.]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/cgraving/bin:/usr/local/sbin:/Users/cgraving/bin:/usr/local/sbin:/Users/cgraving/bin:/usr/local/sbin:/Users/cgraving/.sdkman/candidates/java/current/bin:/Users/cgraving/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/cgraving/.fig/bin:/Users/cgraving/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/cgraving
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 185/% (com.googlecode.iterm2)
  - Active Process: zsh (1425) - /dev/ttys002
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:9DCD55EF-1C23-4E25-A5ED-3C4B9CBD9678
    - PATH=/Users/cgraving/bin:/usr/local/sbin:/Users/cgraving/bin:/usr/local/sbin:/Users/cgraving/bin:/usr/local/sbin:/Users/cgraving/.sdkman/candidates/java/current/bin:/Users/cgraving/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/cgraving/.fig/bin:/Users/cgraving/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=1425
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment] 2022-05-26 08:24
Hi @cgraving! Super weird, I can reproduce this. @sullivan-sean @mschrage any idea what's going on?

**Comment by legallyblind** [comment] 2022-05-26 12:54
I'm having similar issues with plugins. Making changes in the configuration tab changes nothing and after closing the GUI it returns to the default settings.

**Comment by lgothard** [comment] 2022-05-27 14:21
I'm having the same issue as well.

**Comment by legallyblind** [comment] 2022-05-30 10:08
As a temporary solution I have manually modified the configuration file for my plugin. I have achieved it by:

1. Find your plugin folder (on my machine it was `~/.local/share/fig/plugins/`)
2. Enter the plugin folder which you wish to modify.
3. Find the configuration file inside. (`spaceship.zsh`)

Alternatively, if you can't find your plugin folder; look for it using this command(searches in the user dir.): `find ~ -name "*spaceship*" -print`
Replace the "spaceship" with the name of your plugin.

**Comment by SimonMacIntyre** [comment] 2022-06-01 20:41
Also having this issue. I just counted 3 other related new issues in the last 3 days that are also this same issue.

**Comment by srinivasft** [comment] 2022-06-05 02:00
I have raised an issue (#1511) for this but that looks like a duplicate of this. Closing my issue as this was created before.

**Comment by SeparateRecords** [comment] 2022-06-29 07:19
This should be fixed now. It works for me, can someone else confirm that it's working?

**Closed** 2022-06-29 07:24 UTC
Labels: bug, codebase:plugins

**Comment by JakeTompkins** [comment] 2022-10-04 17:37
I'm experiencing this issue still on fig 1.5.0 and MacOs. Specifically, the Oh My Zsh theme refuses to be updated from the Fig configuration UI, and likewise with Enhancd. I had to go into the Enhancd.sh file and manually give it a value for the custom filter command

**Comment by maclavgg** [comment] 2022-11-18 09:34
what is the solution?

**Comment by kitsunde** [comment] 2023-04-25 06:37
This appears to still be an issue on macOS the workaround for Oh My Zsh is to disable it with a theme you don't want, then re-enable it and switch to the theme you want.

**Comment by OceanTrader1** [comment] 2023-06-04 18:33
I'm experiencing a similar issue but the workaround of enabling/disabling does not appear to work reliably. Sometimes, the theme change will be applied but, most often, it is not.

<details><summary><code>fig diagnostic</code></summary>
<p>

fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2 Max
  - cores: 12
  - mem: 32.00 GB
os-info:
  - macOS 13.4.0 (22F66)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/ocean_trader/.local/share/fig/plugins
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 2b02406a-283c-4274-be21-adcbca080eb6
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.16.0
    - PATH: /opt/homebrew/Caskroom/miniconda/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/ocean_trader/.fig/bin:/Users/ocean_trader/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 1102
    - FIG_SET_PARENT: 2b02406a-283c-4274-be21-adcbca080eb6

</p>
</details> 

<details>

<summary><code>~/.zshrc</code></summary>

```shell
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# PROMPT='%~ %% '

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
```

</details>

<details><summary>Install Plugin</summary>
<br></br>
<p>
After installing, I expect the default robbyrussell theme to load but after running <code>fig source</code> the prompt stays the same.
<img src="https://github.com/withfig/fig/assets/69881238/69121343-6822-47e9-b083-305d7933ddc8" alt="Install Oh My Zsh Plugin">
</p>
</details> 

<details>
<summary>Changing themes in GUI does not properly reflect in terminal</summary>
<br></br>
After changing the theme, I expect for the new theme to load in the terminal after running `fig source` but is not always the case.

![fig_change_themes_not_working](https://github.com/withfig/fig/assets/69881238/0d5a0eed-4308-4a18-b3eb-7c7673372ca8)

</details>

<details>
<summary>Disabling and re-enabling plugin does not guarantee a theme change</summary>
<br></br>
After disabling and then enabling the plugin (e.g., the proposed workaround), the proposed fix does not guarantee a theme change.

![fig_change_theme_after_reenable](https://github.com/withfig/fig/assets/69881238/cec846f7-211b-44fa-ae31-b579cdd95716)

</details>
