### ISSUE TITLE
Enter "cd" without prompt

### ISSUE THREAD

**Issue by ygnh-leo** [withfig/fig#1184] opened 2022-03-25 07:52 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B416) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/leo/.nvm/versions/node/v16.13.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/leo/.cargo/bin:/Users/leo/.local/bin:/Users/leo/.fig/bin:/Users/leo/.local/bin:/Users/leo/.local/bin:/Users/leo/.local/bin:/Users/leo/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,1
  - Chip: 
  - Cores: 6
  - Memory: 16 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/leo
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 1159/% (com.googlecode.iterm2)
  - Active Process: zsh (16278) - /dev/ttys008
  - Environment Variables:
    - TERM_SESSION_ID=w0t1p0:FF3BD39E-BF5A-4CD0-8BB3-8E17C7313438
    - PATH=/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/leo/.nvm/versions/node/v16.13.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/leo/.cargo/bin:/Users/leo/.local/bin:/Users/leo/.fig/bin:/Users/leo/.local/bin:/Users/leo/.local/bin:/Users/leo/.local/bin:/Users/leo/.local/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: installed!
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by ygnh-leo** [comment] 2022-03-25 07:59
I used Starship. [Starship](https://starship.rs)
FIG works with Starship turned off.

**Comment by ygnh-leo** [comment] 2022-03-25 08:22
Rule out errors again.
Because I added some emoji to iterm, I can delete it.

**Comment by grant0417** [comment] 2022-03-25 17:31
This can happen when `cd` is aliased by another command.

**Comment by mschrage** [comment] 2022-03-25 18:05
I am closing as a duplicate of #1178, let me know if this isn't the same issue @ygnh-leo.

**Closed by mschrage** 2022-03-25 18:05 UTC
