### ISSUE TITLE
Works in terminal but not in VSCode terminal

### ISSUE THREAD

**Issue by lextir** [withfig/fig#1293] opened 2022-04-10 22:05 UTC
### Description:

Fig works like it should in Terminal (Mac), but it doesn't work in the VSCode integrated terminal.

I have "editor.accessibilitySupport" set to off.
In the Fig preferences, VScode is not disabled.

Thank you.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 11.6.5 (20G527)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [Dutch]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexti/.local/bin:/Users/alexti/.fig/bin:/Users/alexti/.local/bin:/Users/alexti/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir6,2
  - Chip: 
  - Cores: 2
  - Memory: 8 GB
## OS Info:
  - macOS 11.6.5 (20G527)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/alexti
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 12852/% (com.apple.Terminal)
  - Active Process: zsh (15979) - /dev/ttys001
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=86C074E3-1520-433B-AFA2-77E98603AB34
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexti/.local/bin:/Users/alexti/.fig/bin:/Users/alexti/.local/bin:/Users/alexti/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment] 2022-04-11 18:37
Hey @lextir! Thanks for reporting. Can you share the version of VSCode that you are using?

**Comment by lextir** [comment] 2022-04-12 16:23
Version: 1.66.1 (Universal)

**Comment by mschrage** [comment] 2022-04-12 17:09
Can you run `fig doctor --verbose` in the VSCode terminal?

**Comment by lextir** [comment] 2022-04-12 17:53
Yes, I get this in the VS code terminal:

```
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ .bashrc contains valid fig hooks
✔ .profile contains valid fig hooks
✔ .zshrc contains valid fig hooks
✔ .zprofile contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin and ~/.fig/bin
✔ Fig Integration
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...
✔ VSCode integration is enabled


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!

```

**Comment by mschrage** [comment] 2022-04-12 19:38
Is VSCode full-screen? If so, this might be related to #1229

**Comment by lextir** [comment] 2022-04-12 19:43
Ah indeed, this is the same issue. It only doesn't work in full-screen. With the default terminal app the same happens.

**Comment by mschrage** [comment] 2022-04-12 20:16
Thanks for reporting @lextir! I am actively working on this. A fix should go out in the next release.

I'm going to close this as a duplicate of https://github.com/withfig/fig/issues/1229.

**Closed by mschrage** 2022-04-12 20:16 UTC
Labels: type:bug, terminal:VSCode, codebase:_UNSURE_, awaiting user reply
