### ISSUE TITLE
[Error] Bad SSH Config

### ISSUE THREAD

**Issue by mikebronner** [withfig/fig#1941] opened 2022-10-24 13:43 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS Ventora 13.0

### Expected behaviour

Be able to connect to my Remote SSH (VSCode plugin) machine as normal.

### Actual behaviour

```
OpenSSH_9.0p1, LibreSSL 3.3.6
vdollar_percent_expand: env var ${TERM_SESSION_ID} has no value
/Users/mike/.fig/ssh line 2: Bad forwarding specification.
/Users/mike/.fig/ssh: terminating, 1 bad configuration options
local-server-5> ssh child died, shutting down
```

This started happening this morning, but did not happen yesterday.
The following is the referenced ssh config file:

```
Match user="!git,!aur,*"
  RemoteForward /var/tmp/fig-parent-${TERM_SESSION_ID}.socket /var/tmp/fig/${USER}/secure$
  SendEnv LC_FIG_SET_PARENT FIG_SET_PARENT
  StreamLocalBindMask 600
  StreamLocalBindUnlink yes
  LocalCommand /home/mia/Fig/desktop/target/debug/fig_cli _ prompt-ssh '%r@%n' 1>&2
```

As a temporary workaround I was able to bypass the issue by renaming `~/mike/.gif/ssh` to `~/mike/.gif/old-ssh` and then reconnecting VSCode to my remote server.
### Steps to reproduce

Unsure, it happens all the time since this morning.

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B542) [U.S.]
hardware-info:
  - model: Mac Studio
  - model-id: Mac13,2
  - chip-id: Apple M1 Ultra
  - cores: 20 (16 performance and 4 efficiency)
  - mem: 64 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/mike/Developer
  - exe-path: /Users/mike/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_PID: 91201
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 2.5.3
    - PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/mike/.fig/bin:/Users/mike/.local/bin:/Users/mike/.composer/vendor/bin:/Users/mike/.composer/vendor/bin:/Users/mike/.composer/vendor/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 3c79ede7-6edf-4821-940a-54341ec2b7a1
    - FIG_PARENT: 3c79ede7-6edf-4821-940a-54341ec2b7a1
    - FIG_SET_PARENT: 3c79ede7-6edf-4821-940a-54341ec2b7a1
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment] 2022-10-24 16:54
Yikes looks like some debug config got pushed to prod. We’ll get the fixed asap.

In the meantime, if you replace `TERM_SESSION_ID` with `FIGTERM_SESSION_ID` everything should work.

**Comment by squili** [comment] 2022-10-24 17:01
@mschrage This should be fixed with the next release

**Comment by andriilive** [comment] 2022-11-03 23:44
>  if you replace `TERM_SESSION_ID` with `FIGTERM_SESSION_ID` everything should work.

Updated to `2.7.7` with `FIGTERM_SESSION_ID` fix. No effect. The **fig ssh integration continues to break ssh GitHub** connections to other apps. See the video: https://share.cleanshot.com/BkB25k

<img width="606" alt="CleanShot 2022-11-04 at 00 37 15@2x" src="https://user-images.githubusercontent.com/43708848/199854906-4a248216-ceda-467a-96f4-520892f4e25c.png">

**Comment by brendanfalk** [comment] 2022-11-05 00:49
Thanks for sharing this @andriilive 

1. Now rust macos is pushed, fixing all issues associated with SSH integration is now our number one priority
2. Weirdly, our SSH integration specifically accounts for git. We shouldn't be running our integration for anything that involves git. So I am actually shocked that it's not working. We will download GH desktop and reproduce and fix!


Your repro video is super helpful thank you very much!

**Comment by nadworny** [comment] 2022-11-13 21:22
is the only solution for the moment to uninstall the fig?

**Comment by grant0417** [comment] 2022-11-13 22:31
We have a work around in 2.7.8 that should prevent this from happening any more, please make sure you are on that version and let us know if you have any more issues!

**Closed** 2022-11-13 22:32 UTC
Labels: type:bug, integration:ssh, priority

**Comment by mikebronner** [comment] 2022-11-13 22:48
I have no longer had this problem since updating, thanks!

**Comment by nadworny** [comment] 2022-11-14 07:47
hi @grant0417 , I'm on 2.7.8 😢 

```
fig-details:
  - 2.7.8
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/BARTOSZ.NADWORNY
  - exe-path: /Users/BARTOSZ.NADWORNY/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 2bd4ea19-b189-4e40-b894-f731849ea061
    - FIG_HOSTNAME: NW3M6NCFYJ
    - FIG_TERM: 2.7.5
    - PATH: /Users/BARTOSZ.NADWORNY/.rd/bin:/Users/BARTOSZ.NADWORNY/.jbang/bin:/Users/BARTOSZ.NADWORNY/.pyenv/bin:/Users/BARTOSZ.NADWORNY/.nvm/versions/node/v16.15.0/bin:/Users/BARTOSZ.NADWORNY/.poetry/bin:/opt/homebrew/bin/terraform@0.13/bin:/opt/homebrew/anaconda3/bin:/opt/homebrew/anaconda3/condabin:/Users/BARTOSZ.NADWORNY/.jenv/shims:/Users/BARTOSZ.NADWORNY/.jenv/bin:/Users/BARTOSZ.NADWORNY/.poetry/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/BARTOSZ.NADWORNY/.fig/bin:/Users/BARTOSZ.NADWORNY/.local/bin:/opt/homebrew/opt/fzf/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 11690
    - FIG_PARENT: 2bd4ea19-b189-4e40-b894-f731849ea061
    - FIG_SET_PARENT: 2bd4ea19-b189-4e40-b894-f731849ea061
```

**Comment by grant0417** [comment] 2022-11-14 09:08
@nadworny can you share the error you are getting?

**Comment by nadworny** [comment] 2022-11-14 10:06
It works now 😱 
It was the same error as in the first post. Maybe a restart helped 😉
