### ISSUE TITLE
Autcomplete only works for folders, not files

### ISSUE THREAD

**Issue by b-per** [withfig/fig#2420] opened 2023-03-23 09:43 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

Typing `cat ` (or any other command applying to files) should provide me the list of directories to drill through as well as files available.

(I have searched the issues but I couldn't find the same problem, there are just too many of them)

### Actual behaviour

Typing `cat ` suggests directories and command flags but doesn't suggest files.

If I go out of fig with `esc`, the normal shell completion lists all my files correctly.

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/bper
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: d63e688b-8d2b-4525-87d9-1895f81719e3
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /Users/bper/.pyenv/shims:/Users/bper/.rbenv/shims:/Users/bper/miniconda3/bin:/Users/bper/miniconda3/condabin:/opt/homebrew/opt/openssl@1.1/bin:/Applications/SnowSQL.app/Contents/MacOS:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bper/.fig/bin:/Users/bper/.local/bin:/Users/bper/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/bper/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 31014
    - FIG_SET_PARENT: d63e688b-8d2b-4525-87d9-1895f81719e3
```

**Comment by mschrage** [comment] 2023-05-01 22:46
<img width="574" alt="Screenshot 2023-05-01 at 3 46 25 PM" src="https://user-images.githubusercontent.com/3155109/235544565-f6067aec-a2c4-487c-8979-07351bd06ae9.png">

Closing since I can't reproduce this behavior. Please provide more context and I will reopen it.

**Closed by mschrage** 2023-05-01 22:46 UTC
Labels: type:bug, NEED_TO_LABEL
