### ISSUE TITLE
Be more user friendly by making email optional and making telemetry an opt in feature rather than an opt out

### ISSUE THREAD

**Issue by gawlk** [withfig/fig#969] opened 2022-02-21 14:15 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:

Fig is an awesome tool which works great and is open source. Yet it follows that same dark patterns as many more money focused and evil products by forcing users to enter their email for a product that is supposed to be completely local and then collecting telemetry without notifying the user.

The feature should be making the email optional and making the telemetry an opt in rather than an opt out.

**Comment by mschrage** [comment] 2022-02-22 23:50
Hey @gawlk, thanks for your feedback. I'm closing this as a duplicate of #606.

> collecting telemetry without notifying the user.

<img width="702" alt="Screen Shot 2022-02-22 at 6 32 45 PM" src="https://user-images.githubusercontent.com/3155109/155237777-d698a2cb-37e3-40d7-9396-53545fa057ee.png">

When you install Fig, this message is part of the onboarding. We do our best to make it very clear to the user what information is collected. If you have any suggestions on how we can make this more clear, please let us know.

Also, in case you didn't know, you can completely opt out of telemetry by running `fig settings telemetry.disabled true`.

You can read our full (human-readable) privacy policy at [fig.io/privacy](https://fig.io.privacy) if you're interested in learning more.

**Closed by mschrage** 2022-02-22 23:50 UTC
Labels: NEED_TO_LABEL
