### ISSUE TITLE
Annoying dev window

### ISSUE THREAD

**Issue by Hugo-Pereira-98** [withfig/fig#1696] opened 2022-08-17 12:57 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

Developer mode enabled that can't be disabled is very annoying. Please help me

### Environment

```bash
### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.5.0 (21G72)|1.0.60|/bin/zsh|
fig diagnostic

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.60 (B507) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/hugo/.local/share/zinit/polaris/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hugo/.fig/bin:/Users/hugo/.local/bin:/Users/hugo/Library/Application Support/JetBrains/Toolbox/scripts
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: Mac mini
  - Model Identifier: Macmini9,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.5.0 (21G72)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/hugo
  - CLI Installed: true
  - Executable Location: /Users/hugo/.fig/bin/fig
  - Current Window ID: 351/% (com.googlecode.iterm2)
  - Active Process: zsh (86899) - /dev/ttys004
  - Terminal: iterm
  - Environment Variables:
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=5.1.0
    - PATH=/Users/hugo/.local/share/zinit/polaris/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hugo/.fig/bin:/Users/hugo/.local/bin:/Users/hugo/Library/Application Support/JetBrains/Toolbox/scripts
    - TERM=xterm-256color
    - TERM_SESSION_ID=w1t0p0:2ADCB313-022C-4E4D-AFEB-3A6DC15AB51D
    - FIG_PID=86899
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by bradenpowers** [comment] 2022-08-17 13:07
I am experiencing this issue as well.

**Comment by brunordgs** [comment] 2022-08-17 14:25
Same issue here, very annoying.

**Comment by jgtvares** [comment] 2022-08-17 14:53
Same here...

**Comment by cjhines** [comment] 2022-08-17 15:01
Duplicate of https://github.com/withfig/fig/issues/1695

**Closed** 2022-08-17 15:35 UTC
Labels: NEED_TO_LABEL

**Comment by yhoiseth** [comment] 2022-08-18 08:30
> Hey everyone! Fixed the bug now, run `fig restart` and it will go back to normal 🙂

Great, worked for me 🙏
