### ISSUE TITLE
Terminal crashes each time autocomplete attempts to start up

### ISSUE THREAD

**Issue by nathanpalmer** [withfig/fig#417] opened 2021-08-31 13:06 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

The terminal starts up and shows the welcome message that shows me how fig works. I type "cd" and then the terminal disappears. Even trying to take a screenshot will immediately close the session. Something really funky is going on here. 

<img width="827" alt="CleanShot 2021-08-31 at 09 03 36@2x" src="https://user-images.githubusercontent.com/125599/131507399-c0c42a01-f2b1-4a36-ab84-a3883fe17d22.png">

If I turn "Autocomplete" off, then it stops crashing. (Of course, then Fig doesn't really do much I assume.)
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.0|Version 1.0.47 (B257)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nathan/.fig/bin/fig
Accessibility: true
Number of specs: 190
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/nathan/.fig/user/keybindings
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/nathan/.asdf/shims:/usr/local/opt/asdf/bin:./bin:./node_modules/.bin:/Users/nathan/.bin:/usr/local/sbin:/Users/nathan/Source/Go/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/opt/postgresql@12/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Keybase.app/Contents/SharedSupport/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /usr/local/Cellar/fish/3.2.2_1/bin/fish (87461) - ttys004
Current working directory: /Users/nathan
Current window identifier: 32864/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment] 2021-08-31 17:38
Try running `rm "$HOME/.fig/bin/fish (figterm)"`. This should fix the issue.

**Comment by nathanpalmer** [comment] 2021-09-01 13:03
@mschrage That seemed to solve the issue. Thanks.

**Comment by nathanpalmer** [comment] 2021-09-01 13:04
@mschrage That seemed to solve the issue. Thanks.

**Comment by fwesss** [comment] 2021-09-02 21:40
Duplicate of https://github.com/withfig/fig/issues/330

**Closed by fwesss** 2021-09-02 21:40 UTC
Labels: bug, shell:fish
