### ISSUE TITLE
Unable to see process arguments in window title

### ISSUE THREAD

**Issue by SeparateRecords** [withfig/fig#1400] opened 2022-05-02 01:29 UTC
> I want to see the host of connection like it is without fig installed:
> ![image](https://user-images.githubusercontent.com/52195359/166174084-96adc80b-8336-4fcf-ae02-a971160b8b88.png)
> ssh production_host or ssh qa_host etc. not just ssh. And I checked the ‘Arguments’ box in tab’s preference but it didn’t help/

With fig installed, ssh arguments aren't shown:
![image](https://user-images.githubusercontent.com/52195359/166174101-1a0ba8a5-9234-457a-8985-49d6ac1b6849.png)

**Comment by mschrage** [comment] 2022-05-06 17:24
This is a limitation of how tab titles are determined by Terminal.app. Potentially, we can workaround this by allowing the user to specify the title format they prefer inside of Fig rather than at the terminal emulator level.

**Comment by mschrage** [comment] 2022-05-06 17:24
Closing as a duplicate of #1410

**Closed by mschrage** 2022-05-06 17:24 UTC
Labels: type:bug, terminal:macOS, codebase:_UNSURE_
