### ISSUE TITLE
Missing terminal cursor after installing Fig

### ISSUE THREAD

**Issue by huttli** [withfig/fig#562] opened 2021-11-02 04:08 UTC
### Description:
The cursor is missing after I installed Fig. I'd have to manually put the "tput cvvis" command on every new session I start now.

If I observe the closely, I'd see the cursor actually show up at the stage oh-my-zsh was initializing, and then disappeared after fig's initialization.

I have iTerm2/oh-my-zsh(04c96e235ff522704a6f1482e7fd06a05467cbb7) if these were not captured by the diagnostic.

I have checked the existing issues on this repo and oh-my-zsh's, there is no existing bugs reported related to this.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.6.1|Version 1.0.51 (B294)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.51 (B294) [Australian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/zli/.fig/bin/fig
Accessibility: true
Number of specs: 1
SSH Integration: false
Tmux Integration: false
Keybindings path: <none>
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: false
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment] 2021-11-02 18:09
Hey @huttli! Thanks so much for reporting this. Can you share your `zshrc` file as well as a screen recording of this behavior?

Definitely want to figure out what's going on!

**Comment by huttli** [comment] 2021-11-02 22:19
> Hey @huttli! Thanks so much for reporting this. Can you share your `zshrc` file as well as a screen recording of this behavior?
> 
> Definitely want to figure out what's going on!

Here is my `.zshrc` file content:
https://pastebin.com/PX2A2EP4

And the screen recording:

https://user-images.githubusercontent.com/9455555/139959599-6f002e74-0ffe-477b-af98-f299cf1b9a5d.mov

**Comment by HaleTom** [comment] 2022-01-17 06:14
Hi @huttli, I was unable to reproduce your issue:

When sourcing the equivalent of your `.zshrc` I see:

```
[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.fig/zdotdirs/562/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

The `osx` plugin is deprecated and has been renamed to `macos`.
Please update your .zshrc to use the `macos` plugin instead.
```

It seems that the `osx` plugin has been deprecated.  Perhaps this happened after you raised the issue?

If you're not seeing the above output when you start `zsh`, maybe you need to update your plugins and/or `oh-my-zsh`, or `set POWERLEVEL9K_INSTANT_PROMPT=verbose`.

### Working `.zshrc`

I removed a lot of the comments from the `.zshrc` hosted on pastebin, and did some minor changes:

* Allow everything to be contained within a [`$ZDOTDIR`](https://zsh.sourceforge.io/Doc/Release/Files.html) for siloed testing.
* Install Powerlevel 10K
* Install `zsh-iterm-touchbar`
* Rename plugin `osx` -> `macos`
* Ensure that `p10k-instant-prompt` is sourced after `oh-my-zsh.sh`

Here is the .zshrc that I came up with:

```
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####

# Get Powerlevel 10K
p10k_dir=${p10k_dir:=${ZDOTDIR:-$HOME}/.oh-my-zsh/custom/themes/powerlevel10k}
[[ ! -d $p10k_dir ]] && \
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $p10k_dir

# Get zsh-iterm-touchbar
zit_dir=${zit_dir:=${ZDOTDIR:-$HOME}/.oh-my-zsh/custom/plugins/zsh-iterm-touchbar}
[[ ! -d $p10k_dir ]] && \
  git clone --depth=1 https://github.com/iam4x/zsh-iterm-touchbar $zit_dir

# Path to your oh-my-zsh installation.
export ZSH="$ZDOTDIR/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
COMPLETION_WAITING_DOTS="true"

plugins=(
 brew
 docker
 docker-compose
 git
 git-escape-magic
 git-prompt
 gitfast
 git-extras
 kubectl
 node
 npm
 macos  # was osx
 sudo
 vundle
 vim-interaction
 vi-mode
 yarn
 zsh-iterm-touchbar
)

source $ZSH/oh-my-zsh.sh

POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
   echo "Sourcing ${X1XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f $ZDOTDIR/.p10k.zsh ]] || source ~/$ZDOTDIR/.p10k.zsh

# source ~/mytoolbox.rc
# ????? What is in here?

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
```

### Next actions


1. Does your cursor still disappear if you remove the line: `source ~/mytoolbox.rc`?

2. Does the issue still occur if you rename your `~/.p10k.zsh`?

It would greatly assist if you could provide a minimal `.zshrc` that demonstrates your issue:

* Remove all plugins that are not required to produce the issue
* Inline the minimal necessary lines from `mytoolbox.rc` into `.zshrc` itself
* Provide the minimum necessary lines of `~/.p10k.zsh` that still produce the issue

**Comment by huttli** [comment] 2022-01-26 22:20
I cannot reproduce with this version anymore either.
1.0.54 (B359)

I suppose it's fixed somewhere along the line. :D

**Comment by mschrage** [comment] 2022-01-26 22:26
Amazing! I'll close this issue now.

PS. it seems like you're still one version behind the latest. Try running `fig update`  to download the latest build.

**Closed by mschrage** 2022-01-26 22:26 UTC
Labels: bug, integration:zsh
