### ISSUE TITLE
[warning message] Fig needs to be update and may not work with future versions of macos warning message

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#880] opened 2022-02-02 00:17 UTC
![CleanShot 2022-02-01 at 16 13 44](https://user-images.githubusercontent.com/4949076/152072730-898a7b36-1a22-4326-be23-6fed0156b3a2.png)

!!! This warning message is just a warning. Fig still works totally fine. Just click OK then login. We are working on removing the message !!!

**Reproduce**
1. `brew uninstall fig`
2. `brew install fig`
3. cmd+space -> select Fig
4. Click "okay" when it says this is an app downloaded from the internet

People often see this message after updating their mac to monterey. It is scary and also makes people think Fig doesn't work at all so they just uninstall / don't continue with setup. 

It could be related to python2 code somewhere. It could be related to something else. Either way, we need to get rid of it!!

I don't have any of the legacy python code for iTerm2 anymore. 
![CleanShot 2022-02-01 at 16 17 03](https://user-images.githubusercontent.com/4949076/152072958-24ac764d-86de-4f89-9e33-349a3b5b85b0.png)

**Comment by fedeci** [comment] 2022-02-02 10:13
I can investigate this one to see if any deps is using old python.

**Comment by mschrage** [comment] 2022-02-02 18:50
Would be great if you can investigate this @fedeci, but I am pretty sure that we don't have any Python dependencies.

> The first time the `python` executable is from a process, this '"fig" needs to be updated' dialog is triggered.
>
> See [this article](https://macmule.com/2021/10/25/macos-monterey-prompt-needs-to-be-updated/) for more details.
> 
> What's tricky is since Fig runs a pseudoterminal, scripts and executables from your zshrc/bashrc can trigger this. I'm pretty sure that Fig does not actually have any first party dependencies that use Python.

Also I am going to close this as a duplicate of #551.

**Closed by mschrage** 2022-02-02 18:50 UTC
Labels: bug, codebase:_UNSURE_

**Comment by fedeci** [comment] 2022-02-06 11:24
Found this for 10.15 patch notes:
> ## Deprecations
> - Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. Future versions of macOS won’t include scripting language runtimes by default, and might require you to install additional packages. If your software depends on scripting languages, it’s recommended that you bundle the runtime within the app. (49764202)
> - Use of Python 2.7 isn’t recommended as this version is included in macOS for compatibility with legacy software. Future versions of macOS won’t include Python 2.7. Instead, it’s recommended that you run python3 from within Terminal. (51097165)
