### ISSUE TITLE
bug: Installing Fig :: The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.

### ISSUE THREAD

**Issue by aolin480** [withfig/fig#2778] opened 2023-10-17 17:16 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS Ventura - 13.5.2 (22G91)

### Expected behaviour

Running `curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL` should install fig headless correctly. Currently, my terminal is automatically spitting out `curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL` when sshing into one of my servers, and while a CLI command is busy running, `curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL` keeps getting spit out while the process is running 

### Actual behaviour

When running `curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL` I am getting the following error:

```
Installing repo dependencies
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

Installing Fig repository
bash: line 25: /etc/apt/sources.list.d/fig.list: No such file or directory
Installing Fig key
gpg: WARNING: unsafe ownership on homedir '/Users/aaronolin/.gnupg'
Updating apt
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

Installing Fig
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.
```
![fig](https://github.com/withfig/fig/assets/1616101/d3c8e3fd-9b94-43a0-b92b-8cc491ab67c2)

### Steps to reproduce

1. Run from terminal (iTerm2): `curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL`

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 13.5.2 (22G91)
environment:
  - shell: /usr/local/Cellar/zsh/5.9/bin/zsh
  - terminal: iterm
  - cwd: /Users/aaronolin
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.SxZ1ueCXWQ/org.macosforge.xquartz:0
    - FIGTERM_SESSION_ID: 5d12fe8c-5577-4cdb-894a-bb0d7ac92ec7
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/go/bin:/usr/local/opt/node@8/bin:/usr/local/Qt-5.9.7/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/opt/openssl/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/sphinx-doc/bin:/Users/aaronolin/mercurial-hooks:/Users/aaronolin/.nvm/versions/node/v8.16.0/bin/npm:/Users/aaronolin/.nvm/versions/node/v8.16.0/bin/node:/usr/local/opt/php@7.3/sbin:/usr/local/opt/php@7.3/bin:/Users/aaronolin/.yarn/bin:/Users/aaronolin/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/opt/llvm/bin:/Users/aaronolin/.nvm/versions/node/v13.14.0/bin:/Users/aaronolin/Volumes/localdev/www/dealerinspire-docker/bin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/go/bin:/usr/local/opt/node@8/bin:/usr/local/Qt-5.9.7/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/opt/openssl/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/sphinx-doc/bin:/Users/aaronolin/mercurial-hooks:/usr/local/opt/php@7.3/sbin:/usr/local/opt/php@7.3/bin:/Users/aaronolin/.yarn/bin:/Users/aaronolin/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/opt/llvm/bin:/Users/aaronolin/Volumes/localdev/www/dealerinspire-docker/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/aaronolin/.fig/bin:/Users/aaronolin/.local/bin:/Users/aaronolin/go/bin:~/go:/Users/aaronolin/go/bin:~/go:/Users/aaronolin/go/bin:~/go:/Users/aaronolin/go/bin:~/go
    - SHELL: /usr/local/bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 6007
    - FIG_SET_PARENT: 5d12fe8c-5577-4cdb-894a-bb0d7ac92ec7
```
```

**Comment by alphex** [comment] 2023-10-18 14:30
This is happening on OSX Sonoma as well. (14.0 (23A344))
I just upgraded this weekend, I'm assuming Sonoma removed java.

**Comment by mschrage** [comment] 2023-10-18 21:11
Hey @alphex @aolin480 - what is your goal when trying to install the headless version of Fig?

**Comment by alphex** [comment] 2023-10-18 21:49
> Hey @alphex @aolin480 - what is your goal when trying to install the headless version of Fig?

Honestly. I'm just following the error message. 

I just upgraded to osx Sonoma and started getting this error message with every terminal (I use iterm2) command that interacts with a remote host.  

git pull, for example.

**Comment by aolin480** [comment] 2023-10-18 21:57
@mschrage Yep, I am echoing Alphex too. It just started showing up in my command line and so I was just trying to run it, and yeah, when I SSH'd into my work server, it started to install fig headless on my companies server, until I hit CTRL+C, and I don't know how to get this to stop outputting the fig-headless install command:

Here's a screencast of me SSH'ing into a server and it just starts running

https://youtu.be/Fd1ygkHDuD8

**Comment by rmsy** [comment] 2023-10-25 01:34
Same for me as well. I'm on 13.5.2, and after every SSH command, Fig is trying to run `curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL` in my shell, which consistently 1) waits for password for sudo, and 2) fails with the following output:

```
➜  curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL
███████╗██╗ ██████╗
██╔════╝██║██╔════╝
█████╗  ██║██║  ███╗
██╔══╝  ██║██║   ██║
██║     ██║╚██████╔╝
╚═╝     ╚═╝ ╚═════╝.io
Performing compatibility checks
Executing https://repo.fig.io/scripts/apt/install.sh
Password:
Installing repo dependencies
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

Installing Fig repository
bash: line 25: /etc/apt/sources.list.d/fig.list: No such file or directory
Installing Fig key
gpg: WARNING: unsafe ownership on homedir '/Users/isaac/.gnupg'
Updating apt
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

Installing Fig
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

sh-3.2$ 
```

**Comment by kayode0x** [comment] 2023-10-25 02:28
same issue with @rmsy. so i had to add a script that blocks `curl -fSsL https://fig.io/install-headless.sh | bash; exec $SHELL` as a temporary fix.

also unable to completely uninstall fig.

**Comment by mschrage** [comment] 2023-10-26 20:02
We are investigating this. Seems potentially linked to macOS Sonoma.

**Comment by rmsy** [comment] 2023-10-26 20:05
(Just for the record, this started happening to me on Ventura — and I had not yet installed the recent security update for Ventura, either).

**Comment by kayode0x** [comment] 2023-10-26 20:10
my VPS runs on ubuntu :)

**Comment by M1chlCZ** [comment] 2023-11-06 17:15
Does anyone know how to remove it? Terminal is now unusable for me.

**Comment by kayode0x** [comment] 2023-11-06 23:19
> Does anyone know how to remove it? Terminal is now unusable for me.

https://fig.io/user-manual/other/uninstall#using-the-gui

**Comment by aolin480** [comment] 2023-11-10 22:25
Just an update. I removed Fig a couple of weeks ago, and will be looking at notifications for any updates or anything to this issue. I am also on macOS Ventura as well, and was still having this issue.

Thanks!

**Comment by rmsy** [comment] 2023-11-10 22:31
Yeah, this is at the point where I'm going to need to uninstall as well 😞 It basically ruins my shell every time I perform a git operation.

**Comment by aolin480** [comment] 2023-11-10 22:33
Actually, I thought maybe I would install it again and see if there's been any updates, but low and behold, when I tried to SSH into a server, this Fig setup popped up. I am wondering if I selected Always, and so whenever I SSH into a server, it was always just trying to install it? I selected `Never` and so hopefully that was it. I am not too sure where this setting is stored in the config, but if you can't find it, then the best bet would be to remove fig altogether, reinstall it, and then try to SSH into one of your servers and then just select `Never` and maybe that will fix it? ¯\_(ツ)_/¯ 

![iScreen Shoter - iTerm2 - 231110163056](https://github.com/withfig/fig/assets/1616101/8cfba9e8-c73a-4532-b4ba-b20bf6edd68f)

**Comment by rmsy** [comment] 2023-11-10 22:36
I just discovered that there is a duplicate of this issue that describes the same theory; it looks like the config can be found in `~/.fig/settings.json`: https://github.com/withfig/fig/issues/2792#issuecomment-1797980419

Thanks for sharing, I'll give that a try and see if it fixes it for me!

**Comment by adiazarya100** [comment] 2024-02-03 18:28
Any updates regarding this issue? 👀 👀

**Closed** 2024-02-06 19:14 UTC
Labels: integration:ssh
