### ISSUE TITLE
Resizing window creates additional lines in terminal

### ISSUE THREAD

**Issue by bgandrew1** [withfig/fig#1158] opened 2022-03-23 08:43 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Happens every time that I resize the window. Attaching screen recording

https://user-images.githubusercontent.com/9099060/159658272-c56a5052-9fb9-4460-a2d6-d8a976c3fa1c.mov

### Details:

|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B414)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B414) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/anmbradl/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by sullivan-sean** [comment] 2022-09-14 17:46
This seems to be fixed in the latest version (I'm unable to reproduce any difference in behavior on resize across `iTerm` and `Terminal` when Fig is installed vs uninstalled).

Closing for now, but if anyone is still encountering this issue feel free to comment and we can re-investigate.

**Closed by sullivan-sean** 2022-09-14 17:46 UTC
Labels: type:bug, codebase:figterm
