### ISSUE TITLE
Fig doesn't parse zsh aliases and zsh functions

### ISSUE THREAD

**Issue by objectivecosta** [withfig/fig#1060] opened 2022-03-09 12:17 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig doesn't fetch my aliases on zsh and neither does it fetch the zsh functions that I added to .zshrc.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B396)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B396) [Beta] [U.S. International – PC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/rafaelf/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment] 2022-03-09 20:04
Hey @objectivecosta - currently we don't support autocomplete for zsh functions. We should handle aliases however.

Can you share your .zshrc? (This may be due to a compatibility issue with powerlevel10k)

**Comment by SeparateRecords** [comment] 2022-03-11 19:30
Closing as duplicate of #1074, and parsing functions isn't really in scope for us - you might be interested in https://fig.io/docs to make your own completions! 🙂

Eventually we'd like to have an even easier method than that.

**Closed by SeparateRecords** 2022-03-11 19:30 UTC
Labels: awaiting user reply
