### ISSUE TITLE
fig doctor never reports anything or returns

### ISSUE THREAD

**Issue by sleifer** [withfig/fig#964] opened 2022-02-20 17:05 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

First time exploring Fig. Debugging in Fig menu thinks everything is good. running 'fig doctor' prints nothing and never returns. Can't kill with control-c.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B381)|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B381) [U.S.] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/simeon/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (29952) - /dev/ttys006
Current terminal session: w0t0p0:B887CFBA-F564-4DE8-BA09-23E4AB4A92EF
Current working directory: /Users/simeon
Current window identifier: 17090/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by sleifer** [comment] 2022-02-20 22:43
I did some searching of open issues and wonder if this is not related to zplug or secondarily powerlevel10k or zsh-z.

**Comment by SeparateRecords** [comment] 2022-02-21 02:42
I think this is a duplicate of #935 - this is an issue on the latest beta.

@grant0417 @mschrage  do we know the cause of the issue?

**Comment by grant0417** [comment] 2022-02-22 19:21
Hey @sleifer, sorry about the issue with `fig doctor`, a fix should be going out soon.

**Closed by grant0417** 2022-02-22 19:21 UTC

**Comment by sleifer** [comment] 2022-02-23 01:43
Thanks. Installed 1.0.55 (B383) and fig doctor is working.
