### ISSUE TITLE
bug: Failed setting previous_email: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by YousufSohail** [withfig/fig#1997] opened 2022-11-05 15:05 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

To be able to login

### Actual behaviour

Something went wrong :(
Error: Failed setting user_id: EOF while parsing a value at line 1 column 0

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by Wail-Mohammed** [comment] 2022-11-05 20:19
i have the same issue, even after running fig doctor,  it is giving the same error message : "Error: Failed setting user_id: EOF while parsing a value at line 1 column 0 " I wonder how to get it to work.

**Comment by ptg251294** [comment] 2022-11-06 19:01
Same issue on MacBook Pro Core i9 16GB.

**Comment by boogiedimik** [comment] 2022-11-06 19:33
same issue when trying to login

**Comment by ArAsHCoding** [comment] 2022-11-06 19:35
Exactly! I got the same error message when I tried to log in.

**Comment by beyazit** [comment] 2022-11-06 21:34
Same issue
MacBook Pro M2 16GB

**Comment by SeparateRecords** [comment] 2022-11-06 23:54
Hey all! I can't reproduce this at the moment, can you confirm if it's still breaking? If it is, could you grab a time on my calendar? https://calendly.com/robert-fig/support

**Comment by jcha0713** [comment] 2022-11-06 23:58
Yeah it's still not working for me. Tested on MacOS Monterey 12.3
<img width="559" alt="Screen Shot 2022-11-06 at 15 56 25" src="https://user-images.githubusercontent.com/29053796/200202610-acd6e11b-115e-4b48-bb2f-d039b96c9a48.png">

**Comment by ArAsHCoding** [comment] 2022-11-07 00:03
It's still not working on macOS 12.6.1 :(

**Comment by brendanfalk** [comment] 2022-11-07 00:32
Hi all. Thank you all for reporting. We are actively investigating. Bug appears to be related to our integration with AWS Cognito. We will hopefully have a fix within 24 hours.

In meantime, I suggest:
1. Run `fig login` - this should let you login from the CLI as opposed to the GUI
2. Run `fig restart`

Try these a few times and hopefully it should work.

**Comment by BlackMoonWolf** [comment] 2022-11-07 00:36
Same issue here. Ventura on a 16" MBP 16".

**Comment by BlackMoonWolf** [comment] 2022-11-07 00:40
> Hi all. Thank you all for reporting. We are actively investigating. Bug appears to be related to our integration with AWS Cognito. We will hopefully have a fix within 24 hours.
> 
> In meantime, I suggest:
> 
> 1. Run `fig login` - this should let you login from the CLI as opposed to the GUI
> 2. Run `fig restart`
> 
> Try these a few times and hopefully it should work.

This is my first time using Fig. Upon opening it fir the first time, I got a verification code, etc. I put it in but the app appeared to just freeze so I killed the process. Opening the app only starts the above problem in a circular manner.

I tried "fig login" and "fig restart" but fig only says:

`error: Already logged in as <_redacted_>@gmail.com, please logout first.`

I tried this repeatedly several times but nothing changes.

I'll wait a while and try again later.

**Comment by SeparateRecords** [comment] 2022-11-07 02:39
Hey all, just to restate, if you have a moment I'd love to hop in a debugging call so we can find out what's happening and fix this bug! https://calendly.com/robert-fig/support

**Comment by SeparateRecords** [comment] 2022-11-07 05:31
Have sort of figured out what's going on here. `~/Library/Application\ Support/fig/state.json` contains an incorrect value.

Can you:
1. Run `cat ~/Library/Application\ Support/fig/state.json` and send the output here
2. Run `ls -ld ~/Library/Application\ Support/fig/state.json` and send the output here
3. Try `rm ~/Library/Application\ Support/fig/state.json`, then run `fig`, right click → Refresh
4. If that doesn't work, run `echo '{}' > ~/Library/Application\ Support/fig/state.json`, then try refreshing Fig again

**Comment by vinodsptharsha** [comment] 2022-11-07 08:57
> Have sort of figured out what's going on here. `~/Library/Application Support/fig/state.json` contains an incorrect value.
> 
> Can you:
> 
> 1. Run `cat ~/Library/Application\ Support/fig/state.json` and send the output here
> 2. Run `ls -ld ~/Library/Application\ Support/fig/state.json` and send the output here
> 3. Try `rm ~/Library/Application\ Support/fig/state.json`, then run `fig`, right click → Refresh
> 4. If that doesn't work, run `echo '{}' > ~/Library/Application\ Support/fig/state.json`, then try refreshing Fig again

4th option did the trick! Thank you.

**Comment by Bubbleinpit** [comment] 2022-11-07 13:10
@SeparateRecords

**Comment by Bubbleinpit** [comment] 2022-11-07 13:22
@SeparateRecords 
`cat ~/Library/Application\ Support/fig/state.json`:
Nothing
`ls -ld ~/Library/Application\ Support/fig/state.json`:

**Comment by ArAsHCoding** [comment] 2022-11-07 15:57
It worked! After running the step 4 :)
Thank you.

**Comment by ascraig** [comment] 2022-11-07 19:37
I was also able to fix the issue using step 4.

Thank you! @SeparateRecords

**Comment by BlackMoonWolf** [comment] 2022-11-07 21:22
> 2\. run `echo '{}' > ~/Library/Application\ Support/fig/state.json`, then try refreshing Fig again

This appears to have cleared up the issue. ^

Thanks, @SeparateRecords!

**Comment by AkexStar** [comment] 2022-11-08 14:20
> Have sort of figured out what's going on here. `~/Library/Application Support/fig/state.json` contains an incorrect value.
> 
> 已经知道这里发生了什么。 ~/Library/Application Support/fig/state.json 包含一个不正确的值。
> 
> Can you:
> 
> 需要你尝试：
> 
> 1. Run  运行`cat ~/Library/Application\ Support/fig/state.json` and send the output here 把输出发送到这里
> 2. Run  运行`ls -ld ~/Library/Application\ Support/fig/state.json` and send the output here 把输出发送到这里
> 
> Then to fix, try:
> 
> 然后尝试修复:
> 
> 1. Try  试试运行`rm ~/Library/Application\ Support/fig/state.json`, then run  然后运行`fig`, right click → Refresh ，右击→刷新
> 2. If that doesn't work, run  如果没用，就跑`echo '{}' > ~/Library/Application\ Support/fig/state.json`, then try refreshing Fig again 然后再尝试

这个能够解决问题！Thanks a lot！多谢啦

**Comment by Alohaoh** [comment] 2022-11-09 21:25
Same here 
Something went wrong :(
Error: Failed setting user_id: EOF while parsing a value at line 1 column 0

mkdir -p '~/Library/Application Support/fig';
echo '{}' > '~/Library/Application Support/fig/state.json';
mkdir -p '~/.fig';
echo '{}' > ~/.fig/settings.json;

**Comment by grant0417** [comment] 2022-11-10 18:29
This should be fixed on 2.7.7, make sure to update and let us know if the issue is fixed!

**Closed by grant0417** 2022-11-10 18:29 UTC
Labels: type:bug, codebase:desktop

**Comment by antonydevanchi** [comment] 2022-11-11 18:52
> 2\. If that doesn't work, run `echo '{}' > ~/Library/Application\ Support/fig/state.json`, then try refreshing Fig again

fixed

**Comment by galzo** [comment] 2022-11-13 10:39
Same here. couldn't login or logout.
eventually, I found out that the problem was with `~/Library/Application\ Support/fig/state.json` being empty.
I added `{}` to that file, and it fixed it.
