### ISSUE TITLE
Fig dropdown not show

### ISSUE THREAD

**Issue by trcat** [withfig/fig#2888] opened 2024-01-26 01:44 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.6.4 (22G513)

### Expected behaviour

code key in iTerm, I can see a dropdown

### Actual behaviour

code key in iTerm, there is nothing

![image](https://github.com/withfig/fig/assets/23648263/56532a97-3b94-45e1-9367-5f8024406a12)

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  - cores: 4
  - mem: 16.00 GB
os-info:
  - macOS 13.6.4 (22G513)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/dayday
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: ead10b78-243a-497e-97e3-250a16e2e10e
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/dayday/Library/pnpm:/usr/local/lib/ruby/gems/3.2.0/bin:/usr/local/opt/ruby/bin:/Users/dayday/.deno/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/dayday/.fig/bin:/Users/dayday/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 26968
    - FIG_SET_PARENT: ead10b78-243a-497e-97e3-250a16e2e10e
```

**Comment by 2coo** [comment] 2024-01-26 04:32
same here

**Comment by JulienMetralPleaseApp** [comment] 2024-01-26 05:19
Same here, it happened when I updated to macOS version 14.3 (23D56)

**Comment by MP242** [comment] 2024-01-26 07:43
same for me ... on macOS 14.2.1 (23C71) with macbook Air M1.

**Comment by rostik32** [comment] 2024-01-26 09:27
I have been using fig for a year and I encountered the same problem a few days ago.

I have not updated Mac OS in the past few days, I have version 14.1.2 (23B92) MacbookAir m1

**Comment by Siddi-Q** [comment] 2024-01-26 16:46
Same here, it happened when I restarted my MacBook yesterday. I'm on macOS 13.6 (22G120) on the M1 Pro Macbook.

**Comment by 2coo** [comment] 2024-01-27 03:38
Guys, they rebranded `Fig` as `CodeWhisperer`.

Solution: uninstall `Fig` but install `AWS CodeWhisperer`

https://aws.amazon.com/blogs/devops/introducing-amazon-codewhisperer-for-command-line/

**Comment by trcat** [comment] 2024-01-27 03:51
> Guys, they rebranded `Fig` as `CodeWhisperer`.
> 
> Solution: uninstall `Fig` but install `AWS CodeWhisperer`
> 
> https://aws.amazon.com/blogs/devops/introducing-amazon-codewhisperer-for-command-line/

oh Fig’s home website has change and advise to install Code Whisperer. It works for me!

**Comment by danielweck** [comment] 2024-01-27 14:37
Duplicate of https://github.com/withfig/fig/issues/2885

**Comment by chaynabors** [comment] 2024-01-29 18:40
> Duplicate of https://github.com/withfig/fig/issues/2885

**Closed by chaynabors** 2024-01-29 18:40 UTC
Labels: NEED_TO_LABEL
