### ISSUE TITLE
fig doctor finds "Figterm socket does not exist at" error

### ISSUE THREAD

**Issue by mustafasoylu** [withfig/fig#890] opened 2022-02-03 00:37 UTC
### Description:
After updating to the below version, fig doctor finds this error "Figterm socket does not exist at /tmp/figterm-w0t0p0:xxxxx.socket" while using iterm2. I have no idea what this is and what is the reason for the error. However, it seems like the fig works without problem.

I checked this problem with terminal and vs code integrated terminal and both look good, **only iterm2 gives this error.**

<img width="648" alt="Screen Shot 2022-02-03 at 9 30 41" src="https://user-images.githubusercontent.com/57208521/152261198-e9e764a5-41d7-4335-8ac4-f2ec23662c0c.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2 21D49|1.0.55|/usr/local/Cellar/zsh/5.8_1/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B371) [Beta] [ABC] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /usr/local/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/soylu/.nvm/versions/node/v16.13.1/bin:/Users/soylu/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/soylu/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (7069) - /dev/ttys002
Current working directory: /Users/soylu
Current window identifier: 772/% (com.googlecode.iterm2)
Path: /Users/soylu/.nvm/versions/node/v16.13.1/bin:/Users/soylu/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/soylu/.fig/bin
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:1DC81975-A536-46D1-8C75-715321C327B6
  - FIG_INTEGRATION_VERSION=6
  - FIG_TERM=1
  - FIG_TERM_VERSION=4.0.1
MacOS Version: 12.2 21D49
Hardware:
  - Model Name: iMac
  - Model Identifier: iMac20,1
  - Chip: 
  - Cores: 6
  - Memory: 8 GB</pre>
</p>
</details>

**Comment by mschrage** [comment] 2022-02-03 02:35
@soylumutu does inserting text in this terminal session work correctly?

**Comment by benthecoder** [comment] 2022-02-08 00:18
I have the same issue

**Comment by mschrage** [comment] 2022-02-08 00:34
This will be fixed in the next release! It is a bug with the `fig doctor` diagnostic rather than the app itself.

**Comment by opeik** [comment] 2022-03-04 04:39
I'm having a similar issue where autocompletion doesn't work and `fig doctor` reports "Figterm socket does not exist" if running Fig via a Finder alias. Symlinks seem to work fine, but unfortunately symlinked apps don't show up on Spotlight whereas aliased apps do.

**Comment by mschrage** [comment] 2022-03-04 04:50
What do you mean "running Fig via a Finder"? If this is reproducible, that would be awesome!

**Comment by opeik** [comment] 2022-03-05 11:45
> @opeik What do you mean "running Fig via a Finder alias"? If this is reproducible, that would be awesome!

After a bit of investigation this may be more convoluted than I thought. I include Fig in my nix home-manager environment and alias any .app bundles in that generation to `~/Applications`. As I mentioned, Finder aliases show up in Spotlight results whereas symlinks don't. The rest of my apps work fine but Fig consistently has no autocompletion under these circumstances with the "Figterm socket does not exist" error. The nix store is read-only so that might be it? I'll have to experiment more to find a simpler reproduction case.

![Screen Shot 2022-03-05 at 19 38 42](https://user-images.githubusercontent.com/11566773/156881426-bf095daa-944e-4199-8670-18eb2162e686.png)

**Comment by mschrage** [comment] 2022-03-06 00:41
Hey @opeik! I think this has to do with your `nix` environment/packaging system. Fig stores its socket in `$TMPDIR`. Since you're launching Fig using `nix`, the value of the `$TMPDIR` environment variable that the macOS app reads, will not be the same as the value of `$TMPDIR` in your shell.

This causes `fig doctor` (and other shell integrations) to look for the socket in a different location, which explains this error as well as text saying "Could not link with terminal session" in the debugger.

Running Fig using `nix` will likely result in other errors since the app requires coordination between various binaries that may be running in different contexts. For best results, you should launch Fig.app for `/Applications` or `~/Applications`.

Can you also run `fig diagnostic` for me? I am curious to see the output.

**Comment by opeik** [comment] 2022-03-07 06:54
Sure thing! My nix config is here: https://github.com/opeik/nix. 

You're most likely after these two files:

- [pkg-from-app.nix](https://github.com/opeik/nix/blob/main/lib/modules/macos/pkg-from-app.nix#L7)
- [apps.nix](https://github.com/opeik/nix/blob/main/src/home/macos/apps.nix#L30)

 Here's the output of both `fig doctor` and `fig diagnostic`:

```
reimu in ~ 
❯ fig doctor
❌ Figterm socket does not exist at /tmp/figterm-AD28B2BD-3C9C-45E8-BF36-81C134F1DEC6.socket
FYI, looks like your dotfiles are symlinked.
If you need to make modifications, make sure they're made in the right place.

❌ Doctor found errors. Please fix them and try again.

If you are not sure how to fix it, please open an issue with fig issue to let us know!
Or, email us at hello@fig.io!


reimu in ~ 
❯ fig diagnostic
Fig Version: Version 1.0.55 (B383) [Australian] 
UserShell: /etc/profiles/per-user/opeik/bin/fish
Bundle path: /nix/store/qhkbscqvd3hbzfkdli4igvh6d884dbzg-Fig-1.0.55/Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/opeik/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: application is not present.
Hyper Integration: application is not present.
VSCode Integration: Extension is not installed.
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /etc/profiles/per-user/opeik/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/Users/opeik/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/opeik/.nix-profile/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: /Users/opeik
Current window identifier: 3589/% (com.apple.Terminal)
Path: /etc/profiles/per-user/opeik/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/Users/opeik/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/opeik/.nix-profile/bin
Fig environment variables:
  - TERM_SESSION_ID=AD28B2BD-3C9C-45E8-BF36-81C134F1DEC6
  - FIG_CHECKED_PROMPTS=1
  - FIG_ENV_VAR=1
MacOS Version: 12.2.1 21D62
Hardware:
  - Model Name: Mac mini
  - Model Identifier: Macmini9,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
```

**Comment by SeparateRecords** [comment] 2022-03-11 19:25
Going to close this issue as the figterm socket error should be fixed now 🙂

@opeik would love if you could make a new issue with this information!

**Closed by SeparateRecords** 2022-03-11 19:25 UTC

**Comment by opeik** [comment] 2022-03-12 11:49
New update seems to have fixed it, thanks!
