### ISSUE TITLE
not supported on warp terminal

### ISSUE THREAD

**Issue by ngprnk** [withfig/fig#1837] opened 2022-09-27 16:48 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Issue Details

 support for warp terminal

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.61 (B528) [U.S.]
hardware-info:
  - model: MacBook Air
  - model-id: MacBookAir10,1
  - chip-id: Apple M1
  - cores: 8 (4 performance and 4 efficiency)
  - mem: 16 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/nischalgautam/Developer/fit.ai/my-turborepo/apps/e2e/cypress
  - exe-path: /Users/nischalgautam/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - TERM: xterm-256color
    - SHELL: /bin/zsh
    - PATH: /Users/nischalgautam/.bun/bin:/opt/homebrew/opt/ruby/bin:/Users/nischalgautam/Library/Caches/fnm_multishells/45125_1664297221349/bin:/Users/nischalgautam/.bun/bin:/opt/homebrew/opt/ruby/bin:/Users/nischalgautam/Library/Caches/fnm_multishells/44861_1664297216900/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/nischalgautam/.cargo/bin:/Users/nischalgautam/.fig/bin:/Users/nischalgautam/.local/bin:~/flutter/bin:~/flutter/bin
    - FIG_PID: 44764
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment] 2022-09-27 23:35
Duplicate of #785

**Closed by mschrage** 2022-09-27 23:35 UTC
Labels: NEED_TO_LABEL
