### ISSUE TITLE
Fig with tmux and zsh not working

### ISSUE THREAD

**Issue by roitalpaz** [withfig/fig#411] opened 2021-08-31 06:35 UTC
### Description:

While running fig inside iterm with tmux and zsh I got the following errors:

I started to type `git commit`

![image](https://user-images.githubusercontent.com/77916282/131453268-b45e0d6c-918a-418c-9eef-a47cabd269e3.png)

also after first running of fig I got:
![image](https://user-images.githubusercontent.com/77916282/131453813-951d06af-285f-4f81-81f0-f9fd35a1b245.png)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [ABC] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/roitalpaz/.fig/bin/fig
Accessibility: true
Number of specs: 188
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/roitalpaz/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: true
Symlinked dotfiles: true
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (1076) - ttys001
Current working directory: /Users/roitalpaz/git/infra/src/local
Current window identifier: 16225/E3F68297-6386-49FD-B003-21621B642B22% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by koz** [comment] 2021-08-31 14:54
Same issue as mine https://github.com/withfig/fig/issues/401

**Comment by mschrage** [comment] 2021-09-01 04:16
@roitalpaz The fix for the `zsh` issue is running stty -istrip in the affected terminal window.

**Comment by fwesss** [comment] 2021-09-02 22:53
Duplicate of https://github.com/withfig/fig/issues/405

**Closed by fwesss** 2021-09-02 22:53 UTC

**Comment by roitalpaz** [comment] 2021-09-03 07:28
the fix is not working for me, plus It is very hard to type it because the shell just keeps writing garbage
