### ISSUE TITLE
Error: Failed setting user_id: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by CoolJosh0221** [withfig/fig#2008] opened 2022-11-07 14:17 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

I face this error after logging in to fig.
<img width="585" alt="Screen Shot 2022-11-07 at 10 15 38 PM" src="https://user-images.githubusercontent.com/88709160/200332230-aa12a417-0b30-4dd1-bcac-a0cb77fab827.png">

**Comment by odonckers** [comment] 2022-11-07 15:40
I was also having the same issue. All of the sudden, it stopped throwing an error and just stopped sending me confirmation emails. #2009

**Comment by skrollme** [comment] 2022-11-07 16:49
I was able to install fig.io (fresh installation on latest MacOS Ventura) and request the token via email. But after I enter the token I received, I get the same message as on the screenshot above.

**Comment by lmeier** [comment] 2022-11-07 18:25
Getting this as well

**Comment by fegrimaldi** [comment] 2022-11-07 18:38
Have this issue as well. New Installation (today). settings and state json are empty.

 fig doctor reports:

✘ Settings Corruption: Fig settings file is corrupted
Attempting to fix automatically...
Re-running check...

✘ Settings Corruption: Fig state file is corrupted


✘ Doctor found errors. Please fix them and try again.

**Comment by skrollme** [comment] 2022-11-07 19:20
Maybe related to https://github.com/withfig/fig/issues/1997. You also find some workarounds there

**Comment by mschrage** [comment] 2022-11-07 22:18
We have a fix coming for this soon. In the meantime, if you run `fig doctor` twice it should resolve the issue.

**Comment by CoolJosh0221** [comment] 2022-11-08 10:43
> We have a fix coming for this soon. In the meantime, if you run `fig doctor` twice it should resolve the issue.
<img width="1023" alt="Screen Shot 2022-11-08 at 6 42 33 PM" src="https://user-images.githubusercontent.com/88709160/200544226-336d364d-328f-4349-996b-6149b8eedc1b.png">

Unfortunately, it does not work.

**Comment by CoolJosh0221** [comment] 2022-11-08 10:52
> Maybe related to #1997. You also find some workarounds there

thanks, it works now!

**Comment by grant0417** [comment] 2022-11-10 18:29
This should be fixed on 2.7.7, make sure to update and let us know if the issue is fixed!

**Closed by grant0417** 2022-11-10 18:29 UTC
Labels: type:bug, os:macos
