### ISSUE TITLE
Fig suddenly stopped working

### ISSUE THREAD

**Issue by DTcloudOps** [withfig/fig#2523] opened 2023-05-11 13:16 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 11.7.6 (20G1231)

### Expected behaviour

Fig Autocomplete/Suggestions dropdown

### Actual behaviour

No Fig Autocomplete/Suggestions dropdown

### Steps to reproduce

Launching fig and typing cd/aws/git/docker/kubectl, etc.
<img width="542" alt="Screen Shot 2023-05-11 at 9 03 39 AM" src="https://github.com/withfig/fig/assets/121122357/ea7c7a6a-9233-44f4-963a-8c5d47329658">

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  - cores: 4
  - mem: 64.00 GB
os-info:
  - macOS 11.7.6 (20G1231)
environment:
  - shell: /bin/bash
  - terminal: iterm
  - cwd: /Users/dt
  - exe-path: /Users/dt/.fig/bin/fig
  - install-method: fig.dmg download from fig.io
  - env-vars:
    - FIG_PID: 6930
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - FIGTERM_SESSION_ID: 4c4f6bed-e404-4d51-9b1c-fb712f6c3ad1
    - FIG_SET_PARENT_CHECK: 1
    - PATH: /Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dt/.fig/bin:/Users/dt/.local/bin:/Users/dt/flutter/bin
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_TERM: 2.16.0
```

**Comment by FilipSwiatczak** [comment] 2023-05-11 13:51
Same here, started today 11th May 2023, Mac Monterey 12.1 Intel Core i9!

**Comment by mschrage** [comment] 2023-05-11 17:35
Looks like a duplicate of #2522

**Closed by mschrage** 2023-05-11 17:35 UTC
Labels: NEED_TO_LABEL
