### ISSUE TITLE
Why fig eating a lot of memory? 

### ISSUE THREAD

**Issue by temrb** [withfig/fig#1461] opened 2022-05-15 08:20 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Fig eats lot of memory @ idle... at this point I cant use this anymore because it eats as much as chrome when it's not being used.
<img width="269" alt="Screen Shot 2022-05-15 at 3 20 06 AM" src="https://user-images.githubusercontent.com/22056864/168463740-918da944-eb36-4f37-89c9-ff7899d6fca5.png">

### Environment

```bash
Desktop.
```

**Comment by rahulsarathy** [comment] 2022-05-20 01:07
It looks like Fig is using around 100 mb which is expected. If you see memory usages much higher than that, please let us know.

Thanks for reporting this issue!

**Comment by elalemanyo** [comment] 2023-03-22 12:07
Hi,
Any idea why in my case it uses so much memory?
<img width="1208" alt="shot2023-03-22 at 13 04 23@2x" src="https://user-images.githubusercontent.com/3856862/226900163-70c99363-a6ec-4497-95b8-73e3a9d07736.png">

Apple M1 Pro (2021)
macOS 13.2.1
fig_cli 2.14.2

**Comment by Shaurya50211** [comment] 2023-04-09 12:20
I am having the same issue:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/74823287/230772163-07175d1c-7cec-410e-bd0d-ec87c2480238.png">

**Comment by McAlm** [comment] 2023-04-20 15:55
Having the same issue, today fig consumed 1.3 GB RAM!!

**Comment by Shaurya50211** [comment] 2023-04-20 21:03
Not just ram, I've seen it drink up battery when laptop on sleep, might have to delete fig

**Comment by AlfinIndrawan** [comment] 2023-05-07 16:17
You can try issue #1625

Its already closed ,so to search you need to change the label open to closed issues in search

**Comment by renkosteenbeek** [comment] 2023-06-09 08:05
I've got it too.
Running fig settings autocomplete.history.disableLoading true doesn't have effect.

<img width="1419" alt="Screenshot 2023-06-09 at 10 05 21" src="https://github.com/withfig/fig/assets/929106/ac20f55c-97f4-4b02-b6ce-2ae5efa92ca5">

**Comment by ramalhov** [comment] 2023-06-13 12:23
@renkosteenbeek I'm having the same issue with an M1 Pro. Did you find a solution to the issue?

**Comment by renkosteenbeek** [comment] 2023-06-13 12:25
> @renkosteenbeek I'm having the same issue with an M1 Pro. Did you find a solution to the issue?

Nope I didn't.

**Comment by fansilva1991** [comment] 2023-06-14 14:07
Same issue here.

Running 

```
fig settings autocomplete.history.disableLoading true
```

It didn't solve the problem

**Comment by zefman** [comment] 2023-06-17 08:46
Same here!

<img width="572" alt="Screenshot 2023-06-17 at 09 46 29" src="https://github.com/withfig/fig/assets/1266503/b7243434-1e5e-4dc2-b0b8-6a0bc2a4836d">

**Comment by yidongw** [comment] 2023-06-27 18:18
Fig is eating 1.87GB memory in my M1 Pro, which is insane. Can someone open this issue again, please?

**Comment by ramalhov** [comment] 2023-06-27 18:24
@yidongw for me too. I ran the command below and I thought it had solved the issue, but a few days later It's now at 780MB. Might have to stop using it.

`fig settings autocomplete.history.disableLoading true`

**Comment by tomgreenhill** [comment] 2023-07-10 09:58
> @yidongw for me too. I ran the command below and I thought it had solved the issue, but a few days later It's now at 780MB. Might have to stop using it.
> 
> `fig settings autocomplete.history.disableLoading true`

I found the same issue today, used the command above and _so far, so good_ but will keep an eye on it over the coming days. Fingers crossed!

**Comment by SebiBasti** [comment] 2023-07-10 15:21
Same here. After disabling autocomplete everything is back to normal. Before it was at ~2gb memory.

**Comment by ScripterSugar** [comment] 2023-07-11 05:59
<img width="961" alt="image" src="https://github.com/withfig/fig/assets/19164553/03eb7aa4-b2d5-4c67-bc88-028187b1280a">

My fig is eating almost 10 GB of memory lol at this point I expect there be some kind of memory leak

**Comment by tixastronauta** [comment] 2023-07-13 12:59
Today Fig was hitting 8GB on my M1 Macbook Pro (32Gb ram). This is insane. I guess this issue should not be closed.

**Comment by cruzluna** [comment] 2023-07-13 13:46
I got one better...26.88 gb.  Executing `fig settings autocomplete.history.disableLoading true` and restarting fig seemed to lowered it to 45 mb. I will update this comment if the memory explodes in size again. 

![image](https://github.com/withfig/fig/assets/73450306/95d3ce4c-066f-4fda-a896-5f8a59beab99)

**Comment by o-az** [comment] 2023-07-15 14:39
> I got one better...26.88 gb. Executing `fig settings autocomplete.history.disableLoading true` and restarting fig seemed to lowered it to 45 mb. I will update this comment if the memory explodes in size again.
> 
> ![image](https://user-images.githubusercontent.com/73450306/253296518-95d3ce4c-066f-4fda-a896-5f8a59beab99.png)

close to mine. Restarting helps for the first few hours. This issue has been consistent for over a year. Memory leak?

**Comment by yidongw** [comment] 2023-07-17 03:27
Seems like we started a competition here

**Comment by cruzluna** [comment] 2023-07-17 12:37
I think this issue should be reopened especially if this is a common problem for others.

**Comment by o-az** [comment] 2023-07-18 00:47
@cruzluna there's a similar open issue. It might help if you also report your experience there. I'm doing that. 

https://github.com/withfig/fig/issues/2577

**Comment by temrb** [comment] 2023-07-27 08:02
i forgot this is still open. to solve the issue, I uninstalled btw

**Comment by CareTiger** [comment] 2023-08-05 03:44
i uninstalled fig today. insane for this app to consume so much memory. m1 macbook pro with 8GB RAM. bye bye

**Comment by pfcodes** [comment] 2023-08-05 03:54
Please re-open this issue. Fig is using 2GB for me.

**Comment by temrb** [comment] 2023-08-05 04:43
@pfcodes #2577

**Comment by msert29** [comment] 2023-08-05 18:49
Using Mac Sonoroma 14.0
Fig doctor reports no issues

<img width="1289" alt="FigUsage" src="https://github.com/withfig/fig/assets/20394518/34d0b60b-f3fe-4460-96a4-37ff6460b9ec">

**Comment by SebiBasti** [comment] 2023-08-07 06:56
@msert29 alright... you win! 😮

**Comment by ohmantics** [comment] 2023-08-07 20:53
Mac users: in Activity Monitor, go to the View menu and under Columns, enable "Real Private Memory." The Memory column you're reading now includes pages shared with other processes and is really only a measure of address space used, not actual memory pages.

I think you'll find that Fig isn't using that much actual memory, but has been rolling through address space. Likely lots of freed/all-zero pages are allocated, but not affecting other processes.

**Comment by CareTiger** [comment] 2023-08-07 21:31
doesnt explain why my M1's performance got drastically better after i uninstalled fig. i doubt your answer is a complete.

**Comment by pfcodes** [comment] 2023-08-09 07:13
> Mac users: in Activity Monitor, go to the View menu and under Columns, enable "Real Private Memory." The Memory column you're reading now includes pages shared with other processes and is really only a measure of address space used, not actual memory pages.
> 
> I think you'll find that Fig isn't using that much actual memory, but has been rolling through address space. Likely lots of freed/all-zero pages are allocated, but not affecting other processes.

Even if its a red herring I still get an alert from macOS saying almost out of memory with a list of open apps to force close every 30 seconds.

**Comment by chaynabors** [comment] 2023-08-09 19:29
Sorry, closing this in favor of https://github.com/withfig/fig/issues/2577

**Closed by chaynabors** 2023-08-09 19:29 UTC
Labels: NEED_TO_LABEL

**Comment by nastoMAD** [comment] 2024-01-17 15:45
> ### Sanity checks
> * [x]  I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
> * [x]  I have run `fig doctor` in the affected terminal session
> * [x]  I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)
> 
> ### Issue Details
> ### Description:
> > Please include a detailed description of the issue (and an image or screen recording, if applicable)
> 
> Fig eats lot of memory @ idle... at this point I cant use this anymore because it eats as much as chrome when it's not being used. <img alt="Screen Shot 2022-05-15 at 3 20 06 AM" width="269" src="https://user-images.githubusercontent.com/22056864/168463740-918da944-eb36-4f37-89c9-ff7899d6fca5.png">
> 
> ### Environment
> ```shell
> Desktop.
> ```

Same here, almost 1GB of ram in MAc

**Comment by booxood** [comment] 2024-01-22 08:23
<img width="812" alt="image" src="https://github.com/withfig/fig/assets/2151410/c840f7eb-03eb-4d7b-899d-69158ea5213b">

Same problem.

**Comment by charlieuki** [comment] 2024-01-25 13:38
Not only memory but it also drains my Mac battery fast - confirmed based on the high Energy Usage on Activity Monitor these few days.

**Comment by cruzluna** [comment] 2024-01-25 20:39
Well, Fig isn't fixing these issues anymore since being acquired by AWS. 

The options: 
    - switch to [code whisperer ](https://aws.amazon.com/blogs/devops/introducing-amazon-codewhisperer-for-command-line/)
    - find alternate (ie[ ohmyzsh autosuggestions](https://gist.github.com/n1snt/454b879b8f0b7995740ae04c5fb5b7df))
        - live with the issues as is
