### ISSUE TITLE
Fig breaks bashrc and messes up SwiftBar display

### ISSUE THREAD

**Issue by omeraloni** [withfig/fig#854] opened 2022-01-29 14:23 UTC
### Description:
Please see the last few comments in [697;DoneSourcing proceeds plug-in output · Issue #269 · swiftbar/SwiftBar](https://github.com/swiftbar/SwiftBar/issues/269), specifically [this comment](https://github.com/swiftbar/SwiftBar/issues/269#issuecomment-1024795348) that explains how Fig breaks bash and thus causing SwiftBar to show wrong text in macOS menu bar.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.1 21C52|1.0.55|/usr/local/Cellar/fish/3.3.1/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Fig Version: Version 1.0.55 (B365) [ABC] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/omer.a/.fig/bin/fig
Accessibility: true
Number of specs: 0
SSH Integration: false
Tmux Integration: false
Keybindings path: 
iTerm Integration: installed!
Hyper Integration: application is not present.
VSCode Integration: installed!
Docker Integration: true
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/sbin:/Users/omer.a/.fzf/bin:/Users/omer.a/.fig/bin:/Users/omer.a/.poetry/bin:/Users/omer.a/.pyenv/bin:/Users/omer.a/.git-fuzzy/bin:/Users/omer.a/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: fish (9196) - /dev/ttys002
Current working directory: /Users/omer.a
Current window identifier: 30692/% (com.googlecode.iterm2)
Path: /usr/local/sbin:/Users/omer.a/.fzf/bin:/Users/omer.a/.fig/bin:/Users/omer.a/.poetry/bin:/Users/omer.a/.pyenv/bin:/Users/omer.a/.git-fuzzy/bin:/Users/omer.a/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
Fig environment variables:
  - TERM_SESSION_ID=w0t0p0:9347D34F-FF06-483C-A2DC-D93D14B00ADF
  - FIG_TERM=1
  - FIG_INTEGRATION_VERSION=5
  - FIG_CHECKED_PROMPTS=1
  - FIG_ENV_VAR=1
  - FIG_TERM_VERSION=3
MacOS Version: 12.1 21C52
Hardware:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro16,2
  - Chip: 
  - Cores: 4
  - Memory: 16 GB</pre>
</p>
</details>

**Comment by macintacos** [comment] 2022-02-22 17:13
I'm seeing a very similar thing for when I'm running `kubectx` in iTerm. Funnily enough, I can't reproduce the issue in VSCode's terminal.

**Comment by mschrage** [comment] 2022-04-20 21:01
This issue has been fixed! I just forgot to close this issue.

**Closed by mschrage** 2022-04-20 21:01 UTC
