### ISSUE TITLE
does not work on vscode

### ISSUE THREAD

**Issue by lfmarino** [withfig/fig#1890] opened 2022-10-08 20:04 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

fig is not working on vscode zsh terminal

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B539) [ABC]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro16,1
  - chip-id: 
  - cores: 8
  - mem: 16 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/lfmarin/Sites/bridge
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_PARENT: c8aac014-1167-4b82-bbd9-f6d45c1dc176
    - FIG_PID: 5460
    - FIG_SET_PARENT: 826a962f-165b-4021-a005-9f41f048880c
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/lfmarin/.fig/bin:/Users/lfmarin/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 826a962f-165b-4021-a005-9f41f048880c
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by mschrage** [comment] 2022-10-08 20:31
Duplicate of #1883. This is fixed on our beta channel. See other issue for instructions on how to upgrade.

**Closed by mschrage** 2022-10-08 20:31 UTC
Labels: NEED_TO_LABEL
