### ISSUE TITLE
Fig - BSPWM.

### ISSUE THREAD

**Issue by igorcguedes** [withfig/fig#1888] opened 2022-10-07 19:07 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Feature Details

Please, support it for BSPWM!

**Comment by grant0417** [comment] 2022-10-07 21:02
How does adding the config of `bspc rule -a Fig state=floating` work? This should make the window float, if you look at the [additional config](https://fig.io/user-manual/linux#additional-configs) section of our Linux docs you can see other examples.

**Comment by mschrage** [comment] 2022-10-08 02:17
Closing as duplicate of #1791. See the suggestions there for advice on how you might be able to get autocomplete working with BSPWM.

**Closed by mschrage** 2022-10-08 02:17 UTC
Labels: type:integration-request, os:linux
