### ISSUE TITLE
Auto complete not working, fig doctor check passed as well

### ISSUE THREAD

**Issue by atharvaTyagi** [withfig/fig#2471] opened 2023-04-15 11:27 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.2 (21G320)

### Expected behaviour

I should be able to see autocompletion, unless fig say that there's an issue with my configuration.

### Actual behaviour

I'm not able to access auto complete in my terminal

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  - cores: 2
  - mem: 8.00 GB
os-info:
  - macOS 12.6.2 (21G320)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/atharvatyagi
  - exe-path: /Users/atharvatyagi/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 2c11ad98-8c53-467e-8362-409e0bc89bbf
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/atharvatyagi/.fig/bin:/Users/atharvatyagi/.local/bin:/Users/atharvatyagi/development/flutter/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 60321
    - FIG_SET_PARENT: 2c11ad98-8c53-467e-8362-409e0bc89bbf
```

**Comment by Mugilan-Codes** [comment] 2023-04-26 14:11
I had the same issue. Try quitting fig using `fig quit` and launch it again using `fig` command.

**Comment by mschrage** [comment] 2023-05-01 21:58
Closing since there is not enough information to reproduce this issue.

**Closed by mschrage** 2023-05-01 21:58 UTC
Labels: type:bug, NEED_TO_LABEL

**Comment by mSaurabh** [comment] 2023-09-02 17:27
> I had the same issue. Try quitting fig using `fig quit` and launch it again using `fig` command.

This worked for me. Thanks a ton!
