### ISSUE TITLE
Integrate Autocomplete with IntelliJ

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#25] opened 2021-01-28 20:30 UTC
The title says it all.

Please subscribe to this issue to get an update when the autocomplete integration with IntelliJ is ready :smile:

**Comment by maksnester** [comment] 2021-12-01 14:50
Fig is not so useful for my daily work without it :(

**Comment by mschrage** [comment] 2022-01-17 23:28
Duplicate of #49

**Comment by SeparateRecords** [comment] 2022-03-21 02:54
Closing in favor of issue 49 - check it out for details and updates!

**Closed by SeparateRecords** 2022-03-21 02:54 UTC
Labels: integration_request

**Comment by brendanfalk** [comment] 2022-03-21 04:18
(And if you want to test our experimental integration with JetBrains, please use: https://fig.io/docs/support/enabling-input-method)

**Comment by TapaiBalazs** [comment] 2022-03-21 17:53
@brendanfalk I tried, but sadly it doesn't work if you use JetBrains toolbox and install the IDE in a different folder. It fails at the second step not finding the IDE. Could it be somehow set to be configurable where to look for the IDE? 🤔

**Comment by TapaiBalazs** [comment] 2022-03-24 08:42
Okay, the error was that it did not find the folder under `~/Library/Application Support/JetBrains/WebStorm2021.3/`. I created that folder manually, then copied the installed contents to my custom plugins library `~/devtools/plugins/` (in my case). After that I needed to follow the above link and do the things. Now it works I have fig autocomplete in my Webstorm. :)
