### ISSUE TITLE
Allowing using fig without login or any sort of signup process

### ISSUE THREAD

**Issue by brandon-fryslie** [withfig/fig#2747] opened 2023-09-25 14:26 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my feature

### Description:
> Please include a detailed description of the feature (and an image or screen recording, if applicable)

I read about `fig` today and thought it looked very cool!  I wanted to try it out.  However, immediately upon installation it is asking me to sign up for an account.  I tried to use `fig` without signing in (searched online and github issues) but it seems like that might not be possible.  Since signups are also disabled, `fig` is completely unusable for anyone who wants to try it.  Personally I was on the fence and am very suspicious about any tool that requires me to log in to use basic functionality, but this is the nail in the coffin for me, personally.

I will try fig again when there is an open source version and I can use it without signing up or logging in.  IMO I should be able to autocomplete something like `cd` without depending on 3rd party hosted services.  Thanks for the effort, I wish you success.  But I think more experienced developers are going to hard pass on something like this (like Warp terminal).  I'm sure plenty of JS developers will sign up.

**Comment by mschrage** [comment] 2023-09-26 23:30
We hear you. We are doing our best to reduce friction to onboarding. Closing as duplicate of #606.

**Closed by mschrage** 2023-09-26 23:30 UTC
Labels: NEED_TO_LABEL
