### ISSUE TITLE
Double characters when using autocomplete

### ISSUE THREAD

**Issue by nicwhitts** [withfig/fig#629] opened 2021-11-24 11:14 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When i hit tab to auto complete a suggestion. I get an extra character at the start.
For example, i want to run `yarn run:ios`
I get:
`yarn rrun:ios`

with the two rr 

This seems to be new this week.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.0|Version 1.0.52 (B317)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.52 (B317) [British] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Nic/.fig/bin/fig
Accessibility: true
Number of specs: 210
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/Nic/.fig/user/keybindings
iTerm Integration: false 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: true
Only insert on tab: true
Installation Script: true
PseudoTerminal Path: Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (96830) - /dev/ttys013
</pre>
</p>
</details>

**Comment by mschrage** [comment] 2021-12-02 04:58
Hey @nicwhitts! This sounds very frustrating. What type of Mac do you have? This could be a performance issue on older hardware, if you type very quickly?

Would you mind sharing a screen recording of this behavior?

**Comment by nicwhitts** [comment] 2021-12-02 10:47
Hey, I will share a video soon. 

Just popped into my head, I only started experiencing this on the new MacBook m1 16 inch.

**Comment by mschrage** [comment] 2022-03-07 23:18
Closing as duplicate of #173

**Closed by mschrage** 2022-03-07 23:18 UTC
Labels: bug, codebase:macOS
