### ISSUE TITLE
Warp Unsupported

### ISSUE THREAD

**Issue by ChristianHardy** [withfig/fig#2896] opened 2024-01-30 14:13 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.3.0 (23D56)

### Expected behaviour

Warp need to be supported

### Actual behaviour

This message its being displayed:

✘ Terminal support: Unsupported terminal, if you believe this is a mistake or would like to see support for your terminal, run `fig issue`

  __CFBundleIdentifier: dev.warp.Warp-Stable

### Environment

```yaml
fig-details:
  - 2.17.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.3.0 (23D56)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.6.4/bin/fish
  - terminal: <unknown>
  - cwd: /Users/christianhardy/workshop
  - exe-path: /Users/christianhardy/.fig/bin/fig
  - install-method: brew
  - env-vars:
    - __CFBundleIdentifier: dev.warp.Warp-Stable
    - SHELL: /opt/homebrew/bin/fish
    - TERM: xterm-256color
    - FIG_SET_PARENT: 
    - PATH: /Users/christianhardy/.nvm/versions/node/v20.9.0/bin:/Users/christianhardy/.cargo/bin:/opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/christianhardy/.nvm/versions/node/v20.9.0/bin:/Users/christianhardy/.cargo/bin:/opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/bin:/Users/christianhardy/.fig/bin:/Users/christianhardy/.local/bin
    - FIG_PID: 2002
```

**Comment by mschrage** [comment] 2024-01-30 23:47
Duplicate of #785

**Closed by mschrage** 2024-01-30 23:47 UTC
Labels: NEED_TO_LABEL
