### ISSUE TITLE
Creating new workflow doesn't work

### ISSUE THREAD

**Issue by pnarielwala** [withfig/fig#2055] opened 2022-11-15 18:13 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

Through the UI, when trying to create a custom workflow, it allows me to create one.

### Actual behaviour

I get a double error toast message saying "A workflow with this name already exists"

### Environment

```yaml
fig-details:
  - 2.7.9
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/bash
  - terminal: iterm
  - cwd: /Users/pnarielwala/Development
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_PID: 18162
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - FIGTERM_SESSION_ID: f5d2b007-ad0e-4e4b-b2b6-5117f70b4213
    - PATH: /Users/pnarielwala/.nodenv/shims:/Users/pnarielwala/.nodenv/shims:/Users/pnarielwala/.rbenv/shims:/Users/pnarielwala/.rbenv/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/pnarielwala/.yarn/bin:/Users/pnarielwala/.nvm/versions/node/v14.16.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/pnarielwala/.fig/bin:/Users/pnarielwala/.local/bin
    - FIG_HOSTNAME: E-ParthNarielwala
    - FIG_WORKFLOWS_KEYBIND: ^f
    - FIG_TERM: 2.7.9
```

**Comment by mschrage** [comment] 2022-11-15 18:20
@pnarielwala thanks for reporting this. We're investigating right now.

**Comment by parssak** [comment] 2022-11-15 18:46
Hey @pnarielwala, just pushed a fix for this, should be good now

**Comment by chungweileong94** [comment] 2022-11-16 04:10
@parssak Is it a server-side fix? Because I'm still getting the same error with the latest version 2.7.9

**Comment by mschrage** [comment] 2022-11-16 04:33
@chungweileong94 try running `fig quit` and trying again?

**Comment by mschrage** [comment] 2022-11-16 04:34
Seems like there has been a regression cc @parssak

**Comment by parssak** [comment] 2022-11-16 15:15
😓 my bad, fixed again

**Closed by parssak** 2022-11-16 15:15 UTC
Labels: type:bug, workflows
