### ISSUE TITLE
Autocomplete options outputting ' and (

### ISSUE THREAD

**Issue by arminmon** [withfig/fig#427] opened 2021-09-02 12:22 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
The autocomplete has suddenly started putting in ' and ( instead of the actual values when pressing enter on the autocomplete menu.
The recording is self-explanatory: [Filebin .mov recording](https://filebin.net/daxh8xkcfrfutqim/Screen_Recording_2021-09-02_at_10.16.09_pm.mov)

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.2|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [Australian] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/[USERNAME]/.fig/bin/fig
Accessibility: true
Number of specs: 168
SSH Integration: true
Tmux Integration: true
Keybindings path: /Users/[USERNAME]/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/[USERNAME]/.volta/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (19629) - ttys002
Current working directory: /Users/[USERNAME]
Current window identifier: 42111/56ACF6B5-33A7-44D0-ADB1-691493902BC6% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment] 2021-09-02 17:24
Hey @arminmon! So sorry about this bug. Run `stty -istrip` to fix this! We're pushing a workaround for this in the next build.

**Comment by fwesss** [comment] 2021-09-02 21:30
Duplicate of https://github.com/withfig/fig/issues/405

**Closed by fwesss** 2021-09-02 21:30 UTC
