### ISSUE TITLE
no such widget history-substring-up|down

### ISSUE THREAD

**Issue by markfaine** [withfig/fig#2330] opened 2023-02-12 18:25 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Linux 5.19.0-31-generic - "Ubuntu"

### Expected behaviour

History should be cycled when the up or down arrow is pressed.

### Actual behaviour

```shell
No such widget `history-substring-search-up' # up arrow
#  or 
No such widget `history-substring-search-down' # down arrow
```

### Steps to reproduce

Press up arrow or down arrow in zsh

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: 12th Gen Intel(R) Core(TM) i9-12900H
  - cores: 14
  - mem: 62.47 GB
os-info:
  - kernel: 5.19.0-31-generic
  - distro: "Ubuntu"
  - distro-version: "22.10 (Kinetic Kudu)"
environment:
  - shell: /usr/bin/zsh
  - terminal: <unknown>
  - cwd: /home/mfaine
  - exe-path: /usr/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: :1
    - FIGTERM_SESSION_ID: 0f4f651c-cc6f-4116-b70d-c9e8672a9018
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - GLFW_IM_MODULE: ibus
    - GTK_IM_MODULE: ibus
    - PATH: /home/mfaine/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/mfaine/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/mfaine/.local/bin:/home/mfaine/bin:/home/mfaine/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/mfaine/.local/bin:/home/mfaine/.fig/bin:/home/mfaine/.local/share/fig/plugins/fzf-zsh-plugin_unixorn/bin:/home/mfaine/.fzf/bin
    - QT_IM_MODULE: ibus
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - XDG_CURRENT_DESKTOP: ubuntu:GNOME
    - XDG_SESSION_DESKTOP: ubuntu
    - XDG_SESSION_TYPE: x11
    - XMODIFIERS: @im=ibus
    - FIG_PID: 1566451
    - FIG_SET_PARENT: 0f4f651c-cc6f-4116-b70d-c9e8672a9018
```

**Comment by mschrage** [comment] 2023-05-02 01:30
This seems like an issue with your shell configuration. I cannot reproduce with the information provided. Closing for now.

**Closed by mschrage** 2023-05-02 01:30 UTC
Labels: type:bug, NEED_TO_LABEL
