### ISSUE TITLE
Company does not let me turn off secure keyboard entry

### ISSUE THREAD

**Issue by brendanfalk** [withfig/fig#820] opened 2022-01-25 23:20 UTC
A variety of companies mandate that their employees turn on secure keyboard entry.

Fig uses the functionality that secure keyboard entry blocks for hotkey management (e.g. tab/enter insert text, up and down arrows navigate, cmd+i toggles description).

If your company asks you to use secure keyboard entry but you want to use Fig, just email brendan AT fig.io.

Brendan will usually email the CEO / engineering manager directly and get approval for you. We have gone through security reviews at a bunch of the big tech companies and are used in heavily regulated companies too like fintechs, HIPAA compliant etc

**Comment by mschrage** [comment] 2022-01-25 23:35
Closing as duplicate of #764

**Closed by mschrage** 2022-01-25 23:35 UTC
Labels: codebase:macOS
