### ISSUE TITLE
unable to finish install 

### ISSUE THREAD

**Issue by JbOy80082** [withfig/fig#2834] opened 2023-11-22 10:52 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.1.1 (23B81)

### Expected behaviour

i keep ending up with the same issue unable to sign up on github even after it tells me that the connection has been successful. 

### Actual behaviour

Signups are currently disabled (status: 400 Bad Request)

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M2
  - cores: 8
  - mem: 8.00 GB
os-info:
  - macOS 14.1.1 (23B81)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/joshphilips
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - SHELL: /bin/zsh
    - __CFBundleIdentifier: com.googlecode.iterm2
    - PATH: /Users/joshphilips/Library/Caches/fnm_multishells/44329_1700649253641/bin:/Users/joshphilips/Library/Application Support/fnm:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
    - TERM: xterm-256color
```

**Comment by mschrage** [comment] 2023-12-05 22:18
Duplicate of #2748

**Closed by mschrage** 2023-12-05 22:18 UTC
Labels: NEED_TO_LABEL
