### ISSUE TITLE
Hitting Tab or Enter to autocomplete or run with Fig works incorrectly

### ISSUE THREAD

**Issue by idanielgarcia13** [withfig/fig#428] opened 2021-09-02 13:37 UTC
https://user-images.githubusercontent.com/40194108/131851648-720b8d38-2992-4baa-ae34-0b3e49f1cda6.mov

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Whenever I use Fig with iTerm2, the autocomplete shows up just fine but when I want to use it, hitting Enter or Tab just inserts some random character like ) or ' 

 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.1|Version 1.0.47 (B257)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/danielgarcia/.fig/bin/fig
Accessibility: true
Number of specs: 184
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/danielgarcia/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/danielgarcia/opt/anaconda3/bin:/Users/danielgarcia/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: /bin/zsh (43907) - ttys009
Current working directory: /Users/danielgarcia
Current window identifier: 30375/29CBEBB5-CCB0-483B-9CA7-0903BF59FBB2% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by fwesss** [comment] 2021-09-02 21:29
Duplicate of https://github.com/withfig/fig/issues/405

**Closed by fwesss** 2021-09-02 21:29 UTC
