### ISSUE TITLE
fig hangs on pip command

### ISSUE THREAD

**Issue by marcstein** [withfig/fig#2423] opened 2023-03-25 15:19 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

pip install shell-gpt --user

should install the library

### Actual behaviour

![Screenshot 2023-03-25 at 11 16 36 AM](https://user-images.githubusercontent.com/804069/227726057-996b4ec4-ff1c-479e-a45c-c8bb32f78eac.png)

simply hangs at this point. Most commands work fine in terminal Version 2.13 (447) and iTerm both this fails in both.

### Steps to reproduce

fails every time

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/marcstein
  - exe-path: /Users/marcstein/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 67720587-3cae-466e-8205-8fdfb5ba1bab
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.2
    - PATH: /Users/marcstein/.deta/bin:/Users/marcstein/.fig/bin:/opt/homebrew/Caskroom/miniconda/base/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/Users/marcstein/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/open-babel/3.1.1_1/bin:/Library/Apple/usr/bin:/Users/marcstein/.cargo/bin:/Users/marcstein/.fig/bin:/Users/marcstein/.local/bin:/Users/marcstein/go/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 45963
    - FIG_SET_PARENT: 67720587-3cae-466e-8205-8fdfb5ba1bab
```

**Comment by mschrage** [comment] 2023-05-01 23:41
Closing since I cannot reproduce. Please share a screen recording of the behavior.

**Closed by mschrage** 2023-05-01 23:41 UTC
Labels: type:bug, NEED_TO_LABEL
