### ISSUE TITLE
Fig Integration: WarpTerminal is not supported

### ISSUE THREAD

**Issue by wahibAbdou** [withfig/fig#2565] opened 2023-05-24 15:55 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.2.1 (22D68)

### Expected behaviour

to work fine with WarpTerminal

### Actual behaviour

command and aliases are working but not the menu

### Steps to reproduce

install warp and fig together

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/mvpro
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - PATH: /Users/mvpro/.nvm/versions/node/v14.15.1/bin:/opt/homebrew/opt/node@16/bin:/usr/local/opt/node@16/bin:/opt/homebrew/opt/mysql-client/bin:/opt/homebrew/opt/php@7.3/sbin:/opt/homebrew/opt/php@7.3/bin:/Users/mvpro/.composer/vendor/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mvpro/.fig/bin:/Users/mvpro/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: dev.warp.Warp-Stable
    - FIG_SET_PARENT_CHECK: 1
    - FIG_PID: 97346
    - FIG_SET_PARENT:
```

**Comment by Grady-Saccullo** [comment] 2023-05-25 16:57
Fig doesn't intend to support warp. Duplicate of #785

**Closed** 2023-05-30 17:16 UTC
Labels: NEED_TO_LABEL
