### ISSUE TITLE
no path completions after typing 'cd '

### ISSUE THREAD

**Issue by sleifer** [withfig/fig#965] opened 2022-02-20 17:07 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

First time exploring Fig. Debugging in Fig menu thinks everything is good. trying 'cd ' to get path completion shows animated ellipses for a bit then nothing. I've yet to have this work once even during onboarding.

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.55 (B381)|/usr/local/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.55 (B381) [U.S.] 
UserShell: /usr/local/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/simeon/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: 
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by sleifer** [comment] 2022-02-20 22:43
I did some searching of open issues and wonder if this is not related to zplug or secondarily powerlevel10k or zsh-z.

**Comment by sleifer** [comment] 2022-02-23 01:44
Installed 1.0.55 (B383). No change to this issue for me with fig doctor reporting Everything looks good!

**Comment by brendanfalk** [comment] 2022-02-23 02:03
Very likely related to https://github.com/withfig/fig/issues/920

**Comment by brendanfalk** [comment] 2022-02-25 18:26
Closing this as it is a duplicate of #920

**Closed by brendanfalk** 2022-02-25 18:26 UTC
