### ISSUE TITLE
add support to Warp

### ISSUE THREAD

**Issue by gentax** [withfig/fig#2243] opened 2023-01-19 10:03 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.1.0 (22C65)

### Expected behaviour

With older version of Warp terminal, Fig worked well

### Actual behaviour

executing `fig doctor` I got the following feedback
```
✔ ~/.zshrc contains valid fig hooks
✘ Fig Integration: WarpTerminal is not supported
```

in the past, it worked well...
Please fix it, I love to use them both!

### Environment

```yaml
fig-details:
  - 2.9.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.1.0 (22C65)
environment:
  - shell: /bin/zsh
  - terminal: <unknown>
  - cwd: /Users/pgenta/Sites/cne-event-integration-service
  - exe-path: /Users/pgenta/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - PATH: /Users/pgenta/.rvm/gems/ruby-3.0.0/bin:/Users/pgenta/.rvm/gems/ruby-3.0.0@global/bin:/Users/pgenta/.rvm/rubies/ruby-3.0.0/bin:/Users/pgenta/.nvm/versions/node/v16.16.0/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/pgenta/.fig/bin:/Users/pgenta/.local/bin:/Users/pgenta/.rvm/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: dev.warp.Warp-Stable
    - FIG_SET_PARENT_CHECK: 1
    - FIG_PID: 85364
    - FIG_SET_PARENT:
```

**Comment by chaynabors** [comment] 2023-02-08 00:58
Warp is using a similar but conflicting mechanism for providing their own completions so this isn't on the road map right now. Nobody is opposed to looking for a workaround but we don't have the bandwidth.

**Comment by jonatan-ivanov** [comment] 2023-03-13 08:13
@chaynabors Would keeping the issue open make sense so that you can track user interest better?

**Comment by chaynabors** [comment] 2023-03-29 23:29
That's fine

**Comment by noghartt** [comment] 2023-04-06 04:00
What are the points necessary to have Fig working in Warp?

**Comment by ferdroid8080** [comment] 2023-04-11 03:23
Fig + Warp = <3

**Comment by mschrage** [comment] 2023-05-02 19:36
Closing as duplicate of #785

**Closed by mschrage** 2023-05-02 19:36 UTC
Labels: type:bug, NEED_TO_LABEL
