### ISSUE TITLE
command not found: `__bp_install_after_session_init`

### ISSUE THREAD

**Issue by ligenlnron** [withfig/fig#1080] opened 2022-03-10 08:14 UTC
### Description:
(eval):545: command not found: __bp_install_after_session_init
__fig_reset_hooks:16: command not found: __bp_sanitize_string
__fig_reset_hooks:26: bad substitution
(eval):545: command not found: __bp_install_after_session_init
__fig_reset_hooks:16: command not found: __bp_sanitize_string
__fig_reset_hooks:26: bad substitution

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.2.1|Version 1.0.56 (B401)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B401) [搜狗拼音] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ron/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: zsh (34226) - /dev/ttys001
Current terminal session: w0t0p0:EB93A674-4E4A-4D8D-ADB0-818459319EDA
Current working directory: /Users/ron
Current window identifier: 9063/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment] 2022-03-10 19:37
Hey @ligenlnron! Can you share your `.zshrc`, `.zprofile` and `.profile` with me?

**Comment by mschrage** [comment] 2022-03-10 22:02
Hey @ligenlnron! We have a fix for this coming soon. The issue is due to sourcing your `~/.profile` from either `~/.zshrc` or `~/.zprofile`.

A quick workaround is to edit `~/.profile` and comment out Fig's shell integration manually:
```bash
# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
# eval "$(fig init bash pre)"

...

# Fig post block. Keep at the bottom of this file.
# eval "$(fig init bash post)"
```

**Comment by mschrage** [comment] 2022-03-10 22:03
Closing this issue as a duplicate of #1079

**Closed by mschrage** 2022-03-10 22:03 UTC
Labels: awaiting user reply
