### ISSUE TITLE
Duplicate characters with autocomplete (potential zsh autocomplete race condition)

### ISSUE THREAD

**Issue by jonbackhaus** [withfig/fig#781] opened 2022-01-15 14:40 UTC
### Description:
Sometimes, I see duplicate characters inserted when using TAB for completion. (This is maybe a personal problem, since I think Fig is expecting me to use RETURN?) See attached video for example of issue: 
1. first attempt is slow (i.e. pause after `ssh`), then TAB
2. second attempt is slow, then RETURN
3. third attempt is fast (i.e. no pause after `ssh`), then TAB

It looks like a race-condition where Fig is competing with the zsh auto-complete and I end up with a garbled result.

https://user-images.githubusercontent.com/10749098/149625748-740911b2-9eb4-4f61-99b6-3edb882cf0c4.mov

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.0.1|Version 1.0.53 (B339)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.53 (B339) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/Jonathan/.fig/bin/fig
Accessibility: true
Number of specs: 206
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/Jonathan/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/Users/Jonathan/.fig/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment] 2022-01-18 06:01
We’ve just updated how we get the edit buffer in zsh. It should be more performant as of v1.0.54z

**Comment by jonbackhaus** [comment] 2022-01-23 11:31
Seems much better! Thank you!

**Comment by SeparateRecords** [comment] 2022-01-23 23:32
Probably not super helpful but I actually ran into this on 1.0.54 last night while testing some updates to the deno spec. Noticed while using `git` completions in my fork of https://github.com/withfig/autocomplete

```console
$ fig --version
fig version 1.0.54 B359

$ fish --version
fish, version 3.3.1
```

**Comment by jonbackhaus** [comment] 2022-01-24 21:07
I saw other anomalous behavior this morning. I typed `ssh ` and pressed [Return] to select the first entry in the Fig menu. But instead of inserting "plex" it inserted "plexex" with a slight delay between drawing "plex" and the trailing "-ex" suffix. This isn't consistently repeatable so it's some kind of weird bug. 

```
❯ fig --version
fig version 1.0.54 B359
❯ zsh --version
zsh 5.8 (arm-apple-darwin21.1.0)
```

**Comment by brendanfalk** [comment] 2022-03-11 18:46
Duplicate of https://github.com/withfig/fig/issues/173

**Closed** 2022-04-15 17:15 UTC
Labels: type:bug, codebase:macos, codebase:autocomplete-app, codebase:figterm, performance
