### ISSUE TITLE
No way to skip email sign in

### ISSUE THREAD

**Issue by misolori** [withfig/fig#1234] opened 2022-03-31 16:56 UTC
### Description:

I would like to not share my email to setup a local tool and there is no way to continue

<img width="590" alt="CleanShot 2022-03-31 at 09 54 24@2x" src="https://user-images.githubusercontent.com/35271042/161109132-3c826ccb-2b30-407b-a0a3-a3e9952489df.png">

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B416)|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [U.S.] 
UserShell: /bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/miguelsolorio/.fig/bin/fig
Accessibility: false
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: true
VSCode Integration: false
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by mschrage** [comment] 2022-03-31 19:18
Hey @misolori! Thanks for this feedback. This is actually the expected behavior.

 I think the confusion is that Fig is not just a local autocomplete tool. Fig lets you con_fig_ure and syncing your development environment across devices.
 
<img width="942" alt="Screen Shot 2022-03-31 at 11 25 08 AM" src="https://user-images.githubusercontent.com/3155109/161124560-c84e8539-e601-4982-9678-10c538aaa1e4.png">

I'm closing this as a duplicate of #606.

**Closed by mschrage** 2022-03-31 19:18 UTC

**Comment by misolori** [comment] 2022-03-31 19:59
> Fig lets you con_fig_ure and syncing your development environment across devices

but what if I don't want to sync across devices? this is essentially blocking me from using this.

**Comment by SeparateRecords** [comment] 2022-04-01 07:25
@misolori The dotfiles / plugins features are completely optional, if you don't want to sync then you don't have to! To avoid entering my main email, personally I use Fastmail's [masked email](https://1password.com/fastmail/), and there are plenty of other temporary email services out there too.

We don't have immediate plans to skip entering an email, but I totally get that not everyone wants to (or can) use their actual email address.

If privacy is a concern for you we're happy to also go into detail about that!

**Comment by misolori** [comment] 2022-04-01 15:32
@SeparateRecords I think you are missing the point: requiring a login upfront for a desktop/local tool is gatekeeping, if you want people to use features like syncing/collaboration, then require it when they want to enable those features. I think the comments https://github.com/withfig/fig/issues/606 make it clear that I am not the only one feeling this way. 

> We don't have immediate plans to skip entering an email

That's a shame

**Comment by JimtotheB** [comment] 2022-04-06 02:52
Yeah, I installed this, hit this block and immediately uninstalled it. I have more I could say, but I'll leave it at that.
