### ISSUE TITLE
Could not sync remote dotfiles

### ISSUE THREAD

**Issue by NachoVazquez** [withfig/fig#1553] opened 2022-06-21 16:50 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I have dotfiles installed and it was working, but now every time I type `fig source` I get the message **Could not sync remote dotfile**

I have tried restarting fig and closing the terminal several times but that doesn't seems to help.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.58|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.58 (B461) [Beta] [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/opt/python/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nachovazquez/.nvm/versions/node/v16.15.1/bin:/Users/nachovazquez/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nachovazquez/.cargo/bin:/Users/nachovazquez/.fig/bin:/Users/nachovazquez/.local/bin:/Users/nachovazquez/.yarn/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/nachovazquez
  - CLI Installed: true
  - Executable Location: /Users/nachovazquez/.fig/bin/fig
  - Current Window ID: 6439/% (com.googlecode.iterm2)
  - Active Process: zsh (19541) - /dev/ttys001
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:7A6221CD-B5FE-4432-9F9C-99BBA87E43F9
    - PATH=/opt/homebrew/opt/python/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nachovazquez/.nvm/versions/node/v16.15.1/bin:/Users/nachovazquez/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nachovazquez/.cargo/bin:/Users/nachovazquez/.fig/bin:/Users/nachovazquez/.local/bin:/Users/nachovazquez/.yarn/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=19541
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

</p>
</details>

**Comment by grant0417** [comment] 2022-06-21 20:13
Hey @NachoVazquez, this seems to be a regression in the latest build and we should be pushing a fix soon!

**Comment by NachoVazquez** [comment] 2022-06-21 20:16
Awesome @grant0417 ! Thanks for the quick replay. I am looking forward to the release!

**Comment by grant0417** [comment] 2022-06-21 23:15
This is fixed now on stable!

**Closed by grant0417** 2022-06-21 23:15 UTC

**Comment by aboutaaron** [comment] 2022-06-21 23:27
@grant0417, is there a way to check that this error is fixed in the latest build? I had the same issue and just did an uninstall/reinstall on a brand new mac, and I'm still getting the `Could not sync remote dotfiles` error after installing some plugins. Am I missing something?

**Comment by tundera** [comment] 2022-06-22 14:49
> @grant0417, is there a way to check that this error is fixed in the latest build? I had the same issue and just did an uninstall/reinstall on a brand new mac, and I'm still getting the `Could not sync remote dotfiles` error after installing some plugins. Am I missing something?

I had the same issue and had to update my general settings to opt out of the beta releases. It doesn't look like this fix has made it to the beta version at this point.
