### ISSUE TITLE
not getting autocomplete suggestions in my terminal

### ISSUE THREAD

**Issue by Wassap124** [withfig/fig#2895] opened 2024-01-28 13:47 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 14.2.1 (23C71)

### Expected behaviour

I should see fig auto-completes

### Actual behaviour

I don't

### Steps to reproduce

- checked fig settings, autocomplete is enabled.
- i restarted fig
- i restarted my mac
- i tried to update - im running on the latest version

im just not getting auto-completes

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 16.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/alonkazimirsky/repos/env0
  - exe-path: /Users/alonkazimirsky/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 7a628d8e-283a-42c5-94df-72cae7f189aa
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/alonkazimirsky/.npm-packages/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/alonkazimirsky/.fig/bin:/Users/alonkazimirsky/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 805
    - FIG_SET_PARENT: 7a628d8e-283a-42c5-94df-72cae7f189aa
```

**Comment by Wassap124** [comment] 2024-01-28 13:52
https://github.com/withfig/fig/assets/17432424/224131ae-20cf-4c1d-9921-5663c5ae3067

**Comment by jthorupp** [comment] 2024-01-29 07:41
Having the same issue.

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 14.2.1 (23C71)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: <I don't want to share this>
  - exe-path: <I don't want to share this>/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 0beb5710-395f-43ae-b96a-9c304a598e44
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: <I don't want to share this>
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 38567
    - FIG_SET_PARENT: 0beb5710-395f-43ae-b96a-9c304a598e44
```

**Comment by HeathStratosphere** [comment] 2024-01-29 15:42
Same:

`fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.4.1 (22F770820d)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/heathmorris
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 21a3ed0a-1cc2-4a98-a078-68fc54143cc5
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/heathmorris/.nvm/versions/node/v20.10.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/heathmorris/.fig/bin:/Users/heathmorris/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 7447
    - FIG_SET_PARENT: 21a3ed0a-1cc2-4a98-a078-68fc54143cc5`

**Comment by HeathStratosphere** [comment] 2024-01-29 18:05
There are multiple threads like this, no one has any solutions except to switch to the successor AWS CodeWhisperer CLI. I just did and I'm back up and running, on Cursor.sh (IDE). I uninstalled fig also. Unfortunate and cryptic way to sunset a product.

**Comment by chaynabors** [comment] 2024-01-29 18:39
Duplicate of https://github.com/withfig/fig/issues/2885

**Closed by chaynabors** 2024-01-29 18:39 UTC
Labels: NEED_TO_LABEL

**Comment by Wassap124** [comment] 2024-01-30 05:57
[this](https://github.com/withfig/fig/issues/2885#issuecomment-1915357652) seems to have solved it for me
