### ISSUE TITLE
Fig disconnects/stops working when opening a new tab

### ISSUE THREAD

**Issue by kyleshepherd** [withfig/fig#1533] opened 2022-06-10 10:06 UTC
### Description:
Fig no longer works automatically. If I run `fig source` it will work in the tab I ran that command in, but any new tabs Fig will no longer work in.

https://user-images.githubusercontent.com/25406287/173042774-70d7f077-d033-4f87-a92b-3d4be3ee6977.mov

Pls fix I haven't been able to use Fig in months.

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.4.0 (21F79)|1.0.57|/opt/homebrew/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B450) [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /Users/kyleshepherd/google-cloud-sdk/bin:/Users/kyleshepherd/google-cloud-sdk/bin:/Users/kyleshepherd/google-cloud-sdk/bin:/Users/kyleshepherd/.nvm/versions/node/v14.17.4/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/kyleshepherd/.fig/bin:/Users/kyleshepherd/.local/bin:/bin:/Users/kyleshepherd/Go/bin:/bin:/Users/kyleshepherd/Go/bin:/bin:/Users/kyleshepherd/Go/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Air
  - Model Identifier: MacBookAir10,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 8 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: Unknown UserShell
  - Current Directory: /Users/kyleshepherd
  - CLI Installed: true
  - Executable Location: /Users/kyleshepherd/.fig/bin/fig
  - Current Window ID: 9414/% (com.googlecode.iterm2)
  - Active Process: zsh (8249) - /dev/ttys002
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:6CBB247E-4098-4705-A2CE-FEDFF4B94698
    - PATH=/Users/kyleshepherd/google-cloud-sdk/bin:/Users/kyleshepherd/google-cloud-sdk/bin:/Users/kyleshepherd/google-cloud-sdk/bin:/Users/kyleshepherd/.nvm/versions/node/v14.17.4/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/kyleshepherd/.fig/bin:/Users/kyleshepherd/.local/bin:/bin:/Users/kyleshepherd/Go/bin:/bin:/Users/kyleshepherd/Go/bin:/bin:/Users/kyleshepherd/Go/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=8249
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by SeparateRecords** [comment] 2022-06-14 04:12
Wow this is very strange. Not showing at _all_ in the second tab.

* In the terminal tab where it's not working, could you type out `git commit` (_don't press enter!_), then click the ◧ Fig icon in your menubar, hover over the debugger, and send a screenshot?

<img width="612" alt="Screen Shot 2022-05-20 at 7 42 37 pm" src="https://user-images.githubusercontent.com/52195359/173491589-7b90b9f4-9b82-4fe7-b1e0-36d402b43ec2.png">

* Can you make a quick screen recording? Two terminal windows, in one, could you run these two commands:
  * `FIG_LOG_LEVEL=DEBUG`
  * `fig debug logs`
* Then, in the other window, type out a command. That way we can see exactly what's happening :)

Let me know if you'd like some clarification!

**Comment by SeparateRecords** [comment] 2022-06-15 00:52
Thanks so much for the video/screenshot - looks like the issue is that fig is interpreting your autosuggestions (history?) as typed text.

We've got another issue open for this so I'll close it in favor of that :) really appreciate all the detail!

For now, the workaround is to change your autosuggestion color. It's the same as your foreground right now, so figterm can't tell the difference between typed text and suggestion.

**Comment by kyleshepherd** [comment] 2022-06-15 06:13
Ah I see! I wasn’t able to find where in iTerm to change the autosuggestion colour, do you have any pointers?

**Comment by kyleshepherd** [comment] 2022-06-15 10:25
Yep, you were totally right! My autosuggestion colour had broke due to an error in `zsh-syntax-highlighting`. Updating that to the latest commit fixed this for me! Thanks for your help!!

**Comment by SeparateRecords** [comment] 2022-06-17 00:33
Very interesting that updating zsh-syntax-highlighting fixed this! Do you know what version you were on before? Would help us a lot to narrow down the issue

**Closed** 2022-07-18 08:53 UTC
