### ISSUE TITLE
fig not working in vs code terminal

### ISSUE THREAD

**Issue by scolestock** [withfig/fig#1885] opened 2022-10-07 02:31 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

Fig is working correctly in iTerm, but in a vscode terminal window, it is not working despite restarting vs code, a good report from fig doctor inside vs code, and a fig restart inside vs code.

### Environment

```yaml
fig-details:
  - desktop-version: Version 1.0.62 (B539) [U.S.]
hardware-info:
  - model: MacBook Pro

os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - exe-path: /Users/scott/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_PID: 34286
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.2.0
    - PATH: /Users/scott/.nvm/versions/node/v16.14.2/bin:/Users/scott/.yarn/bin:/Users/scott/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/mysql-client@5.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/scott/.nvm/versions/node/v16.14.2/bin:/Users/scott/.yarn/bin:/Users/scott/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/mysql-client@5.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/scott/.fig/bin:/Users/scott/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: 6834ba6d-c0ee-4e87-acec-a21181d49cca
    - FIG_PARENT: 6834ba6d-c0ee-4e87-acec-a21181d49cca
    - FIG_SET_PARENT: 6834ba6d-c0ee-4e87-acec-a21181d49cca
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true
```

**Comment by mschrage** [comment] 2022-10-07 18:41
Closing as duplicate of #1883 - see that issue for more details.

**Closed by mschrage** 2022-10-07 18:41 UTC
Labels: NEED_TO_LABEL
