### ISSUE TITLE
Opening Dashboard and Settings displays empty window

### ISSUE THREAD

**Issue by sowizz** [withfig/fig#2047] opened 2022-11-14 13:56 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 10.15.7 (19H1824)

### Expected behaviour

Setting and Dashboard contents to be displayed.

### Actual behaviour

I can only see empty window.

![image](https://user-images.githubusercontent.com/1541634/201677910-5bd20968-a041-48de-a806-7a82e8c54657.png)

### Steps to reproduce

Not sure, I've followed instruction on how to install and setup fig and when it's all done I cannot access settings and dashboard.

### Environment

```yaml
fig-details:
  - 2.7.8
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 10.15.7 (19H1824)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/sowizz
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 4841629f-77e0-4bd6-bd9c-0ce1689a7b97
    - FIG_HOSTNAME: b8098a5103ed
    - FIG_TERM: 2.7.8
    - PATH: /Users/sowizz/.poetry/bin:/Users/sowizz/.poetry/bin:/usr/local/Cellar/pyenv-virtualenv/HEAD-cc9d5f1/shims:/Users/sowizz/.pyenv/shims:/Users/sowizz/.pyenv/bin:/usr/local/opt/openssl@3/bin:/usr/local/opt/node@16/bin:/usr/local/sbin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sowizz/.fig/bin:/Users/sowizz/.local/bin:/Users/sowizz/Library/Android/sdk/emulator:/Users/sowizz/Library/Android/sdk/tools:/Users/sowizz/Library/Android/sdk/tools/bin:/Users/sowizz/Library/Android/sdk/platform-tools
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 3709
    - FIG_PARENT: 4841629f-77e0-4bd6-bd9c-0ce1689a7b97
    - FIG_SET_PARENT: 4841629f-77e0-4bd6-bd9c-0ce1689a7b97
```

**Comment by grant0417** [comment] 2022-11-14 21:35
Going to close this as duplicate of #2028

The current version broke support for macOS versions below 11.3, a new version 2.7.9 will be out soon to fix this!

**Closed by grant0417** 2022-11-14 21:35 UTC
Labels: type:bug
