### ISSUE TITLE
Removing default keybindings will not actually override default behavior.

### ISSUE THREAD

**Issue by vvzvlad** [withfig/fig#1160] opened 2022-03-23 10:56 UTC
### Description:
Immediately after installation everything worked fine, but after some time I see prompts like this:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/3315944/159675799-4ecfe6e1-929a-40d8-b6af-dfd650c78063.png">
Reinstalling the program solves the problem, but as soon as I go into the settings, everything crashes. 

Also, in my opinion, the "insert selected" button setting doesn't work correctly. I removed "enter" from there, because I want to press enter to do the typed command, not the first sentence, and replaced it with "right", but pressing enter still substitutes the proposed fig. Here in this video I first pressed "enter" and then "right", the behavior is the same. In addition, the problem above is present. 

https://user-images.githubusercontent.com/3315944/159683792-ce82035c-2341-4a78-9822-028f4460cc93.mov

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.3.0 (21E230)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B414) [Lipton 3.4]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/opt/X11/bin:/usr/local/CrossPack-AVR/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/vvzvlad/.local/bin:/Users/vvzvlad/.fig/bin:/Users/vvzvlad/.local/bin:/Users/vvzvlad/.local/bin:/Users/vvzvlad/.local/bin:/usr/local/sbin/
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,4
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.3.0 (21E230)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/vvzvlad
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 26846/% (com.apple.Terminal)
  - Active Process: zsh (6669) - /dev/ttys015
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=2C30188E-F08B-4E93-B360-0D231172E6DB
    - PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/opt/X11/bin:/usr/local/CrossPack-AVR/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/vvzvlad/.local/bin:/Users/vvzvlad/.fig/bin:/Users/vvzvlad/.local/bin:/Users/vvzvlad/.local/bin:/Users/vvzvlad/.local/bin:/usr/local/sbin/
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by mschrage** [comment] 2022-03-23 17:48
Hey @vvzvlad, it seems like there are two issues going on.

1. The autocomplete window appearance. I have no idea why the full list of suggestions aren't being displayed. This is very unusual. If you type `git co`, does the popup still only show the description?

2. Settings not working. The change you made to the "Insert Selected" keybinding looks good. It seems like the settings updates aren't being applied.

Can you run `fig doctor --verbose` and share the output here?

**Comment by vvzvlad** [comment] 2022-03-23 18:25
1)Fig correctly prompts, and correctly comments with a command description, and correctly inserts by "enter" or "right", but still does not show the list. 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/3315944/159769039-4b4271cc-27d1-4a18-97e6-815117d38693.png">

2)Yes, the settings don't work. I remove the "esc" binding from "Hide autocomplete", but after that it still triggers and removes the window.

>>Can you run fig doctor --verbose and share the output here?
```

[$] fig doctor --verbose                                           [21:24:36]
Let's check if you're logged in...
✔ Logged into Fig

Let's check your dotfiles...
✔ .bashrc contains valid fig hooks
✔ .profile contains valid fig hooks
✔ .bash_profile contains valid fig hooks
✔ .zshrc contains valid fig hooks
✔ .zprofile contains valid fig hooks
✔ 00_fig_pre.fish contains valid fig hooks
✔ 99_fig_post.fish contains valid fig hooks

Let's make sure Fig is running...
✔ Fig bin exists
✔ PATH contains ~/.local/bin and ~/.fig/bin
✔ Fig is running
✔ Fig socket exists
✔ Daemon
✔ Figterm socket
✔ Insertion lock does not exist
✔ PATH and PseudoTerminal PATH match

Let's check if your system is compatible...
✔ OS is supported

Let's check fig diagnostic...
✔ Installation script
✔ Compatible shell
✔ Fig app installed in the right place
✔ Autocomplete is enabled
✔ Fig CLI path
✔ Accessibility enabled
✔ Secure keyboard input disabled

Let's check your terminal integrations...


Fig still not working? Run fig issue to let us know!
Or, email us at hello@fig.io!
```

**Comment by vvzvlad** [comment] 2022-03-23 18:34
If I delete fig and put it again, it starts working. But if after that I go to settings and change there the parameter "insert selected" from "enter" to "right", everything breaks and doesn't work anymore. 

Maybe this will help, but the bottom of the menu looks different, the font is different size in situations when it works and when it doesn't:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/3315944/159770833-5b36ed2f-39a2-40d8-a669-0be6c400b430.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/3315944/159771018-81447354-2195-4eb7-b133-7592eb710b06.png">

**Comment by mschrage** [comment] 2022-03-23 19:50
Hmm I can't reproduce. Can you run `cat ~/.fig/settings.json`?

**Comment by vvzvlad** [comment] 2022-03-23 19:53
```
[$] cat ~/.fig/settings.json                                                                  [22:51:41]
{
  "app.hideMenubarIcon": false,
  "app.launchOnStartup": false,
  "autocomplete.fontSize": -1,
  "autocomplete.keybindings.right": "insertSelected",
  "autocomplete.preferVerboseSuggestions": true,
  "autocomplete.scrollWrapAround": false,
  "telemetry.disabled": true
}%    
```

**Comment by mschrage** [comment] 2022-03-23 19:54
Did you intentionally set `autocomplete.fontSize` to -1?

**Comment by vvzvlad** [comment] 2022-03-23 19:55
Yes

**Comment by mschrage** [comment] 2022-03-23 19:55
Can you explain why?

**Comment by vvzvlad** [comment] 2022-03-23 19:57
I don't like big windows and fonts, I have a small font in the terminal, so I reduced the font in fig

**Comment by vvzvlad** [comment] 2022-03-23 20:01
Yes, removing the font size, which became ""autocomplete.fontSize": null," fixed the appearance of the menu. Setting it to "0" ("autocomplete.fontSize": 0,) did not help. 
However, there's still the problem of the tooltip shown being entered by pressing "enter", even though the config is ""autocomplete.keybindings.right: "insertSelected""

**Comment by mschrage** [comment] 2022-03-23 20:01
"-1" is not a valid size. Try experimenting with other values?

You can customize the size of the window with `fig settings autocomplete.height VALUE`.

**Comment by mschrage** [comment] 2022-03-23 20:04
You might need to run something like `fig settings autocomplete.keybindings.enter ignore` to resolve the issue. This seems like a bug.

**Comment by vvzvlad** [comment] 2022-03-23 20:04
>"-1" is not a valid size. Try experimenting with other values?
Oh, I didn't know that. I assumed that if a menu item had no preset font size, then that menu item meant a correction from some standard size. So I clicked the button in the "shrink" field (down arrow), and got "-1". Since this is a program action, I didn't think it would allow a breaka
<img width="516" alt="Screen 2022-03-23 at 23 03 02" src="https://user-images.githubusercontent.com/3315944/159786071-7759ec6f-7d02-48e5-8de8-d77b280bbaf5.png">
ble value to be entered.

**Comment by vvzvlad** [comment] 2022-03-23 20:05
>Can you run cat ~/.fig/tools/all-settings.json?
[all-settings.json.txt](https://github.com/withfig/fig/files/8336232/all-settings.json.txt)

**Comment by vvzvlad** [comment] 2022-03-23 20:08
>You might need to run something like fig settings autocomplete.keybindings.enter ignore to resolve the issue. This seems like a bug on our end.

Yes, that helped.

**Comment by mschrage** [comment] 2022-03-23 20:12
>  Since this is a program action, I didn't think it would allow a breakable value to be entered.

We should fix this!

> However, there's still the problem of the tooltip shown being entered by pressing "enter", even though the config is ""autocomplete.keybindings.right: "insertSelected""

The issue here is that while the new keybinding is being added, the default keybinding for enter is not being overwritten. This  is another bug to fix. This command is a manual work around for the time being:`fig settings autocomplete.keybindings.enter ignore`

**Comment by grant0417** [comment] 2022-03-25 17:50
@phuctm97 can you fix

**Comment by mschrage** [comment] 2022-03-25 18:15
@phuctm97 can you fix the keybinding issue?

Essentially, if the user removes a keybinding that was a default, it must be explicitly set to `ignore` (unless it is defined elsewhere).

For example, if I open the Keybindings page and remove enter from "Insert selected", the value for `autocomplete.keybindings.enter` must be set to `ignore`.

**Comment by phuctm97** [comment] 2022-03-26 16:07
Oh didn't know about `ignore` value, will implement this on monday!

**Comment by phuctm97** [comment] 2022-03-28 06:16
A fix has been shipped. Please check and let me know if you still have the issues or we can close the issue @vvzvlad.

**Comment by vvzvlad** [comment] 2022-03-28 11:41
And how do I delete all the settings at all to check the application's behavior when I install it from zero? When I deleted ~/.fig/settings.json, it was restored as soon as I went into settings and changed a single item.

**Comment by mschrage** [comment] 2022-03-28 18:57
@vvzvlad you can `fig settings setting-name --delete` to restore the default value for that specific setting. 

Currently there is no way to restore all settings at once.

**Comment by mschrage** [comment] 2022-04-15 17:26
You can now remove default keybindings and the updates will be applied correctly!

**Closed by mschrage** 2022-04-15 17:26 UTC
Labels: type:bug, codebase:autocomplete-app, codebase:mission-control
