### ISSUE TITLE
Fig not working after macos update

### ISSUE THREAD

**Issue by andresfdel17** [withfig/fig#2887] opened 2024-01-25 22:48 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.6.4 (22G513)

### Expected behaviour

Autocomplete working normally

### Actual behaviour

Autocomplete doesn't working

### Environment

```yaml
fig-details:
  - 2.17.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  - cores: 2
  - mem: 16.00 GB
os-info:
  - macOS 13.6.4 (22G513)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/andresfdel13
  - exe-path: /Users/andresfdel13/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 02371681-df3a-421a-baff-a45a88c49f2f
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.17.0
    - PATH: /Users/andresfdel13/.nvm/versions/node/v20.10.0/bin:/usr/local/opt/node@18/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/andresfdel13/.fig/bin:/Users/andresfdel13/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 10149
    - FIG_SET_PARENT: 02371681-df3a-421a-baff-a45a88c49f2f
```

**Comment by danielweck** [comment] 2024-01-27 14:36
Duplicate of https://github.com/withfig/fig/issues/2885

**Comment by chaynabors** [comment] 2024-01-29 18:39
> Duplicate of https://github.com/withfig/fig/issues/2885

**Closed by chaynabors** 2024-01-29 18:39 UTC
Labels: NEED_TO_LABEL
