### ISSUE TITLE
Failed Install on Pop Os 22.04 (Ubuntu based distro)

### ISSUE THREAD

**Issue by CHFernandes** [withfig/fig#1782] opened 2022-09-14 03:16 UTC
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

I ran the command: `curl -SsL https://pkg.fig.io/install.sh | bash ` and recieved a message that could not find the package:

![image](https://user-images.githubusercontent.com/20386403/190051243-e22ff75c-7e15-41b4-b1dd-ce8c4bc4c4d6.png)

### Environment

```yaml
/////////////                carlos@pop-os 
         /////////////////////            ------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: Predator G3-572 V1.22 
   /////76767//7676767//////////////      Kernel: 5.19.0-76051900-generic 
  /////767676///*76767///////////////     Uptime: 16 hours, 18 mins 
 ///////767676///76767.///7676*///////    Packages: 2791 (dpkg), 45 (flatpak) 
/////////767676//76767///767676////////   Shell: zsh 5.8.1 
//////////76767676767////76767/////////   Resolution: 1920x1080, 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 42.3.1 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Papirus-Dark [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-7700HQ (8) @ 2.800GHz 
    /////767676767676767676767/////       GPU: NVIDIA GeForce GTX 1060 Mobile 
      ///////////////////////////         GPU: Intel HD Graphics 630 
         /////////////////////            Memory: 8037MiB / 31986MiB 
             /////////////
```

**Comment by mschrage** [comment] 2022-09-14 03:27
Thanks for reporting this @CHFernandes! We'll investigate... cc @squili

**Comment by squili** [comment] 2022-09-14 03:42
I've identified the root cause and have started a new deployment that should fix this. Please try again in an hour!

**Comment by mschrage** [comment] 2022-09-14 03:51
@CHFernandes I'm going to close this for the time being but if you try again and are still running into issues, we'll reopen.

Thanks for quick turn around @squili :)

**Closed by mschrage** 2022-09-14 03:51 UTC
Labels: type:bug, os:linux

**Comment by CHFernandes** [comment] 2022-09-14 10:37
It worked now, thank you guys!
