### ISSUE TITLE
Mac Terminal > `ssh user@` shows repeat entries

### ISSUE THREAD

**Issue by stevesweets** [withfig/fig#2319] opened 2023-02-08 14:30 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 12.6.0 (21G115)

### Expected behaviour

Suggest any servers that start with that user.

Eg

`ssh stevesweets@...`

I would expect to show me any servers i've connected to with that username. 

### Actual behaviour

`ssh user@...`

Brings up many duplicates

```
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
ssh user@127.0.0.1
```

Which is annoying if i have a few different servers on the same subnet, because it means I don't get the suggestions

### Steps to reproduce

I mean, it happens every time.

### Environment

```yaml
fig-details:
  - 2.14.0
hardware-info:
  - model: mbp 2021
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 32.00 GB
os-info:
  - macOS 12.6.0 (21G115)
environment:
  - shell: /bin/zsh
  - terminal: terminal
  - cwd: /Users/stephensweetland/Repo
  - exe-path: /Users/stephensweetland/.fig/bin/fig
  - install-method: unknown
  - env-vars:
    - FIGTERM_SESSION_ID: 118277d2-23f5-4f03-aa96-2d89198e6e1f
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.14.0
    - PATH: /Users/stephensweetland/.local/share/fig/plugins/git-open:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/stephensweetland/.fig/bin:/Users/stephensweetland/.local/bin:/Users/stephensweetland/Library/Application Support/JetBrains/Toolbox/scripts:/Users/stephensweetland/.local/share/fig/plugins/git-extra-commands_unixorn/bin:/Users/stephensweetland/.local/share/fig/plugins/git-extra-commands_unixorn/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 72948
    - FIG_SET_PARENT: 118277d2-23f5-4f03-aa96-2d89198e6e1f
```

**Comment by iWECon** [comment] 2023-04-06 02:24
Same #2438

**Comment by EmranMR** [comment] 2023-05-01 09:57
I have the same problem... I asked for help in Discord. Any updates? I even deleted my account and started fresh, I deleted all my ssh profiles and redone them. deleted fig reinstalled fig. Not sure where this cache is saved tbh. Would happily delete and start fresh if I could.... 😵‍💫

**Comment by mschrage** [comment] 2023-05-02 01:27
Hey @EmranMR. Try running `rm ~/.fig/fig.history` to delete your local shell history in Fig.

You might also try deleting your raw shell history (`rm .zsh_history`)

**Comment by mschrage** [comment] 2023-05-02 01:27
Closing as duplicate of #2438

**Closed by mschrage** 2023-05-02 01:27 UTC
Labels: type:bug, NEED_TO_LABEL

**Comment by EmranMR** [comment] 2023-05-02 11:54
> Hey @EmranMR. Try running `rm ~/.fig/fig.history` to delete your local shell history in Fig.
> 
> You might also try deleting your raw shell history (`rm .zsh_history`)

Hi Matt!
Thank you for the reply.
I did delete both history files however I still see the manyplicates... 🙈 would you like me to carry on the discussion in #2438 ?

**Comment by stevesweets** [comment] 2023-05-10 17:57
> Closing as duplicate of #2438

booooo 2438 is a duplicate of mine lol

**Comment by iWECon** [comment] 2023-05-11 01:48
> > Closing as duplicate of #2438
> 
> 
> 
> booooo 2438 is a duplicate of mine lol

🤣
