### ISSUE TITLE
(eval):545: command not found: __bp_install_after_session_init - After latest update

### ISSUE THREAD

**Issue by crebuh** [withfig/fig#1079] opened 2022-03-10 06:52 UTC
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

Today my fig client was updated. Now after each time I'm opening a new terminal I get this message. Still fig seems to work fine. 

`Last login: Thu Mar 10 06:50:57 on ttys001
(eval):545: command not found: __bp_install_after_session_init
__fig_reset_hooks:16: command not found: __bp_sanitize_string
__fig_reset_hooks:26: bad substitution
(eval):545: command not found: __bp_install_after_session_init
__fig_reset_hooks:16: command not found: __bp_sanitize_string
__fig_reset_hooks:26: bad substitution`

### Details:
|OS|Fig|Shell|
|-|-|-|
|macOS 12.2.1 (21D62)|1.0.56|/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>

# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B401) [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 8
  - Memory: 16 GB
## OS Info:
  - macOS 12.2.1 (21D62)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/crebuh
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 479/% (com.googlecode.iterm2)
  - Active Process: zsh (11062) - /dev/ttys004
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p1:27CAF99E-A7F4-4705-8239-192E1B0261ED
    - PATH=/Users/crebuh/.fastlane/bin:/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin:/Users/crebuh/google-cloud-sdk/bin:/Users/crebuh/.fastlane/bin:/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin:/Users/crebuh/.nvm/versions/node/v17.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/crebuh/flutter/bin:/Library/Apple/usr/bin:/Users/crebuh/.local/bin:/Users/crebuh/.fig/bin:/Users/crebuh/.local/bin:/Users/crebuh/.local/bin:/Users/crebuh/flutter/.pub-cache/bin:/Users/crebuh/Library/Android/sdk/build-tools/30.0.2:/Users/crebuh/.local/bin:/Users/crebuh/Library/Android/sdk/tools/bin:/Users/crebuh/Library/Android/sdk/platform-tools:/Users/crebuh/Library/Android/sdk/emulator:/Users/crebuh/Library/Android/sdk/build-tools/29.0.0:/Applications/Android Studio.app/Contents/gradle/gradle-5.1.1/bin:/Users/crebuh/.local/bin:/Users/crebuh/Library/Android/sdk/tools/bin:/Users/crebuh/Library/Android/sdk/platform-tools:/Users/crebuh/Library/Android/sdk/emulator:/Users/crebuh/Library/Android/sdk/build-tools/29.0.0:/Applications/Android Studio.app/Contents/gradle/gradle-5.1.1/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.2.0
    - FIG_CHECKED_PROMPTS=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

</p>
</details>

**Comment by sergiuwaxmann** [comment] 2022-03-10 12:44
I also have this issue after the update...

**Comment by mscherr-fastspot** [comment] 2022-03-10 14:26
+1 as well

**Comment by cow-coding** [comment] 2022-03-10 17:17
+1

**Comment by mschrage** [comment] 2022-03-10 21:59
We have a fix coming soon! The issue is due to sourcing your `~/.profile` from either `~/.zshrc` or `~/.zprofile`.
@cow-coding @crebuh  @mscherr-fastspot @ebarti @sergiuwaxmann

A quick workaround is to edit `~/.profile` and remove Fig's shell integration manually:
<img width="404" alt="Screen Shot 2022-03-10 at 1 59 06 PM" src="https://user-images.githubusercontent.com/3155109/157761762-f5491da4-3cf1-445a-a164-d4b312049a22.png">

**Comment by grant0417** [comment] 2022-03-11 00:43
This should be fixed, make sure you are running Fig v1.0.56 B403

**Closed by grant0417** 2022-03-11 00:43 UTC

**Comment by crebuh** [comment] 2022-03-11 07:09
Yeah it's fixed now :)
