### ISSUE TITLE
how to remove unwanted autocompletion?

### ISSUE THREAD

**Issue by wayou** [withfig/fig#2398] opened 2023-03-16 02:26 UTC
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.3.0 (22E5236f)

### Expected behaviour

Say I have a typo and now I want remove it from the autocomplete list.

I've removed all occurrence of the typo in `~/.fig/history` and restarted fig without luck.

### Actual behaviour

the typo items still in the autocomplete

### Environment

```yaml
fig-details:
  - 2.14.2
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.3.0 (22E5236f)
environment:
  - shell: /opt/homebrew/Cellar/fish/3.6.0/bin/fish
  - terminal: terminal
  - cwd: /Users/niusann
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_SET_PARENT: 76230FE1-EA57-4597-A2A7-0B1880E07525
    - FIG_TERM: 2.14.2
    - SHELL: /opt/homebrew/bin/fish
    - FIG_PARENT: 
    - TERM: xterm-256color
    - FIGTERM_SESSION_ID: a912d755-466b-4223-8186-0ddc31c8d15f
    - __CFBundleIdentifier: com.apple.Terminal
    - FIG_PID: 6805
    - PATH: /usr/local/opt/mysql@5.7/bin:/usr/local/opt/ruby/bin:/opt/homebrew/bin:/Users/niusann/.pyenv/shims:/Users/niusann/go/bin:/opt/local/bin:/Users/niusann/.gem/ruby/2.7.0/bin:/Users/niusann/.nvm/versions/node/v16.18.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/niusann/.fig/bin:/Users/niusann/.local/bin:/Users/niusann/go/bin
    - FIG_DISABLE_SENTRY: 1
```

**Comment by mschrage** [comment] 2023-05-01 23:31
Closing this a duplicate of #596

**Closed by mschrage** 2023-05-01 23:31 UTC
Labels: type:feature-request, codebase:autocomplete-app
